import MeasureTheory.BranchingWalk.Cloud.Basic
import MeasureTheory.BranchingWalk.Displace.Initial
import MeasureTheory.BranchingWalk.Tree.Realization

/-!
# Clouds generated by step fields

The multi-root construction is the primitive one: each root supplies its own
step field and initial position, and the cloud is their union.  The single-root
construction is the special case with the singleton root type `Unit`.
-/

namespace MeasureTheory

namespace BranchingWalk

open MeasureTheory.UlamHarris

namespace Cloud

/-- The cloud generated by a root-indexed step field and root-indexed initial
positions. -/
def ofRootIndexedStepField
    {Root α X : Type*} [AddCommMonoid X]
    (initial : Root → X) (step : Root → StepField α X)
    (time : TreeNode α → Time) : Cloud Time X where
  points t :=
    {x | ∃ r u,
      time u = t ∧
      realizedNode (step r) u ∧
      x = rootIndexedNodePosition initial step r u}

/-- The single-root case of `ofRootIndexedStepField`, indexed by `Unit`. -/
def ofStepField
    {α X Time : Type*} [AddCommMonoid X]
    (initial : X) (step : StepField α X)
    (time : TreeNode α → Time) : Cloud Time X :=
  ofRootIndexedStepField
    (fun _ : Unit => initial)
    (fun _ : Unit => step)
    time

@[simp] theorem ofRootIndexedStepField_points
    {Root α X Time : Type*} [AddCommMonoid X]
    (initial : Root → X) (step : Root → StepField α X)
    (time : TreeNode α → Time) (t : Time) :
    (ofRootIndexedStepField initial step time).points t =
      {x | ∃ r u,
        time u = t ∧
        realizedNode (step r) u ∧
        x = rootIndexedNodePosition initial step r u} :=
  rfl

@[simp] theorem ofStepField_points
    {α X Time : Type*} [AddCommMonoid X]
    (initial : X) (step : StepField α X)
    (time : TreeNode α → Time) (t : Time) :
    (ofStepField initial step time).points t =
      {x | ∃ u,
        time u = t ∧
        realizedNode step u ∧
        x = nodePosition initial step u} := by
  ext x
  simp [ofStepField, ofRootIndexedStepField,
    rootIndexedNodePosition, nodePosition]

end Cloud

end BranchingWalk

end MeasureTheory
