import Mathlib.Order.Filter.AtTopBot.Basic
import Mathlib.Order.Lattice.Nat
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Analysis.SpecificLimits.Basic
import Mathlib.Tactic.Ring

/-!
# Generalized inverse scales

This file contains the deterministic inverse operation used when a
small-deviation estimate is reindexed by an integer tube width.  No
monotonicity is imposed on the time scale: convergence to infinity is enough
for every threshold set to be nonempty.
-/

open Filter
open scoped BigOperators

namespace ProbabilityTheory.RandomWalk

/-- An integer time scale eventually dominates every constant multiple of the
square of its width.  This order-theoretic form avoids casts and is equivalent
to the usual assertion `L δ / δ² → ∞`. -/
def IsSuperquadraticScale (L : ℕ → ℕ) : Prop :=
  ∀ K : ℕ, Filter.Eventually (fun δ => K * δ ^ 2 ≤ L δ) atTop

/-- The first integer width whose time scale, with the conventional one-step
offset, reaches `n`.  When the threshold set is empty, `sInf` has the harmless
default value zero; all mathematical properties below assume that `L` tends
to infinity. -/
noncomputable def inverseScale (L : ℕ → ℕ) (n : ℕ) : ℕ :=
  sInf {δ | n ≤ L δ + 1}

/-- The upper inverse used together with `inverseScale`; this is the sequence
called `y(n) = x(n + 1) - 1` in the inverse-scale argument. -/
noncomputable def upperInverseScale (L : ℕ → ℕ) (n : ℕ) : ℕ :=
  inverseScale L (n + 1) - 1

private theorem inverseScale_set_nonempty {L : ℕ → ℕ}
    (hL : Tendsto L atTop atTop) (n : ℕ) :
    { δ | n ≤ L δ + 1 }.Nonempty := by
  obtain ⟨δ, hδ⟩ := (tendsto_atTop.1 hL n).exists
  exact ⟨δ, hδ.trans (Nat.le_add_right (L δ) 1)⟩

/-- The generalized inverse reaches its defining threshold. -/
theorem inverseScale_spec {L : ℕ → ℕ}
    (hL : Tendsto L atTop atTop) (n : ℕ) :
    n ≤ L (inverseScale L n) + 1 := by
  exact Nat.sInf_mem (inverseScale_set_nonempty hL n)

/-- The generalized inverse is no larger than any width reaching the same
threshold. -/
theorem inverseScale_le {L : ℕ → ℕ}
    {n δ : ℕ} (hδ : n ≤ L δ + 1) :
    inverseScale L n ≤ δ := by
  exact Nat.sInf_le hδ

/-- Raising the target cannot decrease the first width that reaches it. -/
theorem inverseScale_mono {L : ℕ → ℕ}
    (hL : Tendsto L atTop atTop) :
    Monotone (inverseScale L) := by
  intro n m hnm
  apply inverseScale_le
  exact hnm.trans (inverseScale_spec hL m)

/-- At the target generated by a width itself, the generalized inverse is no
larger than that width. -/
theorem inverseScale_scale_add_one_le (L : ℕ → ℕ) (δ : ℕ) :
    inverseScale L (L δ + 1) ≤ δ := by
  exact inverseScale_le le_rfl

/-- The other half of the inverse sandwich uses monotonicity of the original
scale.  This assumption is essential: convergence to infinity alone does not
control values at earlier widths. -/
theorem lt_inverseScale_scale_add_two {L : ℕ → ℕ}
    (hL : Tendsto L atTop atTop) (hmono : Monotone L) (δ : ℕ) :
    δ < inverseScale L (L δ + 2) := by
  by_contra h
  have hinv : inverseScale L (L δ + 2) ≤ δ := Nat.le_of_not_gt h
  have hscale := hmono hinv
  have hspec := inverseScale_spec hL (L δ + 2)
  omega

/-- A width lies between the lower and upper generalized inverses of its own
time scale. -/
theorem inverseScale_le_width_le_upperInverseScale {L : ℕ → ℕ}
    (hL : Tendsto L atTop atTop) (hmono : Monotone L) (δ : ℕ) :
    inverseScale L (L δ + 1) ≤ δ ∧
      δ ≤ upperInverseScale L (L δ + 1) := by
  constructor
  · exact inverseScale_scale_add_one_le L δ
  · have hupper := lt_inverseScale_scale_add_two hL hmono δ
    have hupper' : δ < inverseScale L (L δ + 1 + 1) := by
      simpa [Nat.add_assoc] using hupper
    simp only [upperInverseScale]
    omega

/-- Every strictly smaller width fails to reach the threshold. -/
theorem lt_threshold_of_lt_inverseScale {L : ℕ → ℕ}
    {n δ : ℕ} (hδ : δ < inverseScale L n) :
    L δ + 1 < n := by
  exact Nat.lt_of_not_ge fun hreach =>
    (not_le_of_gt hδ) (inverseScale_le hreach)

/-- At a positive generalized inverse, the preceding width has not reached
the target.  This is the inequality needed to control `x(n) / sqrt n`; the
value of `L` at `x(n)` can overshoot `n` and gives the wrong comparison. -/
theorem scale_pred_inverseScale_add_one_lt {L : ℕ → ℕ}
    {n : ℕ} (hx : 0 < inverseScale L n) :
    L (inverseScale L n - 1) + 1 < n := by
  apply lt_threshold_of_lt_inverseScale
  omega

/-- The inequality `L_(x(n)) ≥ n - 1` used in the inverse-scale argument. -/
theorem sub_one_le_scale_inverseScale {L : ℕ → ℕ}
    (hL : Tendsto L atTop atTop) (n : ℕ) :
    n - 1 ≤ L (inverseScale L n) := by
  exact Nat.sub_le_iff_le_add.mpr (inverseScale_spec hL n)

/-- If the original integer time scale tends to infinity, so does its
generalized inverse.  Monotonicity of `L` is not needed. -/
theorem tendsto_inverseScale_atTop {L : ℕ → ℕ}
    (hL : Tendsto L atTop atTop) :
    Tendsto (inverseScale L) atTop atTop := by
  rw [tendsto_atTop]
  intro b
  let B := ∑ δ ∈ Finset.range b, (L δ + 1)
  filter_upwards [eventually_ge_atTop (B + 1)] with n hn
  by_contra hnb
  have hinv : inverseScale L n < b := Nat.lt_of_not_ge hnb
  have hmember : inverseScale L n ∈ Finset.range b :=
    Finset.mem_range.mpr hinv
  have hterm : L (inverseScale L n) + 1 ≤ B := by
    change L (inverseScale L n) + 1 ≤
      ∑ δ ∈ Finset.range b, (L δ + 1)
    exact Finset.single_le_sum (s := Finset.range b)
      (f := fun δ => L δ + 1) (fun _ _ => Nat.zero_le _) hmember
  have hspec := inverseScale_spec hL n
  omega

/-- The corresponding upper generalized inverse also tends to infinity. -/
theorem tendsto_upperInverseScale_atTop {L : ℕ → ℕ}
    (hL : Tendsto L atTop atTop) :
    Tendsto (upperInverseScale L) atTop atTop := by
  rw [tendsto_atTop]
  intro b
  filter_upwards [tendsto_atTop.1 (tendsto_inverseScale_atTop hL) (b + 1)]
    with n hn
  have hmono := inverseScale_mono hL (Nat.le_succ n)
  have hmono' : inverseScale L n ≤ inverseScale L (n + 1) := by
    simpa [Nat.succ_eq_add_one] using hmono
  simp only [upperInverseScale]
  omega

/-- A superquadratic lower bound on the original scale gives the corresponding
subdiffusive bound on its generalized inverse.  This is the integer core of
the implication `x(n) / sqrt n → 0`: the factor four only comes from
`x(n) ≤ 2 * (x(n) - 1)`. -/
theorem eventually_mul_sq_inverseScale_le_four_mul
    {L : ℕ → ℕ} (hL : Tendsto L atTop atTop) (K : ℕ)
    (hquadratic : Filter.Eventually (fun δ => K * δ ^ 2 ≤ L δ) atTop) :
    Filter.Eventually (fun n => K * (inverseScale L n) ^ 2 ≤ 4 * n) atTop := by
  obtain ⟨D, hD⟩ := eventually_atTop.1 hquadratic
  filter_upwards [tendsto_atTop.1 (tendsto_inverseScale_atTop hL)
    (max (D + 1) 2)] with n hn
  let x := inverseScale L n
  let k := x - 1
  have hxD : D + 1 ≤ x := le_trans (le_max_left (D + 1) 2) hn
  have hx2 : 2 ≤ x := le_trans (le_max_right (D + 1) 2) hn
  have hkD : D ≤ k := by
    dsimp [k]
    omega
  have hK : K * k ^ 2 ≤ L k := hD k hkD
  have hpred : L k + 1 < n := by
    dsimp [k, x]
    apply scale_pred_inverseScale_add_one_lt
    exact lt_of_lt_of_le (by omega : 0 < max (D + 1) 2) hn
  have hxk : x ≤ 2 * k := by
    dsimp [k]
    omega
  calc
    K * x ^ 2 ≤ K * (2 * k) ^ 2 :=
      Nat.mul_le_mul_left K (Nat.pow_le_pow_left hxk 2)
    _ = 4 * (K * k ^ 2) := by ring
    _ ≤ 4 * L k := Nat.mul_le_mul_left 4 hK
    _ ≤ 4 * n := Nat.mul_le_mul_left 4
      (Nat.le_of_lt (lt_trans (Nat.lt_succ_self (L k)) hpred))

/-- Uniform form of the inverse subdiffusive estimate for a superquadratic
scale. -/
theorem eventually_mul_sq_inverseScale_le_four_mul_of_superquadratic
    {L : ℕ → ℕ} (hL : Tendsto L atTop atTop)
    (hquadratic : IsSuperquadraticScale L) (K : ℕ) :
    Filter.Eventually (fun n => K * (inverseScale L n) ^ 2 ≤ 4 * n) atTop :=
  eventually_mul_sq_inverseScale_le_four_mul hL K (hquadratic K)

/-- The squared generalized inverse is negligible compared with time. -/
theorem tendsto_sq_inverseScale_div_atTop_zero
    {L : ℕ → ℕ} (hL : Tendsto L atTop atTop)
    (hquadratic : IsSuperquadraticScale L) :
    Tendsto (fun n : ℕ =>
      ((inverseScale L n : ℝ) ^ 2) / (n : ℝ)) atTop (nhds 0) := by
  refine Metric.tendsto_atTop.2 ?_
  intro ε hε
  obtain ⟨K, hK⟩ := exists_nat_gt (4 / ε)
  have hKpos : 0 < (K : ℝ) := by
    exact lt_of_le_of_lt (div_nonneg (by norm_num) hε.le) hK
  have hfour : (4 : ℝ) / K < ε := by
    rw [div_lt_iff₀ hKpos]
    simpa [mul_comm] using (div_lt_iff₀ hε).mp hK
  obtain ⟨N, hN⟩ := eventually_atTop.1
    (eventually_mul_sq_inverseScale_le_four_mul_of_superquadratic
      hL hquadratic K)
  refine ⟨max N 1, fun n hn => ?_⟩
  have hnN : N ≤ n := le_trans (le_max_left N 1) hn
  have hnposNat : 0 < n := lt_of_lt_of_le Nat.zero_lt_one
    (le_trans (le_max_right N 1) hn)
  have hbound := hN n hnN
  have hboundReal :
      (K : ℝ) * (inverseScale L n : ℝ) ^ 2 ≤ 4 * (n : ℝ) := by
    exact_mod_cast hbound
  have hxbound :
      (inverseScale L n : ℝ) ^ 2 ≤ 4 * (n : ℝ) / K := by
    rw [le_div_iff₀ hKpos]
    simpa [mul_comm] using hboundReal
  have hnpos : 0 < (n : ℝ) := by exact_mod_cast hnposNat
  have hratio :
      (inverseScale L n : ℝ) ^ 2 / (n : ℝ) ≤ 4 / K := by
    rw [div_le_iff₀ hnpos]
    calc
      (inverseScale L n : ℝ) ^ 2 ≤ 4 * (n : ℝ) / K := hxbound
      _ = (4 / K) * n := by ring
  rw [Real.dist_eq, sub_zero, abs_of_nonneg
    (div_nonneg (sq_nonneg _) hnpos.le)]
  exact hratio.trans_lt hfour

end ProbabilityTheory.RandomWalk
