import Probability.Process.Stable.SmallDeviation.EscapeRate
import Probability.Process.Stable.SmallDeviation.EscapeRate.Corridor
import Probability.Process.Stable.SmallDeviation.EscapeRate.Endpoint
import Probability.Process.Stable.SmallDeviation.EscapeRate.Law

open MeasureTheory Filter
open scoped NNReal Topology

#check ProbabilityTheory.IsStableLevyProcess.exists_rationalRange_escape_rate
#check ProbabilityTheory.IsStableLevyProcess.exists_centeredCorridor_escape_rate
#check ProbabilityTheory.IsStableLevyProcess.exists_shiftedCorridor_escape_rate
#check ProbabilityTheory.IsStableLevyProcess.exists_shiftedEndpointCorridor_escape_rate
#check ProbabilityTheory.IsStableLevyProcess.tendsto_log_shiftedCorridor_div_log_range
#check ProbabilityTheory.IsStableLevyProcess.tendsto_log_shiftedEndpointCorridor_div_log_shiftedCorridor
#check ProbabilityTheory.IsStableLevyProcess.rationalRangeProbability_eq_of_same_law
#check ProbabilityTheory.IsStableLevyProcess.escapeRate_constant_eq_of_same_law

#print axioms ProbabilityTheory.IsStableLevyProcess.exists_rationalRange_escape_rate
#print axioms ProbabilityTheory.IsStableLevyProcess.exists_centeredCorridor_escape_rate
#print axioms ProbabilityTheory.IsStableLevyProcess.exists_shiftedCorridor_escape_rate
#print axioms ProbabilityTheory.IsStableLevyProcess.exists_shiftedEndpointCorridor_escape_rate
#print axioms ProbabilityTheory.IsStableLevyProcess.tendsto_log_shiftedCorridor_div_log_range
#print axioms ProbabilityTheory.IsStableLevyProcess.tendsto_log_shiftedEndpointCorridor_div_log_shiftedCorridor
#print axioms ProbabilityTheory.IsStableLevyProcess.rationalRangeProbability_eq_of_same_law
#print axioms ProbabilityTheory.IsStableLevyProcess.escapeRate_constant_eq_of_same_law
