import Probability.Process.RandomWalk.SmallDeviation.Mogulskii.PathClass.Rate.Approximation

#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.tendsto_log_m3_preimage_probability_ratio
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.M3.hAlpha_antitone_of_subset_of_probabilityRate
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.M3EnergyLimits.hAlpha_eq_of_approximation
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.tendsto_log_probability_ratio_of_M3Approximation
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.existsUnique_hAlpha_of_IsM
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.tendsto_log_probability_ratio_of_IsM
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.tendsto_log_probability_ratio_of_IsM_of_M2Rates
