import Probability.Process.Stable.SmallDeviation.ShiftedCorridor

#check ProbabilityTheory.IsStableLevyProcess.eventually_one_sub_le_log_corridor_ratio_of_cdf
#check ProbabilityTheory.IsStableLevyProcess.eventually_one_sub_le_log_corridor_ratio_of_measure_Iio_zero

#print axioms ProbabilityTheory.IsStableLevyProcess.eventually_one_sub_le_log_corridor_ratio_of_cdf
#print axioms ProbabilityTheory.IsStableLevyProcess.eventually_one_sub_le_log_corridor_ratio_of_measure_Iio_zero
