import Mathlib.MeasureTheory.Measure.GiryMonad
import Mathlib.MeasureTheory.Measure.Count
import Mathlib.MeasureTheory.Measure.Typeclasses.Finite
import Mathlib.Topology.MetricSpace.Bounded
import Mathlib.Topology.Order.Bornology

/-!
# Abstract point processes and offspring point processes

`PointProcess Ω E` is the abstract object: a measurable map from `Ω` to the
space of locally finite counting measures on a measurable topological space
`E`. The measurable space on `Measure E` is Mathlib's evaluation sigma-algebra
(the Giry-monad measurable space), so measurability is exactly the usual
point-process measurability generated by the evaluations `ν ↦ ν s`.

The thesis works on `E = ℝ` and needs finite mass on every left half-line.
That is the specialization `OffspringPointProcess Ω`, and it is the only layer
below which the order of `ℝ` enters the definition. Countable slot marks are a
later measurable representation used to attach independent copies to an
Ulam--Harris tree; the abstract point process does not depend on trees,
roots, or a selection rule.
-/

open MeasureTheory
open scoped ENNReal

namespace ThesisSpeed

/-- A measure takes values in `ℕ ∪ {∞}` on every measurable set. -/
def IsCountingMeasure {E : Type*} [MeasurableSpace E]
    (ν : Measure E) : Prop :=
  ∀ s : Set E, MeasurableSet s →
    ν s = ∞ ∨ ∃ n : ℕ, ν s = n

/-- The local finiteness relevant for ordering offspring from the left. -/
def IsLeftLocallyFinite (ν : Measure ℝ) : Prop :=
  ∀ R : ℝ, ν (Set.Iic R) ≠ ∞

/-- Left-local finiteness on `ℝ` implies the standard compact-finiteness
condition, because every compact subset of `ℝ` is bounded above. -/
theorem IsLeftLocallyFinite.isFiniteMeasureOnCompacts
    {ν : Measure ℝ} (hν : IsLeftLocallyFinite ν) :
    IsFiniteMeasureOnCompacts ν where
  lt_top_of_isCompact := by
    intro K hK
    obtain ⟨R, hR⟩ := hK.isBounded.bddAbove
    exact lt_of_le_of_lt (measure_mono fun _x hx => hR hx)
      (lt_top_iff_ne_top.mpr (hν R))

/-- An abstract point process: a measurable random locally finite counting
measure on `E`. The zero measure is allowed. -/
structure PointProcess (Ω E : Type*) [MeasurableSpace Ω] [MeasurableSpace E]
    [TopologicalSpace E] where
  toMeasure : Ω → Measure E
  measurable_toMeasure : Measurable toMeasure
  counting : ∀ ω, IsCountingMeasure (toMeasure ω)
  locallyFinite : ∀ ω, IsFiniteMeasureOnCompacts (toMeasure ω)

instance {Ω E : Type*} [MeasurableSpace Ω] [MeasurableSpace E]
    [TopologicalSpace E] :
    CoeFun (PointProcess Ω E) (fun _ => Ω → Measure E) :=
  ⟨PointProcess.toMeasure⟩

/-- The zero point process exists at the abstract level and represents the
samplewise absence of offspring. -/
def emptyPointProcess (Ω E : Type*) [MeasurableSpace Ω] [MeasurableSpace E]
    [TopologicalSpace E] : PointProcess Ω E where
  toMeasure := fun _ => 0
  measurable_toMeasure := measurable_const
  counting := by
    intro ω s hs
    right
    exact ⟨0, by simp⟩
  locallyFinite := by
    intro ω
    constructor
    intro K hK
    simp

/-- The thesis-specific offspring point process: an abstract point process on
`ℝ`, with the extra condition that every left half-line has finite mass. -/
structure OffspringPointProcess (Ω : Type*) [MeasurableSpace Ω] where
  toMeasure : Ω → Measure ℝ
  measurable_toMeasure : Measurable toMeasure
  counting : ∀ ω, IsCountingMeasure (toMeasure ω)
  leftLocallyFinite : ∀ ω, IsLeftLocallyFinite (toMeasure ω)

instance {Ω : Type*} [MeasurableSpace Ω] :
    CoeFun (OffspringPointProcess Ω) (fun _ => Ω → Measure ℝ) :=
  ⟨OffspringPointProcess.toMeasure⟩

/-- Forget the left-half-line condition, retaining the abstract point
process structure. -/
noncomputable def OffspringPointProcess.toPointProcess
    {Ω : Type*} [MeasurableSpace Ω] (Ξ : OffspringPointProcess Ω) :
    PointProcess Ω ℝ where
  toMeasure := Ξ.toMeasure
  measurable_toMeasure := Ξ.measurable_toMeasure
  counting := Ξ.counting
  locallyFinite := fun ω =>
    (Ξ.leftLocallyFinite ω).isFiniteMeasureOnCompacts

/-- The empty offspring point process is valid at the foundational level. -/
def emptyOffspringPointProcess (Ω : Type*) [MeasurableSpace Ω] :
    OffspringPointProcess Ω where
  toMeasure := fun _ => 0
  measurable_toMeasure := measurable_const
  counting := by
    intro ω s hs
    right
    exact ⟨0, by simp⟩
  leftLocallyFinite := by simp [IsLeftLocallyFinite]

end ThesisSpeed
