import Probability.BranchingRandomWalk.Genealogy.Exploration.RootIndexed.SelectedSubtrees.FixedFamily

/-!
# Domain flows restricted to a set of initial roots

A concurrent restart construction may inspect complete trial trees while
keeping other initial roots in reserve.  This file builds the corresponding
domain flow on an arbitrary root set and proves independence from every
disjoint reserve-root family.  Neither root set is assumed finite or
countable.
-/

open MeasureTheory ProbabilityTheory

namespace ProbabilityTheory.BranchingRandomWalk

open Combinatorics.UlamHarris Combinatorics.Branching MeasureTheory

namespace RootIndexed

/-- Sigma-algebra generated by a specified set of root/address coordinates. -/
@[instance_reducible] def stepSpace
    {Root α X : Type*} [MeasurableSpace X]
    (s : Set (Root × TreeNode α)) :
    MeasurableSpace (StepField Root α X) :=
  ⨆ p ∈ s, stepCoordinateSpace p

/-- All coordinates whose initial-root label belongs to `roots`. -/
def rootAddresses {Root α : Type*} (roots : Set Root) :
    Set (Root × TreeNode α) :=
  {p | p.1 ∈ roots}

/-- Coordinates below generation `n` and over the selected initial roots. -/
def rootPastAddresses {Root α : Type*} (roots : Set Root) (n : ℕ) :
    Set (Root × TreeNode α) :=
  {p | p.1 ∈ roots ∧ p.2.length < n}

/-- The generation domain flow restricted to a set of initial roots. -/
def rootFiltration
    {Root α X : Type*} [MeasurableSpace X] (roots : Set Root) :
    Filtration ℕ
      (inferInstance : MeasurableSpace (StepField Root α X)) where
  seq n := stepSpace (rootPastAddresses roots n)
  mono' := by
    intro n m hnm
    apply iSup_le
    intro p
    apply iSup_le
    intro hp
    exact le_iSup_of_le p (le_iSup_of_le
      ⟨hp.1, lt_of_lt_of_le hp.2 hnm⟩ le_rfl)
  le' := by
    intro n
    apply iSup_le
    intro p
    apply iSup_le
    intro hp
    have hm : Measurable
        (fun ω : StepField Root α X => ω p.1 p.2) :=
      (measurable_pi_apply p.2).comp (measurable_pi_apply p.1)
    exact hm.comap_le

theorem rootFiltration_le_stepFiltration
    {Root α X : Type*} [MeasurableSpace X]
    (roots : Set Root) (n : ℕ) :
    rootFiltration (α := α) (X := X) roots n ≤
      stepFiltration (Root := Root) (α := α) (X := X) n := by
  apply iSup_le
  intro p
  apply iSup_le
  intro hp
  exact (step_measurable (X := X) p.1 p.2 hp.2).comap_le

theorem stepSpace_independent
    {Root α X : Type*} [MeasurableSpace X]
    (μ : Measure (Step α X)) [IsProbabilityMeasure μ]
    (s t : Set (Root × TreeNode α)) (hdisjoint : Disjoint s t) :
    Indep (stepSpace (X := X) s) (stepSpace (X := X) t)
      (stepFieldLaw (Root := Root) μ) := by
  have hcoord : iIndep (fun p : Root × TreeNode α =>
      stepCoordinateSpace (X := X) p)
      (stepFieldLaw (Root := Root) μ) := by
    have h : iIndepFun
        (fun (p : Root × TreeNode α) (ω : StepField Root α X) =>
          ω p.1 p.2) (stepFieldLaw (Root := Root) μ) := by
      unfold stepFieldLaw _root_.ProbabilityTheory.BranchingRandomWalk.stepFieldLaw
      simpa using (iIndepFun_uncurry_infinitePi'
        (μ := fun (_ : Root) (_ : TreeNode α) => μ)
        (X := fun (_ : Root) (_ : TreeNode α) => id)
        (fun _ _ => measurable_id))
    exact h.iIndep
  have hle : ∀ p : Root × TreeNode α,
      stepCoordinateSpace (X := X) p ≤
        (inferInstance : MeasurableSpace (StepField Root α X)) := by
    intro p
    exact ((measurable_pi_apply p.2).comp
      (measurable_pi_apply p.1 : Measurable
        (fun ω : StepField Root α X => ω p.1))).comap_le
  exact indep_iSup_of_disjoint hle hcoord hdisjoint

theorem rootAddresses_disjoint
    {Root α : Type*} {roots reserves : Set Root}
    (hdisjoint : Disjoint roots reserves) :
    Disjoint (rootAddresses (α := α) roots)
      (rootAddresses (α := α) reserves) := by
  apply Set.disjoint_left.mpr
  intro p hp hq
  exact Set.disjoint_left.mp hdisjoint hp hq

/-- All information read from one set of initial roots is independent of all
information stored below a disjoint set of reserve roots. -/
theorem rootSpace_independent
    {Root α X : Type*} [MeasurableSpace X]
    (μ : Measure (Step α X)) [IsProbabilityMeasure μ]
    (roots reserves : Set Root) (hdisjoint : Disjoint roots reserves) :
    Indep (stepSpace (X := X) (rootAddresses (α := α) roots))
      (stepSpace (X := X) (rootAddresses (α := α) reserves))
      (stepFieldLaw (Root := Root) μ) :=
  stepSpace_independent μ _ _ (rootAddresses_disjoint hdisjoint)

/-- Every finite-time trial-root domain is independent of the complete
reserve-root forest. -/
theorem rootFiltration_reserve_independent
    {Root α X : Type*} [MeasurableSpace X]
    (μ : Measure (Step α X)) [IsProbabilityMeasure μ]
    (roots reserves : Set Root) (hdisjoint : Disjoint roots reserves)
    (n : ℕ) :
    Indep (rootFiltration (α := α) (X := X) roots n)
      (stepSpace (X := X) (rootAddresses (α := α) reserves))
      (stepFieldLaw (Root := Root) μ) := by
  apply indep_of_indep_of_le_left
    (rootSpace_independent μ roots reserves hdisjoint)
  apply iSup_le
  intro p
  apply iSup_le
  intro hp
  exact le_iSup_of_le p (le_iSup_of_le hp.1 le_rfl)

/-- The complete fields carried by a fixed reserve family are measurable with
respect to the reserve-root coordinate space. -/
theorem reserveField_measurable
    {Root κ α X : Type*} [MeasurableSpace X]
    (reserve : κ → Root) :
    Measurable[stepSpace (X := X)
      (rootAddresses (α := α) (Set.range reserve))]
      (fun ω : StepField Root α X => fun i => ω (reserve i)) := by
  apply (@measurable_pi_iff (StepField Root α X) κ
    (fun _ => TreeNode α → Step α X)
    (stepSpace (X := X) (rootAddresses (α := α) (Set.range reserve)))
    (fun _ => inferInstance) _).2
  intro i
  apply (@measurable_pi_iff (StepField Root α X) (TreeNode α)
    (fun _ => Step α X)
    (stepSpace (X := X) (rootAddresses (α := α) (Set.range reserve)))
    (fun _ => inferInstance) _).2
  intro u
  have hp : (reserve i, u) ∈
      rootAddresses (α := α) (Set.range reserve) :=
    ⟨i, rfl⟩
  have hm : Measurable[stepCoordinateSpace (X := X) (reserve i, u)]
      (fun ω : StepField Root α X => ω (reserve i) u) :=
    Measurable.of_comap_le le_rfl
  exact hm.mono (le_iSup_of_le (reserve i, u)
    (le_iSup_of_le hp le_rfl)) le_rfl

/-- A fixed family of reserve trees is independent of every finite-time event
that only inspects a disjoint set of trial roots. -/
theorem reserveField_independent
    {Root κ α X : Type*} [MeasurableSpace X]
    (μ : Measure (Step α X)) [IsProbabilityMeasure μ]
    (trials : Set Root) (reserve : κ → Root)
    (hdisjoint : Disjoint trials (Set.range reserve)) (n : ℕ) :
    Indep (rootFiltration (α := α) (X := X) trials n)
      (MeasurableSpace.comap
        (fun ω : StepField Root α X => fun i => ω (reserve i)) inferInstance)
      (stepFieldLaw (Root := Root) μ) :=
  indep_of_indep_of_le_right
    (rootFiltration_reserve_independent μ trials (Set.range reserve)
      hdisjoint n)
    (reserveField_measurable reserve).comap_le

end RootIndexed

end ProbabilityTheory.BranchingRandomWalk
