module

public import Probability.Process.Path.Skorokhod.Corridor.UniformBlocks.Prefix

/-!
# Tube events for uniform block partitions

This module packages the measurable block and prefix tube events generated by
the deterministic uniform-block path construction.  It contains no process
law or independence assumption; those hypotheses enter in the Stable and
random-walk adapters.
-/

@[expose] public section

namespace ProbabilityTheory

open MeasureTheory
open scoped NNReal

/-- The tube event for one translated block of a real-time process. -/
def rationalUniformBlockTubeEvent {Ω : Type*} (X : ℝ≥0 → Ω → ℝ)
    (width : ℝ) {blocks : ℕ} (hblocks : 0 < blocks) (j : Fin blocks) : Set Ω :=
  (fun ω : Ω => fun q : ↑RationalGrid.RationalUnitInterval =>
    rationalUniformBlockProcessFromTime X hblocks j q ω) ⁻¹'
    Skorokhod.rationalCoordinateOscillationTube width

/-- The event that the first `m` translated block paths lie in the tube. -/
def rationalUniformPrefixTubeEvent {Ω : Type*} (X : ℝ≥0 → Ω → ℝ)
    (width : ℝ) {blocks : ℕ} (hblocks : 0 < blocks) (m : ℕ) : Set Ω :=
  ⋂ k : Fin blocks,
    if k.val < m then rationalUniformBlockTubeEvent X width hblocks k else Set.univ

/-- Adding one block to a prefix event is intersection with the new block
event. -/
theorem rationalUniformPrefixTubeEvent_succ {Ω : Type*} (X : ℝ≥0 → Ω → ℝ)
    (width : ℝ) {blocks : ℕ} (hblocks : 0 < blocks)
    (m : ℕ) (hm : m < blocks) :
    rationalUniformPrefixTubeEvent X width hblocks (m + 1) =
      rationalUniformPrefixTubeEvent X width hblocks m ∩
        rationalUniformBlockTubeEvent X width hblocks ⟨m, hm⟩ := by
  ext ω
  simp only [rationalUniformPrefixTubeEvent, Set.mem_iInter, Set.mem_inter_iff]
  constructor
  · intro h
    constructor
    · intro k
      by_cases hk : k.val < m
      · have hk' : k.val < m + 1 := by omega
        simpa [hk, hk'] using h k
      · simp [hk]
    · have h' := h ⟨m, hm⟩
      simpa using h'
  · rintro ⟨hp, hmEvent⟩ k
    by_cases hk : k.val < m
    · simpa [hk, Nat.lt_succ_of_lt hk] using hp k
    · by_cases hkm : k.val = m
      · have heq : k = ⟨m, hm⟩ := Fin.ext hkm
        simpa [hkm, heq] using hmEvent
      · have hnot : ¬ k.val < m + 1 := by omega
        simp [hnot]

/-- The empty prefix event is the whole sample space. -/
@[simp] theorem rationalUniformPrefixTubeEvent_zero {Ω : Type*}
    (X : ℝ≥0 → Ω → ℝ) (width : ℝ) {blocks : ℕ}
    (hblocks : 0 < blocks) :
    rationalUniformPrefixTubeEvent X width hblocks 0 = Set.univ := by
  simp [rationalUniformPrefixTubeEvent]

/-- The first `m` block events are the pullback of the deterministic prefix
tube set through the stopped prefix path. -/
theorem rationalUniformPrefixTubeSet_preimage
    {Ω : Type*} (X : ℝ≥0 → Ω → ℝ) (width : ℝ)
    {blocks : ℕ} (hblocks : 0 < blocks) (m : ℕ) :
    rationalUniformPrefixPath X blocks m hblocks ⁻¹'
      rationalUniformPrefixTubeSet width hblocks m =
      ⋂ k : Fin blocks,
        if k.val < m then
          ((fun ω q => rationalUniformBlockProcessFromTime X hblocks k q ω) ⁻¹'
            Skorokhod.rationalCoordinateOscillationTube width)
        else Set.univ := by
  ext ω
  simp only [Set.mem_preimage, rationalUniformPrefixTubeSet, Set.mem_iInter]
  apply forall_congr'
  intro k
  by_cases hk : k.val < m
  · simp only [hk, ↓reduceIte, rationalTubeBlockEvent, Set.mem_preimage]
    rw [rationalUniformPrefixPath_blockIncrement_eq X hblocks m k hk ω]
  · simp [hk]

/-- The prefix tube event is the pullback of the deterministic prefix tube set. -/
theorem rationalUniformPrefixTubeEvent_eq_preimage
    {Ω : Type*} (X : ℝ≥0 → Ω → ℝ) (width : ℝ)
    {blocks : ℕ} (hblocks : 0 < blocks) (m : ℕ) :
    rationalUniformPrefixTubeEvent X width hblocks m =
      rationalUniformPrefixPath X blocks m hblocks ⁻¹'
        rationalUniformPrefixTubeSet width hblocks m := by
  rw [rationalUniformPrefixTubeSet_preimage X width hblocks m]
  rfl

/-- The zero-block tube event is the unshifted short-horizon range tube. -/
theorem rationalUniformBlockTubeEvent_zero_eq_horizon
    {Ω : Type*} (X : ℝ≥0 → Ω → ℝ) (width : ℝ)
    {blocks : ℕ} (hblocks : 0 < blocks) :
    rationalUniformBlockTubeEvent X width hblocks ⟨0, hblocks⟩ =
      rationalHorizonTubeEvent X (rationalUniformBlockBoundary blocks 1 hblocks)
        width := by
  ext ω
  change (fun q => X (rationalUniformBlockAbsoluteTime hblocks ⟨0, hblocks⟩ q) ω -
      X (rationalUniformBlockAbsoluteTime hblocks ⟨0, hblocks⟩ ⊥) ω) ∈
      Skorokhod.rationalCoordinateOscillationTube width ↔
    (fun q => X (rationalUniformBlockBoundary blocks 1 hblocks * rationalUnitTime q) ω) ∈
      Skorokhod.rationalCoordinateOscillationTube width
  simp only [rationalUniformBlockAbsoluteTime_zero_eq_horizon hblocks]
  simp only [rationalUnitTime_bot]
  simp
  change (fun q => X (rationalUniformBlockBoundary blocks 1 hblocks *
      rationalUnitTime q) ω - X 0 ω) ∈
      Skorokhod.rationalCoordinateOscillationTube width ↔
    (fun q => X (rationalUniformBlockBoundary blocks 1 hblocks *
      rationalUnitTime q) ω) ∈
      Skorokhod.rationalCoordinateOscillationTube width
  exact Skorokhod.mem_rationalCoordinateOscillationTube_sub_const_iff
    width (X 0 ω) _

end ProbabilityTheory

end
