module

public import Combinatorics.BranchingWalk.Basic.Displace
public import Combinatorics.BranchingWalk.Step.Map
public import Combinatorics.BranchingWalk.Basic.SiblingClosable
public import Combinatorics.BranchingWalk.Step.Relation
public import Combinatorics.UlamHarris.MarkedTree.SiblingOrder
public import Mathlib.Tactic.Abel

/-!
# Reading a step field off a marked tree

`markedTreeOfStep` derives a marked tree from a step field: the realized addresses
carry their displacements. `stepOfMarkedTree` reads a step field back off a
marked tree: the slot `i` at the address `u` is survive exactly when `u ++ [i]`
is a realized node, and its value is the displacement of that node relative to
its parent, `mark (u ++ [i]) - mark u`. So the two readings are inverse on the
realized part of a field, and the round trips proved here turn this into
the equivalence between step fields and marked trees whose root mark vanishes.

Reading a field off a tree needs the relative displacement, so this file works
over an additive group. Order compatibility is separated into
`MarkedTree/Order.lean`.
This file is the per-root core: the walk-level object is
`RootIndexed.BranchingWalk.positionedMarkedTree` in
`MarkedTree/OfBranchingWalk.lean`, which is the accumulated-position
specialization of the generic node-marking construction and bridges back to
`markedTreeOfStep` here at a single initial ancestor.
-/

@[expose] public section

namespace Combinatorics

namespace Branching

open Combinatorics.UlamHarris

variable {α X : Type*}

section AddCommGroup

variable [LT α] [AddCommGroup X]

/-- The marked tree generated by a step field: the realized addresses are the
ones whose root path survives, and each of them carries its displacement
`displace step [] u`. The tree is sibling closed exactly because the field is
(`Step.IsSiblingClosed`), and it is parent closed because a prefix of a realized
path is realized. -/
noncomputable def markedTreeOfStep (step : StepField α X)
    (hpresence : IsSiblingClosed step) : MarkedTree α X where
  tree :=
    { carrier := {u | surviveAlong step [] u}
      root_mem := surviveAlong_nil step []
      parent_closed := by
        intro u v h
        exact surviveAlong_prefix step u v h
      sibling_closed := by
        intro u i j hmem hij
        have hmem' : surviveAlong step [] (u ++ [j]) := hmem
        change surviveAlong step [] (u ++ [i])
        rw [surviveAlong_root_append_singleton_iff] at hmem'
        rw [surviveAlong_root_append_singleton_iff]
        exact ⟨hmem'.1, (survive_iff_ne_none _ _).2 fun hnone =>
          ((survive_iff_ne_none _ _).1 hmem'.2) ((hpresence u) i j hij hnone)⟩ }
  mark u _ := displace step [] u

/-- The step field read off a marked tree: at the address `u` the slot `i` is
survive exactly when `u ++ [i]` is realized, carrying the displacement of
`u ++ [i]` relative to `u`. -/
noncomputable def stepOfMarkedTree (M : MarkedTree α X) : StepField α X := by
  classical
  exact fun u i =>
    if h : u ++ [i] ∈ M.tree.carrier then
      some (M.mark (u ++ [i]) h - M.mark u (M.tree.parent_closed h))
    else none

@[simp] theorem stepOfMarkedTree_apply_of_mem {M : MarkedTree α X}
    {u : TreeNode α} {i : α} (h : u ++ [i] ∈ M.tree.carrier) :
    stepOfMarkedTree M u i =
      some (M.mark (u ++ [i]) h - M.mark u (M.tree.parent_closed h)) := by
  classical
  simp [stepOfMarkedTree, h]

@[simp] theorem stepOfMarkedTree_apply_of_notMem {M : MarkedTree α X}
    {u : TreeNode α} {i : α} (h : u ++ [i] ∉ M.tree.carrier) :
    stepOfMarkedTree M u i = none := by
  classical
  simp [stepOfMarkedTree, h]

/-- A slot of the field read off a marked tree is survive exactly when the
corresponding child is a realized node. -/
theorem survive_stepOfMarkedTree_iff {M : MarkedTree α X} {u : TreeNode α}
    {i : α} :
    survive (stepOfMarkedTree M u) i ↔ u ++ [i] ∈ M.tree.carrier := by
  classical
  constructor
  · rintro ⟨x, hx⟩
    by_contra h
    rw [stepOfMarkedTree_apply_of_notMem (M := M) h] at hx
    exact absurd hx (by simp)
  · intro h
    exact ⟨_, stepOfMarkedTree_apply_of_mem (M := M) h⟩

/-- The realized nodes of the field read off a marked tree are exactly the
realized nodes of that tree. -/
theorem surviveAlong_root_stepOfMarkedTree_iff {M : MarkedTree α X} (u : TreeNode α) :
    surviveAlong (stepOfMarkedTree M) [] u ↔ u ∈ M.tree.carrier := by
  induction u using List.reverseRecOn with
  | nil => exact ⟨fun _ => M.tree.root_mem, fun _ => surviveAlong_nil _ _⟩
  | append_singleton p i ih =>
      rw [surviveAlong_root_append_singleton_iff, ih, survive_stepOfMarkedTree_iff]
      exact ⟨fun h => h.2, fun h => ⟨M.tree.parent_closed h, h⟩⟩

/-- The field read off a marked tree lists the survive slots of every address
from the left, because the tree of a marked tree is sibling closed. -/
theorem Step.IsSiblingClosed_stepOfMarkedTree {M : MarkedTree α X} (u : TreeNode α) :
    Step.IsSiblingClosed (stepOfMarkedTree M u) := by
  intro i j hij hj
  by_contra h
  have hp : survive (stepOfMarkedTree M u) j := (survive_iff_ne_none _ _).2 h
  have hmem : u ++ [j] ∈ M.tree.carrier := (survive_stepOfMarkedTree_iff).1 hp
  have himem : u ++ [i] ∈ M.tree.carrier := M.tree.sibling_closed hmem hij
  exact ((survive_iff_ne_none _ _).1 ((survive_stepOfMarkedTree_iff).2 himem)) hj

/-- The zero-defaulted slot of the field read off a marked tree is the
displacement of the child relative to its parent. -/
theorem value'_stepOfMarkedTree_of_mem {M : MarkedTree α X} {u : TreeNode α}
    {i : α} (h : u ++ [i] ∈ M.tree.carrier) :
    value' (stepOfMarkedTree M u) i =
      M.mark (u ++ [i]) h - M.mark u (M.tree.parent_closed h) :=
  value'_some _ _ _ (stepOfMarkedTree_apply_of_mem (M := M) h)

/-- A slot of the field read off a marked tree whose child is not realized is
absent, so the zero-defaulted reading is zero. -/
theorem value'_stepOfMarkedTree_of_notMem {M : MarkedTree α X} {u : TreeNode α}
    {i : α} (h : u ++ [i] ∉ M.tree.carrier) :
    value' (stepOfMarkedTree M u) i = 0 :=
  value'_none _ _ (stepOfMarkedTree_apply_of_notMem (M := M) h)

/-- The displacement of a realized node in the field read off a marked tree is
that mark, up to the root mark: the relative displacements along the root path
telescope. -/
theorem displace_stepOfMarkedTree {M : MarkedTree α X} :
    ∀ (u : TreeNode α) (hu : u ∈ M.tree.carrier),
      displace (stepOfMarkedTree M) [] u = M.mark u hu - M.rootMark := by
  intro u
  induction u using List.reverseRecOn with
  | nil =>
      intro hu
      have h : M.mark [] hu = M.rootMark := by
        rw [MarkedTree.rootMark_eq, Subsingleton.elim hu M.tree.root_mem]
      rw [displace_nil, h, sub_self]
  | append_singleton p i ih =>
      intro hmem
      have hpar : p ∈ M.tree.carrier := M.tree.parent_closed hmem
      rw [displace_append_singleton, ih hpar,
        value'_stepOfMarkedTree_of_mem (M := M) hmem]
      abel

/-- Reading a presence-closed step field off its own marked tree returns the
field on every realized address. -/
theorem stepOfMarkedTree_markedTreeOfStep_of_realized (step : StepField α X)
    (hpresence : IsSiblingClosed step) {u : TreeNode α}
    (hu : surviveAlong step [] u) :
    stepOfMarkedTree (markedTreeOfStep step hpresence) u = step u := by
  funext i
  by_cases hmem : u ++ [i] ∈ (markedTreeOfStep step hpresence).tree.carrier
  · rw [stepOfMarkedTree_apply_of_mem (M := markedTreeOfStep step hpresence) hmem]
    have hreal : surviveAlong step [] (u ++ [i]) := hmem
    have hp : survive (step u) i :=
      ((surviveAlong_root_append_singleton_iff step u i).1 hreal).2
    obtain ⟨x, hx⟩ := hp
    rw [hx]
    congr 1
    show displace step [] (u ++ [i]) - displace step [] u = x
    rw [displace_append_singleton, value'_some (step u) i x hx]
    exact add_sub_cancel_left _ _
  · rw [stepOfMarkedTree_apply_of_notMem (M := markedTreeOfStep step hpresence) hmem]
    have hnot : ¬ survive (step u) i := fun hp =>
      hmem ((surviveAlong_root_append_singleton_iff step u i).2 ⟨hu, hp⟩)
    have hnone : step u i = none := by
      by_contra h
      exact hnot ((survive_iff_ne_none _ _).2 h)
    rw [hnone]

/-- A step field read off a marked tree is sibling closed: the condition is per step, so the
field-level form is the pointwise one. -/
theorem IsSiblingClosed_stepOfMarkedTree {M : MarkedTree α X} :
    IsSiblingClosed (stepOfMarkedTree M) :=
  fun u => Step.IsSiblingClosed_stepOfMarkedTree u

/-- Marking the field read off a marked tree returns that tree, as soon as the
root mark vanishes: the relative displacements along a root path telescope back
to the marks. -/
theorem markedTreeOfStep_stepOfMarkedTree (M : MarkedTree α X) (hroot : M.rootMark = 0) :
    markedTreeOfStep (stepOfMarkedTree M) IsSiblingClosed_stepOfMarkedTree = M := by
  have htree : (markedTreeOfStep (stepOfMarkedTree M)
      IsSiblingClosed_stepOfMarkedTree).tree = M.tree := by
    refine Tree.ext ?_
    ext u
    exact surviveAlong_root_stepOfMarkedTree_iff u
  refine MarkedTree.ext htree ?_
  intro u hu
  show displace (stepOfMarkedTree M) [] u = M.mark u (htree ▸ hu)
  rw [displace_stepOfMarkedTree (M := M) u (htree ▸ hu), hroot, sub_zero]

/-- The marked tree of a sibling closable step field: relabel every step by the witness of its own
closability and read the tree off the relabeled field. Nothing is handed in beyond the closability —
the relabeling and the closure of the relabeled steps are the witnesses it carries. -/
noncomputable def StepField.markedTreeOfClosable (β : StepField α X)
    (h : StepField.IsSiblingClosable β) : MarkedTree α X :=
  markedTreeOfStep (fun u i => β u (Classical.choose (h.pointwise u).exists_relabel i))
    fun u => (Classical.choose_spec (h.pointwise u).exists_relabel).2

/-- On a sibling closable slot type the marked tree of a step field is had with nothing handed in: the
field is closable by instance search. -/
noncomputable def StepField.markedTreeOfClosable'
    [Combinatorics.Branching.IsSiblingClosable α] (β : StepField α X) :
    MarkedTree α X :=
  β.markedTreeOfClosable inferInstance

end AddCommGroup

section MappedPosition

variable [LT α]

/-- Relabel a sibling-closable mark field and accumulate its marks only after
mapping them into an independent additive position space. -/
noncomputable def StepField.positionedMarkedTreeOfClosable
    {Mark Position : Type*} [AddCommGroup Position]
    (β : StepField α Mark) (d : Mark → Position)
    (h : StepField.IsSiblingClosable β) : MarkedTree α Position :=
  let relabeled : StepField α Mark :=
    fun u i => β u (Classical.choose (h.pointwise u).exists_relabel i)
  markedTreeOfStep (relabeled.map d) (fun u => by
    intro i j hij hi
    have hi' : relabeled u i = none := by
      simpa [StepField.map, Step.map] using hi
    have hj' :=
      (Classical.choose_spec (h.pointwise u).exists_relabel).2 i j hij hi'
    simpa [StepField.map, Step.map] using hj')

/-- Instance-search form of `positionedMarkedTreeOfClosable`. -/
noncomputable def StepField.positionedMarkedTreeOfClosable'
    {Mark Position : Type*} [AddCommGroup Position]
    [Combinatorics.Branching.IsSiblingClosable α]
    (β : StepField α Mark) (d : Mark → Position) : MarkedTree α Position :=
  β.positionedMarkedTreeOfClosable d inferInstance

end MappedPosition


end Branching

end Combinatorics
