import Probability.Process.RandomWalk.SmallDeviation.Mogulskii.Discrete.Horizontal

#check ProbabilityTheory.RandomWalk.iidSequenceLaw_measure_forall_consecutiveBlockEvent
#check ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.measurableSet_blockOscillationLTEvent
#check ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.iidSequenceLaw_measure_forall_blockOscillationLT
#check ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.openHorizontalTubeProbability_le_pow_blockOscillationLT_of_blockCover
#check ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.openHorizontalTubeProbability_le_pow_blockOscillationLT_source

#print axioms ProbabilityTheory.RandomWalk.iidSequenceLaw_measure_forall_consecutiveBlockEvent
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.iidSequenceLaw_measure_forall_blockOscillationLT
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.openHorizontalTubeProbability_le_pow_blockOscillationLT_source
