import Probability.Process.Stable.PathLaw.LinearTube
import Probability.Process.RandomWalk.SmallDeviation.Entrance.Exchangeability
import Probability.Process.RandomWalk.SmallDeviation.Entrance.FunctionalLimit
import Probability.Process.RandomWalk.SmallDeviation.Entrance.LinearTubeRotation
import Probability.Process.RandomWalk.SmallDeviation.Entrance.CyclicPath
import Probability.Process.RandomWalk.SmallDeviation.Entrance.NormalDomain

/-!
# Axiom audit for the E₀ linear-tube inputs

This test exposes the transitive axioms of the stable path-law tube-positivity input
and the deterministic cyclic-rotation estimate.
-/

#print axioms ProbabilityTheory.IsStableClockProcessLaw.measure_linearPathBall_pos
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.exists_cyclicPartialSum_mem_Icc_of_linearTube
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.exists_cyclicPartialSum_mem_Icc_of_negativeLinearTube
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.measure_le_card_smul_of_finiteRotationCover
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.TendstoInDistribution.measure_openEvent_le_liminf
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.eventually_measure_normalizedStep_linearBall_pos
#print axioms ProbabilityTheory.iidSequenceLaw_map_finPrefix
#print axioms ProbabilityTheory.measure_pi_preimage_eq_of_reindex
#print axioms ProbabilityTheory.measure_pi_event_le_card_smul_of_reindexCover
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.cyclicPartialSum_removeLinearDrift
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.offsetCorridorPath_removeLinearDrift_iff_moving
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.finiteNormalizedStepPath_apply_grid
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.iidSequenceLaw_measure_linearPathBall_eq_pi
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.finiteLinearBall_subset_cyclicOffsetCover_lowerEdge
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.measure_pi_offsetCorridor_ge_div_of_linearTube
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.cyclicCoordinateReindex_isCyclicPartialSumReindex
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.finiteLinearBall_subset_cyclicOffsetCover_lowerEdge_modular
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.measure_pi_offsetCorridor_ge_div_of_linearTube_modular
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.exists_offsetCorridorPath_of_linearTube_allOffsets
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.eventually_measure_normalizedStep_linearBall_pos_on_Icc_of_centeredSecondMoment
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.finiteDriftRemovedOffsetCorridorEvent_iff_finiteMovingEntranceEvent
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.measure_pi_finiteMovingEntranceEvent_ge_div_of_uniformLinearBall
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.exists_eventually_measure_pi_finiteMovingEntranceEvent_ge_div_of_centeredSecondMoment
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Entrance.exists_eventually_iidSequenceLaw_finiteMovingEntranceEvent_ge_div_of_centeredSecondMoment
