import Probability.Process.Path.PathClass.StepCorridor.Probability.Rate.Approximation
import Probability.Process.Path.PathClass.StepCorridor.Probability.Rate.StableConstantCorridor

open ProbabilityTheory.Process.Path.PathClass.StepCorridor.Probability

#print axioms ProbabilityTheory.Process.Path.PathClass.StepCorridor.Probability.tendsto_log_finiteCorridorUnion_preimage_probability_ratio
#print axioms ProbabilityTheory.Process.Path.PathClass.StepCorridor.Probability.tendsto_log_finiteCorridorUnion_preimage_probability_ratio_of_nullMeasurable
#print axioms ProbabilityTheory.Process.Path.PathClass.StepCorridor.Probability.tendsto_log_finiteCorridorUnion_preimage_probability_ratio_of_aemeasurable_paths
#print axioms ProbabilityTheory.Process.Path.PathClass.StepCorridor.Probability.FiniteCorridorUnion.realEnergy_antitone_of_subset_of_probabilityRate
#print axioms ProbabilityTheory.Process.Path.PathClass.StepCorridor.Probability.FiniteCorridorUnionEnergyLimits.commonEnergy_eq_of_approximation
#print axioms ProbabilityTheory.Process.Path.PathClass.StepCorridor.Probability.tendsto_log_probability_ratio_of_FiniteCorridorUnionApproximation
#print axioms ProbabilityTheory.Process.Path.PathClass.StepCorridor.Probability.existsUnique_commonEnergy_of_hasVanishingEnergyGapApproximation
#print axioms ProbabilityTheory.Process.Path.PathClass.StepCorridor.Probability.tendsto_log_probability_ratio_of_hasVanishingEnergyGapApproximation
#print axioms ProbabilityTheory.Process.Path.PathClass.StepCorridor.Probability.tendsto_log_probability_ratio_of_hasVanishingEnergyGapApproximation_of_stepCorridorRates
#print axioms ProbabilityTheory.Process.Path.PathClass.StepCorridor.Probability.exists_constantCorridor_rate
