import Probability.Process.SmallDeviation.Mogulskii.PathClass.Rate.Approximation

#print axioms ProbabilityTheory.Process.SmallDeviation.Mogulskii.tendsto_log_m3_preimage_probability_ratio
#print axioms ProbabilityTheory.Process.SmallDeviation.Mogulskii.M3.hAlpha_antitone_of_subset_of_probabilityRate
#print axioms ProbabilityTheory.Process.SmallDeviation.Mogulskii.M3EnergyLimits.hAlpha_eq_of_approximation
#print axioms ProbabilityTheory.Process.SmallDeviation.Mogulskii.tendsto_log_probability_ratio_of_M3Approximation
#print axioms ProbabilityTheory.Process.SmallDeviation.Mogulskii.existsUnique_hAlpha_of_IsM
#print axioms ProbabilityTheory.Process.SmallDeviation.Mogulskii.tendsto_log_probability_ratio_of_IsM
#print axioms ProbabilityTheory.Process.SmallDeviation.Mogulskii.tendsto_log_probability_ratio_of_IsM_of_M2Rates
