import Probability.Process.Path.Cadlag.TerminalLeft
import Probability.Process.RandomWalk.SmallDeviation.Mogulskii.SourcePath
import Probability.Process.Stable.SmallDeviation.Mogulskii.PathClass.Rate
import Probability.Process.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.PathClassInnerOuter
import Probability.Process.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.SourcePathClassRate
import Probability.Process.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.SourcePathClassRegimes
import Probability.Process.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.SourcePathClassInnerOuter
import Probability.Process.RandomWalk.SmallDeviation.Mogulskii.Gaussian.EscapeConstant
import Probability.Process.RandomWalk.SmallDeviation.Mogulskii.Gaussian.SourcePathClass
import Probability.Process.Stable.PathLaw.UnitInterval

open scoped NNReal

#check ProbabilityTheory.Process.Path.Cadlag.terminalLeftPath
#check ProbabilityTheory.Process.Path.Cadlag.measurable_terminalLeftValue
#check ProbabilityTheory.Process.Path.Cadlag.measurable_terminalLeftPath
#check ProbabilityTheory.RandomWalk.measurable_sourceNormalizedStepCadlagPathIcc
#check ProbabilityTheory.RandomWalk.sourceNormalizedStepCadlagPathIcc_apply_top
#check ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.tendsto_scaledLog_sourceNormalizedStepCorridor_eq_energyRate
#check ProbabilityTheory.RandomWalk.sourceNormalizedStepCadlagPathIcc_range_eq_scaledDisplacement
#check ProbabilityTheory.RandomWalk.sourceNormalizedStepCadlagPathIcc_mem_rangeInOpenInterval_iff
#check ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.sourceNormalizedStepCorridor_m2_rate
#check ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.tendsto_log_probability_ratio_of_IsM_of_sourceDiscreteM2Rates
#check ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.tendsto_log_probability_ratio_of_IsM_of_sourceStableInputs
#check ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.tendsto_log_probability_ratio_of_IsM_of_source_index_lt_one
#check ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.tendsto_log_probability_ratio_of_IsM_of_source_index_one
#check ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.tendsto_log_probability_ratio_of_IsM_of_source_index_gt_one
#check ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.tendsto_log_probability_ratio_of_IsM_of_source_index_two
#check ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.existsUnique_inner_outer_log_probability_ratio_of_IsM_of_sourceStableInputs
#check ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Gaussian.tendsto_log_probability_ratio_of_IsM_of_source_index_two_of_brownian_explicit
#check ProbabilityTheory.IsStableLevyProcess.unitIntervalPathLaw
#check ProbabilityTheory.IsStableLevyProcess.isStableClockProcessLaw_unitIntervalPathLaw

example {Ω : Type*} [MeasurableSpace Ω]
    {α : ℝ} {μ : MeasureTheory.Measure ℝ}
    {P : MeasureTheory.Measure Ω} [MeasureTheory.IsProbabilityMeasure P]
    {X : ℝ≥0 → Ω → ℝ}
    (hX : ProbabilityTheory.IsStableLevyProcess α μ X P) :
    ProbabilityTheory.IsStableClockProcessLaw α μ ProbabilityTheory.unitIntervalClock
      hX.unitIntervalPathLaw := by
  exact hX.isStableClockProcessLaw_unitIntervalPathLaw

#print axioms ProbabilityTheory.Process.Path.Cadlag.measurable_terminalLeftPath
#print axioms ProbabilityTheory.RandomWalk.measurable_sourceNormalizedStepCadlagPathIcc
#print axioms ProbabilityTheory.RandomWalk.sourceNormalizedStepCadlagPathIcc_apply_top
#print axioms ProbabilityTheory.RandomWalk.sourceNormalizedStepCadlagPathIcc_range_eq_scaledDisplacement
#print axioms ProbabilityTheory.RandomWalk.sourceNormalizedStepCadlagPathIcc_mem_rangeInOpenInterval_iff
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.tendsto_scaledLog_sourceNormalizedStepCorridor_eq_energyRate
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.sourceNormalizedStepCorridor_m2_rate
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.tendsto_log_probability_ratio_of_IsM_of_sourceDiscreteM2Rates
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.tendsto_log_probability_ratio_of_IsM_of_sourceStableInputs
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.tendsto_log_probability_ratio_of_IsM_of_source_index_lt_one
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.tendsto_log_probability_ratio_of_IsM_of_source_index_one
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.tendsto_log_probability_ratio_of_IsM_of_source_index_gt_one
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.tendsto_log_probability_ratio_of_IsM_of_source_index_two
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.existsUnique_inner_outer_log_probability_ratio_of_IsM_of_sourceDiscreteM2Rates
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.existsUnique_inner_outer_log_probability_ratio_of_IsM_of_sourceStableInputs
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Gaussian.canonicalMogulskiiScale
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Gaussian.tendsto_log_probability_ratio_of_IsM_of_source_index_two_of_brownian_explicit
#print axioms ProbabilityTheory.IsStableLevyProcess.unitIntervalPathLaw
#print axioms ProbabilityTheory.IsStableLevyProcess.isStableClockProcessLaw_unitIntervalPathLaw

#print axioms MeasureTheory.Measure.innerMeasure_mono
#print axioms MeasureTheory.Measure.measure_le_innerMeasure_of_nullMeasurableSet_subset
#print axioms ProbabilityTheory.Process.SmallDeviation.Mogulskii.tendsto_inner_outer_log_probability_ratio_of_M3Approximation
#print axioms ProbabilityTheory.Process.SmallDeviation.Mogulskii.exists_inner_outer_log_probability_ratio_of_IsM
#print axioms ProbabilityTheory.HasStableProcessEscapeRate.isM_inner_outer_rate
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.existsUnique_inner_outer_log_probability_ratio_of_IsM_of_discreteM2Rates

#print axioms ProbabilityTheory.Process.SmallDeviation.Mogulskii.HasStableProcessEscapeRate.eq_neg_pi_sq_div_eight
#print axioms ProbabilityTheory.Process.SmallDeviation.Mogulskii.HasStableProcessEscapeRate.fullWidthCoefficient_eq_neg_pi_sq_div_two
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Gaussian.exists_brownian_escapeRate_eq_neg_pi_sq_div_eight
