/-
Copyright (c) 2026 WANG Yiyang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: WANG Yiyang
-/

module

public import Topology.Cadlag.Skorokhod.EDistance.Logarithmic.Topology
public import Topology.Cadlag.Skorokhod.TimeChange.FinitePartition.LogDistortion
public import Topology.Cadlag.Skorokhod.Oscillation.Partition.Existence

/-!
# Comparing the two Skorokhod metrics

The logarithmic time-change cost is stronger than the ordinary `J₁` cost.
This module develops the reverse comparison locally, using the oscillation
partition of the fixed path and a piecewise-affine replacement for a nearby
ordinary time change.
-/

@[expose] public section

open scoped ENNReal
open Filter Set
open scoped Topology

namespace Skorokhod

private theorem continuousAt_relativeLogDistortionBound :
    ContinuousAt (fun q : ℝ => max (Real.log (1 + q)) (-Real.log (1 - q))) 0 := by
  have hplusArg : ContinuousAt (fun q : ℝ => 1 + q) 0 := by fun_prop
  have hminusArg : ContinuousAt (fun q : ℝ => 1 - q) 0 := by fun_prop
  have hlog : ContinuousAt (fun z : ℝ => Real.log z) 1 :=
    Real.continuousAt_log (by norm_num)
  have hlogPlus : ContinuousAt (fun q : ℝ => Real.log (1 + q)) 0 := by
    have hlog' : ContinuousAt (fun z : ℝ => Real.log z) (1 + 0) := by
      simpa only [add_zero] using hlog
    simpa only [Function.comp_def] using
      ContinuousAt.comp (f := fun q : ℝ => 1 + q) (x := 0)
        (g := fun z : ℝ => Real.log z) hlog' hplusArg
  have hlogMinus : ContinuousAt (fun q : ℝ => Real.log (1 - q)) 0 := by
    have hlog' : ContinuousAt (fun z : ℝ => Real.log z) (1 - 0) := by
      simpa only [sub_zero] using hlog
    simpa only [Function.comp_def] using
      ContinuousAt.comp (f := fun q : ℝ => 1 - q) (x := 0)
        (g := fun z : ℝ => Real.log z) hlog' hminusArg
  have hminus : ContinuousAt (fun q : ℝ => -Real.log (1 - q)) 0 :=
    ContinuousAt.neg hlogMinus
  change Filter.Tendsto (fun q : ℝ =>
    max (Real.log (1 + q)) (-Real.log (1 - q))) (nhds 0)
      (nhds (max (Real.log (1 + 0)) (-Real.log (1 - 0))))
  exact hlogPlus.tendsto.max hminus.tendsto

/-- The point index of the finite-point partition generated by `partition`'s
knots agrees with the index already stored in `partition`. -/
private theorem finitePointIndex_eq_partitionIndex
    (partition : OscillationPartition) (t : unitInterval) :
    (TimeChange.FinitePartition.ofPoints partition.size_pos partition.points
      partition.first partition.last partition.strictMono_points).index t =
        partition.index t := by
  let generated := TimeChange.FinitePartition.ofPoints partition.size_pos
    partition.points partition.first partition.last partition.strictMono_points
  apply (partition.index_eq_of_cell (generated.index t) t ?_ ?_).symm
  · simpa [generated, TimeChange.FinitePartition.ofPoints,
      OscillationPartition.ofFinitePoints] using generated.index_lower t
  · rcases generated.index_upper t with h | h
    · exact Or.inl (by simpa [generated, TimeChange.FinitePartition.ofPoints,
        OscillationPartition.ofFinitePoints] using h)
    · exact Or.inr (by simpa [generated, TimeChange.FinitePartition.ofPoints,
        OscillationPartition.ofFinitePoints] using h)

/-- Pulling a finite partition back through a time change makes its cell
index agree with the original partition index after applying that clock. -/
private theorem matchingSource_index
    (partition : OscillationPartition) (τ : TimeChange) (t : unitInterval) :
    (TimeChange.FinitePartition.ofPoints partition.size_pos
      (fun i => τ.symm (partition.points i))
      (by simpa using congrArg τ.symm partition.first)
      (by simpa using congrArg τ.symm partition.last)
      (τ.symm.strictMono_toHomeomorph.comp partition.strictMono_points)).index t =
        partition.index (τ t) := by
  let source : Fin (partition.size + 1) → unitInterval :=
    fun i => τ.symm (partition.points i)
  let sourcePartition := TimeChange.FinitePartition.ofPoints partition.size_pos
    source (by simpa [source] using congrArg τ.symm partition.first)
    (by simpa [source] using congrArg τ.symm partition.last)
    (τ.symm.strictMono_toHomeomorph.comp partition.strictMono_points)
  apply (partition.index_eq_of_cell (sourcePartition.index t) (τ t) ?_ ?_).symm
  · have h := τ.strictMono_toHomeomorph.monotone (sourcePartition.index_lower t)
    simpa [sourcePartition, source, TimeChange.FinitePartition.ofPoints,
      OscillationPartition.ofFinitePoints] using h
  · rcases sourcePartition.index_upper t with h | h
    · exact Or.inl <| by
        have h' := τ.strictMono_toHomeomorph h
        simpa [sourcePartition, source, TimeChange.FinitePartition.ofPoints,
          OscillationPartition.ofFinitePoints] using h'
    · exact Or.inr <| by
        simpa [sourcePartition, TimeChange.FinitePartition.ofPoints,
          OscillationPartition.ofFinitePoints] using h

/-- A J₁ time-change witness can be replaced by a piecewise-affine clock
whose logarithmic distortion is controlled by a fixed small-oscillation
partition of the first path. -/
theorem billingsleyEDist_le_of_j1Cost_le_of_oscillationPartition
    {E : Type*} [MetricSpace E]
    (f g : CadlagPath unitInterval E) (partition : OscillationPartition)
    {osc δ : ℝ} (hosc : OscillationBoundedOnPartition partition f osc)
    (τ : TimeChange) (hδ : 0 ≤ δ) (hδsmall : δ < partition.mesh / 8)
    (hcost : j1Cost f g τ ≤ ENNReal.ofReal δ) :
    billingsleyEDist f g ≤ ENNReal.ofReal
      (max (max (Real.log (1 + 4 * δ / partition.mesh))
        (-Real.log (1 - 4 * δ / partition.mesh))) (osc + δ)) := by
  have hosc_nonneg : 0 ≤ osc := by
    have h := hosc ⊥ ⊥ (ne_of_lt bot_lt_top) (ne_of_lt bot_lt_top) rfl
    simpa using h
  have hτdistENN : ENNReal.ofReal τ.distortion ≤ ENNReal.ofReal δ :=
    (le_max_left _ _).trans hcost
  have hτdist : τ.distortion ≤ δ :=
    (ENNReal.ofReal_le_ofReal_iff hδ).mp hτdistENN
  have hspace : uniformEDist (τ.act f) g ≤ ENNReal.ofReal δ :=
    (le_max_right _ _).trans hcost
  let source : Fin (partition.size + 1) → unitInterval :=
    fun i => τ.symm (partition.points i)
  let target : Fin (partition.size + 1) → unitInterval := partition.points
  have hsourceFirst : source ⟨0, by omega⟩ = ⊥ := by
    simpa [source] using congrArg τ.symm partition.first
  have hsourceLast : source ⟨partition.size, by omega⟩ = ⊤ := by
    simpa [source] using congrArg τ.symm partition.last
  have hsourceStrict : StrictMono source :=
    τ.symm.strictMono_toHomeomorph.comp partition.strictMono_points
  have htargetFirst : target ⟨0, by omega⟩ = ⊥ := by
    exact partition.first
  have htargetLast : target ⟨partition.size, by omega⟩ = ⊤ := by
    exact partition.last
  have htargetStrict : StrictMono target := partition.strictMono_points
  have hpoints : ∀ i, dist (source i) (target i) ≤ δ := by
    intro i
    calc
      dist (source i) (target i) ≤ τ.symm.distortion :=
        τ.symm.dist_apply_le_distortion (partition.points i)
      _ = τ.distortion := TimeChange.distortion_symm τ
      _ ≤ δ := hτdist
  have hclock := TimeChange.FinitePartition.ofMatchingPartitions_logDistortion_le
    partition.size_pos source target hsourceFirst hsourceLast hsourceStrict
    htargetFirst htargetLast htargetStrict partition.mesh δ partition.mesh_pos hδ
    hδsmall partition.gap_lower hpoints
  let clock := TimeChange.FinitePartition.ofMatchingPartitions partition.size_pos source target
    hsourceFirst hsourceLast hsourceStrict htargetFirst htargetLast htargetStrict
  have hspatial : uniformEDist (clock.act f) g ≤ ENNReal.ofReal (osc + δ) := by
    rw [uniformEDist_eq_edist, UniformFun.edist_def]
    apply iSup_le
    intro t
    rw [edist_dist]
    have hcell : partition.index (clock t) = partition.index (τ t) := by
      let sourcePartition := TimeChange.FinitePartition.ofPoints partition.size_pos
        source hsourceFirst hsourceLast hsourceStrict
      let targetPartition := TimeChange.FinitePartition.ofPoints partition.size_pos
        target htargetFirst htargetLast htargetStrict
      have htargetIndex (x : unitInterval) :
          targetPartition.index x = partition.index x := by
        simpa [targetPartition, target] using
          finitePointIndex_eq_partitionIndex partition x
      have hmap := TimeChange.FinitePartition.map_index partition.size_pos source target
        hsourceFirst hsourceLast hsourceStrict htargetFirst htargetLast htargetStrict t
      have hmapIndex : targetPartition.index (clock t) = sourcePartition.index t := by
        simpa [clock, targetPartition, sourcePartition,
          TimeChange.FinitePartition.ofMatchingPartitions,
          TimeChange.FinitePartition.homeomorph] using hmap
      have hsourceIndex : sourcePartition.index t = partition.index (τ t) := by
        simpa [sourcePartition, source] using matchingSource_index partition τ t
      exact (htargetIndex (clock t)).symm.trans (hmapIndex.trans hsourceIndex)
    have herror (t : unitInterval) : dist (τ.act f t) (g t) ≤ δ := by
      have herrorENN : edist (τ.act f t) (g t) ≤ ENNReal.ofReal δ :=
        (edist_apply_le_uniformEDist (τ.act f) g t).trans hspace
      rw [edist_dist] at herrorENN
      exact (ENNReal.ofReal_le_ofReal_iff hδ).mp herrorENN
    have hspatialPoint : dist (f (clock t)) (g t) ≤ osc + δ := by
      by_cases ht : t = ⊤
      · subst t
        have hsum : δ ≤ osc + δ := by linarith [hosc_nonneg]
        simpa [clock, TimeChange.act_apply, TimeChange.apply_top] using
          (herror ⊤).trans hsum
      · have hclockTop : clock t ≠ ⊤ := by
          intro heq
          have hlt : clock t < clock ⊤ :=
            clock.strictMono_toHomeomorph (lt_top_iff_ne_top.mpr ht)
          rw [TimeChange.apply_top, heq] at hlt
          exact (not_lt_of_ge le_top hlt).elim
        have hτTop : τ t ≠ ⊤ := by
          intro heq
          have hlt : τ t < τ ⊤ :=
            τ.strictMono_toHomeomorph (lt_top_iff_ne_top.mpr ht)
          rw [TimeChange.apply_top, heq] at hlt
          exact (not_lt_of_ge le_top hlt).elim
        have hoscPoint := hosc (clock t) (τ t) hclockTop hτTop hcell
        calc
          dist (f (clock t)) (g t) ≤
              dist (f (clock t)) (f (τ t)) + dist (f (τ t)) (g t) :=
            dist_triangle _ _ _
          _ ≤ osc + δ := add_le_add hoscPoint (herror t)
    exact ENNReal.ofReal_le_ofReal hspatialPoint
  have hcostClock : billingsleyCost f g clock ≤ ENNReal.ofReal
      (max (max (Real.log (1 + 4 * δ / partition.mesh))
        (-Real.log (1 - 4 * δ / partition.mesh))) (osc + δ)) := by
    unfold billingsleyCost
    have hclock' : clock.logDistortion ≤ ENNReal.ofReal
        (max (Real.log (1 + 4 * δ / partition.mesh))
          (-Real.log (1 - 4 * δ / partition.mesh))) := by
      simpa [clock] using hclock
    calc
      max clock.logDistortion (uniformEDist (clock.act f) g) ≤
          max (ENNReal.ofReal (max (Real.log (1 + 4 * δ / partition.mesh))
            (-Real.log (1 - 4 * δ / partition.mesh))))
            (ENNReal.ofReal (osc + δ)) := max_le
              (hclock'.trans (le_max_left _ _))
              (hspatial.trans (le_max_right _ _))
      _ = ENNReal.ofReal
          (max (max (Real.log (1 + 4 * δ / partition.mesh))
            (-Real.log (1 - 4 * δ / partition.mesh))) (osc + δ)) := by
        simp only [ENNReal.ofReal_max]
  exact (billingsleyEDist_le_cost f g clock).trans hcostClock

/-- The identity map from the ordinary Skorokhod `J₁` path metric to the
Billingsley logarithmic path metric is continuous at every càdlàg path. The
modulus may depend on the fixed path through a finite small-oscillation
partition. -/
theorem continuousAt_toBillingsleyPath {E : Type*} [MetricSpace E]
    (f : CadlagPath unitInterval E) :
    ContinuousAt (fun g : CadlagPath unitInterval E =>
      (⟨g⟩ : BillingsleyPath E)) f := by
  rw [Metric.continuousAt_iff]
  intro ε hε
  obtain ⟨partition, osc, hoscLt, hosc⟩ :=
    IsCadlag.exists_oscillation_partition f.isCadlag_toFun (by linarith : 0 < ε / 4)
  have hoscPartition : OscillationBoundedOnPartition partition f osc := by
    simpa using hosc
  have hosc_nonneg : 0 ≤ osc := by
    have h := hoscPartition ⊥ ⊥ (ne_of_lt bot_lt_top) (ne_of_lt bot_lt_top) rfl
    simpa using h
  have hnear : {q : ℝ |
      max (Real.log (1 + q)) (-Real.log (1 - q)) < ε} ∈ 𝓝 (0 : ℝ) := by
    have hphiZero : max (Real.log (1 + 0)) (-Real.log (1 - 0)) < ε := by
      simpa using hε
    have heventually : ∀ᶠ q : ℝ in 𝓝 (0 : ℝ),
        max (Real.log (1 + q)) (-Real.log (1 - q)) ∈ Set.Iio ε := by
      simpa using
        continuousAt_relativeLogDistortionBound.eventually (Iio_mem_nhds hphiZero)
    filter_upwards [heventually] with q hq
    exact hq
  obtain ⟨radius, hradius, hball⟩ := Metric.mem_nhds_iff.mp hnear
  let δ : ℝ := min (partition.mesh / 16)
    (min (partition.mesh * radius / 16) ((ε - osc) / 2))
  have hmeshδ : 0 < partition.mesh / 16 :=
    div_pos partition.mesh_pos (by norm_num)
  have hradiusδ : 0 < partition.mesh * radius / 16 :=
    div_pos (mul_pos partition.mesh_pos hradius) (by norm_num)
  have hmargin : 0 < (ε - osc) / 2 := by linarith
  have hδpos : 0 < δ := by
    dsimp [δ]
    exact lt_min hmeshδ (lt_min hradiusδ hmargin)
  have hδsmall : δ < partition.mesh / 8 := by
    have hδle : δ ≤ partition.mesh / 16 := min_le_left _ _
    dsimp [δ] at hδle ⊢
    linarith
  have hδmargin : δ < ε - osc := by
    have hδle : δ ≤ (ε - osc) / 2 := (min_le_right _ _).trans (min_le_right _ _)
    dsimp [δ] at hδle ⊢
    linarith
  have hq_nonneg : 0 ≤ 4 * δ / partition.mesh :=
    div_nonneg (by positivity) partition.mesh_pos.le
  have hq_lt_radius : 4 * δ / partition.mesh < radius := by
    have hδle : δ ≤ partition.mesh * radius / 16 :=
      (min_le_right _ _).trans (min_le_left _ _)
    have hprod : 0 < partition.mesh * radius := mul_pos partition.mesh_pos hradius
    rw [div_lt_iff₀ partition.mesh_pos]
    dsimp [δ] at hδle
    nlinarith
  have hqmem : 4 * δ / partition.mesh ∈ Metric.ball (0 : ℝ) radius := by
    rw [Metric.mem_ball, Real.dist_eq]
    simpa [abs_of_nonneg hq_nonneg] using hq_lt_radius
  have hlogBound :
      max (Real.log (1 + 4 * δ / partition.mesh))
        (-Real.log (1 - 4 * δ / partition.mesh)) < ε := by
    exact hball hqmem
  have hspaceBound : osc + δ < ε := by linarith
  have htotalBound : max
      (max (Real.log (1 + 4 * δ / partition.mesh))
        (-Real.log (1 - 4 * δ / partition.mesh))) (osc + δ) < ε :=
    max_lt hlogBound hspaceBound
  refine ⟨δ, hδpos, fun g hgf => ?_⟩
  have hdistfg : dist f g < δ := by simpa [dist_comm] using hgf
  have hj1 : j1EDist f g < ENNReal.ofReal δ := by
    rw [← edist_cadlagPath_eq_j1EDist, edist_dist]
    exact (ENNReal.ofReal_lt_ofReal_iff hδpos).2 hdistfg
  obtain ⟨τ, hτ⟩ := exists_timeChange_j1Cost_lt hj1
  have hbill : billingsleyEDist f g ≤ ENNReal.ofReal
      (max (max (Real.log (1 + 4 * δ / partition.mesh))
        (-Real.log (1 - 4 * δ / partition.mesh))) (osc + δ)) := by
    exact billingsleyEDist_le_of_j1Cost_le_of_oscillationPartition f g partition
      hoscPartition τ hδpos.le hδsmall hτ.le
  have hbilllt : billingsleyEDist g f < ENNReal.ofReal ε := by
    rw [billingsleyEDist_comm]
    exact hbill.trans_lt <| (ENNReal.ofReal_lt_ofReal_iff hε).2 htotalBound
  have hdist : dist (⟨g⟩ : BillingsleyPath E) (⟨f⟩ : BillingsleyPath E) < ε := by
    have hed : edist (⟨g⟩ : BillingsleyPath E) (⟨f⟩ : BillingsleyPath E) <
        ENNReal.ofReal ε := by
      change billingsleyEDist g f < _
      exact hbilllt
    rw [edist_dist, ENNReal.ofReal_lt_ofReal_iff hε] at hed
    exact hed
  exact hdist

/-- The identity on paths is continuous from the ordinary `J₁` metric to
Billingsley's logarithmic metric. -/
theorem continuous_toBillingsleyPath {E : Type*} [MetricSpace E] :
    Continuous (fun g : CadlagPath unitInterval E =>
      (⟨g⟩ : BillingsleyPath E)) := by
  exact continuous_iff_continuousAt.2 continuousAt_toBillingsleyPath

/-- The ordinary `J₁` and Billingsley path spaces have the same topology. -/
noncomputable def billingsleyPathHomeomorph {E : Type*} [MetricSpace E] :
    CadlagPath unitInterval E ≃ₜ BillingsleyPath E where
  toEquiv :=
    { toFun := fun f => ⟨f⟩
      invFun := fun f => f.toCadlagPath
      left_inv := fun _ => rfl
      right_inv := fun _ => rfl }
  continuous_toFun := continuous_toBillingsleyPath
  continuous_invFun := uniformContinuous_toCadlagPath.continuous

end Skorokhod

end
