import Probability.Process.Path.Cadlag.FiniteDimensional.Dense

#print axioms Skorokhod.measurableEmbedding_denseEvaluation
#print axioms Skorokhod.measure_map_finiteEvaluation_eq_of_gridEvaluation_eq
#print axioms Skorokhod.measure_eq_of_map_finiteDenseEvaluation_eq
#print axioms Skorokhod.ProbabilityMeasure.tendsto_of_tight_of_finiteGridEvaluation
