/-
Copyright (c) 2026 WANG Yiyang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: WANG Yiyang
-/

import Probability.BranchingRandomWalk.Selection.NSelection.Law.SelectedPopulation
import Probability.BranchingRandomWalk.Population.Processes.StepSelection.RootIndexed

/-!
# Product law for a finite step-selected source

This specializes the selected-target matching theorem to a source population
generated by an arbitrary measurable `Step.FiniteSelection`.  These are the
local, time-homogeneous examples of causal killed branching populations and
allow zero, one, or arbitrarily many available children before the finite rule
is applied.
-/

open MeasureTheory ProbabilityTheory

namespace ProbabilityTheory.BranchingRandomWalk.Selection.NSelection

open ProbabilityTheory.BranchingRandomWalk.Coupling

open Combinatorics.UlamHarris Combinatorics.Branching
open Combinatorics.Branching.Selection.NSelection

/-- Equal-rank installation couples a finite step-selected source to the
concrete first-`N` target while preserving the target product-field law. -/
theorem RootIndexed.rankInstalledField_stepSelection_law
    {Root α Mark Position Value : Type*}
    [MeasurableSpace (RootIndexed.TreeNode Root α)]
    [Countable (RootIndexed.TreeNode Root α)]
    [MeasurableSpace Mark] [MeasurableSpace Position]
    [AddCommMonoid Position] [MeasurableAdd₂ Position]
    [MeasurableSpace Value] [TopologicalSpace Value]
    [OpensMeasurableSpace Value] [LinearOrder Value]
    [SecondCountableTopology Value] [OrderClosedTopology Value]
    [MeasurableEq Value]
    [LinearOrder (RootIndexed.TreeNode Root α)]
    (μ : Measure (Step α Mark)) [IsProbabilityMeasure μ]
    (R : Step.FiniteSelection α Mark) (hR : Measurable R.select)
    (sourceRoots targetRoots : Finset Root)
    (N : ℕ) (initial : Root → Position)
    (d : Mark → Position) (hd : Measurable d)
    (φ : Position → Value) (hφ : Measurable φ) :
    let sourceValue := fun k
        (field : RootIndexed.StepField (Root ⊕ Root) α Mark) =>
      RootIndexed.observedPositionAtGeneration initial d φ k
        (field.reindex Sum.inl)
    let targetValue := fun k
        (_ : RootIndexed.StepField (Root ⊕ Root) α Mark)
        (field : RootIndexed.StepField Root α Mark) =>
      RootIndexed.observedPositionAtGeneration initial d φ k field
    let source := fun k
        (field : RootIndexed.StepField (Root ⊕ Root) α Mark) =>
      RootIndexed.StepSelection.labelledPopulationOn R sourceRoots k
        (field.reindex Sum.inl)
    let target := fun k
        (_ : RootIndexed.StepField (Root ⊕ Root) α Mark)
        (field : RootIndexed.StepField Root α Mark) =>
      RootIndexed.selectedPopulationTotalized N targetRoots initial d φ k field
    ∀ n,
      (RootIndexed.stepFieldLaw (Root := Root ⊕ Root) μ).map
          (RootIndexed.rankInstalledField sourceValue targetValue source target
            RootIndexed.StepField.left RootIndexed.StepField.right n) =
        RootIndexed.stepFieldLaw (Root := Root) μ := by
  dsimp only
  let sourceValue := fun k
      (field : RootIndexed.StepField (Root ⊕ Root) α Mark) =>
    RootIndexed.observedPositionAtGeneration initial d φ k
      (field.reindex Sum.inl)
  let source := fun k
      (field : RootIndexed.StepField (Root ⊕ Root) α Mark) =>
    RootIndexed.StepSelection.labelledPopulationOn R sourceRoots k
      (field.reindex Sum.inl)
  have hsourceMeas (k : ℕ) : Measurable[RootIndexed.stepFiltration
      (Root := Root ⊕ Root) (α := α) (X := Mark) k] (source k) := by
    exact (RootIndexed.StepSelection.labelledPopulationOn_adapted
      R hR sourceRoots k).comp
        (RootIndexed.StepField.reindex_filtration_measurable Sum.inl k)
  have hsourceFiber (k : ℕ) (s : Finset (RootIndexed.TreeNode Root α)) :
      MeasurableSet[RootIndexed.stepFiltration
        (Root := Root ⊕ Root) (α := α) (X := Mark) k]
        {field | source k field = s} :=
    hsourceMeas k (measurableSet_singleton s)
  have hsourceRange (k : ℕ) : (Set.range (source k)).Countable :=
    Set.to_countable _
  have hsourceKey (k : ℕ) : ∀ p q,
      Measurable[RootIndexed.stepFiltration
        (Root := Root ⊕ Root) (α := α) (X := Mark) k]
        fun field => valueKey (sourceValue k field) q <
          valueKey (sourceValue k field) p := by
    let _ : MeasurableSpace
        (RootIndexed.StepField (Root ⊕ Root) α Mark) :=
      RootIndexed.stepFiltration
        (Root := Root ⊕ Root) (α := α) (X := Mark) k
    intro p q
    apply measurable_valueKey_lt
    intro r
    exact hφ.comp ((RootIndexed.positionAtGeneration_measurable
      initial d hd k r.1 r.2).comp
        (RootIndexed.StepField.reindex_filtration_measurable Sum.inl k))
  have hsourceDepth : ∀ k field p, p ∈ source k field → p.2.length = k := by
    intro k field p hp
    exact RootIndexed.StepSelection.labelledPopulationOn_depth
      R sourceRoots k (field.reindex Sum.inl) hp
  exact fun n =>
    (RootIndexed.rankInstalledField_totalizedSelectedPopulation_measurable_law
      μ N targetRoots initial d hd φ hφ sourceValue source
      hsourceDepth hsourceFiber hsourceRange hsourceKey n).2

end ProbabilityTheory.BranchingRandomWalk.Selection.NSelection
