/-
Copyright (c) 2026 WANG Yiyang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: WANG Yiyang
-/

module

public import Mathlib.MeasureTheory.Constructions.Polish.Basic
public import Mathlib.MeasureTheory.MeasurableSpace.Constructions
public import Mathlib.Topology.Instances.Real.Lemmas
public import Topology.Cadlag.Skorokhod.Integral
public import Topology.Cadlag.Skorokhod.Separable

/-!
# The Borel structure on càdlàg Skorokhod path space

On real-valued paths over the compact unit interval, the Borel structure of
the Skorokhod `J₁` topology is generated by evaluations at rational times.
-/

@[expose] public section

open Filter MeasureTheory Set
open scoped Topology

namespace Skorokhod

/-- Rational coordinates in the unit interval. -/
abbrev RationalUnitIntervalTime :=
  {q : ℚ // (0 : ℝ) ≤ (q : ℝ) ∧ (q : ℝ) ≤ 1}

def rationalTimeToUnitInterval (q : RationalUnitIntervalTime) : unitInterval :=
  ⟨(q : ℝ), q.property⟩

/-- The vector of all rational-time evaluations of a real-valued càdlàg path. -/
def rationalEvaluation (path : CadlagPath unitInterval ℝ) : RationalUnitIntervalTime → ℝ :=
  fun q => path (rationalTimeToUnitInterval q)

theorem measurable_rationalEvaluation :
    Measurable (rationalEvaluation :
      CadlagPath unitInterval ℝ → RationalUnitIntervalTime → ℝ) := by
  rw [measurable_pi_iff]
  intro q
  simpa [rationalEvaluation] using measurable_apply (rationalTimeToUnitInterval q)

private theorem rationalEvaluation_injective :
    Function.Injective (rationalEvaluation :
      CadlagPath unitInterval ℝ → RationalUnitIntervalTime → ℝ) := by
  intro f g hfg
  apply CadlagPath.ext (T := unitInterval) (E := ℝ)
  intro t
  by_cases ht : t = ⊤
  · subst t
    let q : RationalUnitIntervalTime := ⟨1, by norm_num⟩
    have hq : rationalTimeToUnitInterval q = ⊤ := by
      apply Subtype.ext
      simp [rationalTimeToUnitInterval, q]
    have heq := congrFun hfg q
    simpa [rationalEvaluation, q, hq] using heq
  · have htReal : (t : ℝ) < 1 := (lt_top_iff_ne_top).2 ht
    obtain ⟨u, hu_anti, hu_above, hu_tendsto⟩ :=
      Real.exists_seq_rat_strictAnti_tendsto (t : ℝ)
    have hu_eventually_lt_one : ∀ᶠ n : ℕ in atTop, (u n : ℝ) < 1 :=
      hu_tendsto.eventually (Iio_mem_nhds htReal)
    obtain ⟨N, hN⟩ := eventually_atTop.1 hu_eventually_lt_one
    let τ (n : ℕ) : unitInterval :=
      ⟨(u (N + n) : ℝ),
        ⟨le_trans t.property.1 (hu_above (N + n)).le,
          (hN (N + n) (by omega)).le⟩⟩
    let q (n : ℕ) : RationalUnitIntervalTime :=
      ⟨u (N + n),
        ⟨le_trans t.property.1 (hu_above (N + n)).le,
          (hN (N + n) (by omega)).le⟩⟩
    have hτ_eq (n : ℕ) : rationalTimeToUnitInterval (q n) = τ n := rfl
    have hτ_tendsto_real : Tendsto (fun n : ℕ => (u (N + n) : ℝ)) atTop (𝓝 (t : ℝ)) := by
      have hshift : Tendsto (fun n : ℕ => N + n) atTop atTop :=
        tendsto_atTop_mono (fun n => Nat.le_add_left n N) tendsto_id
      exact hu_tendsto.comp hshift
    have hτ_tendsto : Tendsto τ atTop (𝓝 t) :=
      tendsto_subtype_rng.2 hτ_tendsto_real
    have hτ_gt : ∀ n, t < τ n := fun n => hu_above (N + n)
    have hτ_within : Tendsto τ atTop (𝓝[Set.Ioi t] t) :=
      tendsto_nhdsWithin_iff.2 ⟨hτ_tendsto, Eventually.of_forall hτ_gt⟩
    have hseq : ∀ n, f (τ n) = g (τ n) := by
      intro n
      have heq := congrFun hfg (q n)
      exact heq
    have hlim_f : Tendsto (fun n => f (τ n)) atTop (𝓝 (f t)) :=
      (f.isCadlag_toFun.isRightContinuous t).tendsto.comp hτ_within
    have hlim_g : Tendsto (fun n => g (τ n)) atTop (𝓝 (g t)) :=
      (g.isCadlag_toFun.isRightContinuous t).tendsto.comp hτ_within
    have hlim_g' : Tendsto (fun n => f (τ n)) atTop (𝓝 (g t)) := by
      simpa only [hseq] using hlim_g
    exact tendsto_nhds_unique hlim_f hlim_g'

/-- The rational evaluation map is a measurable embedding. In particular, the
Borel sigma algebra of the `J₁` path topology is generated by its rational
coordinate evaluations. -/
theorem measurableEmbedding_rationalEvaluation :
    MeasurableEmbedding
      (rationalEvaluation :
        CadlagPath unitInterval ℝ → RationalUnitIntervalTime → ℝ) := by
  apply measurable_rationalEvaluation.measurableEmbedding
  exact rationalEvaluation_injective

/-- The Borel sigma algebra of real càdlàg `J₁` paths is the sigma algebra
generated by rational-time evaluations. -/
theorem borel_eq_comap_rationalEvaluation :
    borel (CadlagPath unitInterval ℝ) =
      MeasurableSpace.comap rationalEvaluation
        (inferInstance : MeasurableSpace (RationalUnitIntervalTime → ℝ)) := by
  exact measurableEmbedding_rationalEvaluation.comap_eq.symm

end Skorokhod

end
