import Combinatorics.BranchingWalk.Step.FiniteSelection
import Probability.BranchingRandomWalk.Timing.Frontier

/-!
# Populations generated by finite step selections

A `Step.FiniteSelection` is applied independently at every retained parent.
The resulting population is defined recursively from the currently exposed
frontier, hence is causal.  No child slot is distinguished and neither marks
nor positions are specialized to real numbers.
-/

open MeasureTheory

namespace ProbabilityTheory.BranchingRandomWalk.StepSelection

open Combinatorics.UlamHarris Combinatorics.Branching

attribute [local instance] Classical.propDecidable Classical.decEq

/-- Selected genuine child addresses of one parent. -/
noncomputable def children
    {α X : Type*} (R : Step.FiniteSelection α X)
    (ω : Mark α (Step α X)) (u : TreeNode α) : Finset (TreeNode α) :=
  (R (ω u)).image fun i => u ++ [i]

theorem mem_children_iff
    {α X : Type*} (R : Step.FiniteSelection α X)
    (ω : Mark α (Step α X)) (u q : TreeNode α) :
    q ∈ children R ω u ↔ ∃ i ∈ R (ω u), q = u ++ [i] := by
  classical
  simp [children, eq_comm]

theorem selected_child_survives
    {α X : Type*} (R : Step.FiniteSelection α X)
    (ω : Mark α (Step α X)) (u q : TreeNode α)
    (hq : q ∈ children R ω u) :
    ∃ i, survive (ω u) i ∧ q = u ++ [i] := by
  obtain ⟨i, hi, rfl⟩ := (mem_children_iff R ω u q).mp hq
  exact ⟨i, R.mem_support (ω u) hi, rfl⟩

theorem children_card_le
    {α X : Type*} (R : Step.FiniteSelection α X)
    (ω : Mark α (Step α X)) (u : TreeNode α) :
    (children R ω u).card ≤ (R (ω u)).card := by
  classical
  exact Finset.card_image_le

/-- Apply the finite step rule to every parent in a finite population. -/
noncomputable def grow
    {α X : Type*} (R : Step.FiniteSelection α X)
    (parents : Finset (TreeNode α))
    (ω : Mark α (Step α X)) : Finset (TreeNode α) :=
  parents.biUnion (children R ω)

theorem mem_grow_iff
    {α X : Type*} (R : Step.FiniteSelection α X)
    (parents : Finset (TreeNode α))
    (ω : Mark α (Step α X)) (q : TreeNode α) :
    q ∈ grow R parents ω ↔
      ∃ u ∈ parents, ∃ i ∈ R (ω u), q = u ++ [i] := by
  classical
  simp [grow, mem_children_iff]

theorem grow_card_le_sum
    {α X : Type*} (R : Step.FiniteSelection α X)
    (parents : Finset (TreeNode α))
    (ω : Mark α (Step α X)) :
    (grow R parents ω).card ≤
      ∑ u ∈ parents, (R (ω u)).card := by
  classical
  calc
    (grow R parents ω).card ≤
        ∑ u ∈ parents, (children R ω u).card :=
      Finset.card_biUnion_le
    _ ≤ ∑ u ∈ parents, (R (ω u)).card := by
      exact Finset.sum_le_sum fun u _ => children_card_le R ω u

theorem grow_card_le_mul
    {α X : Type*} (R : Step.FiniteSelection α X) (N : ℕ)
    (hR : R.IsBoundedBy N)
    (parents : Finset (TreeNode α))
    (ω : Mark α (Step α X)) :
    (grow R parents ω).card ≤ N * parents.card := by
  calc
    (grow R parents ω).card ≤
        ∑ u ∈ parents, (R (ω u)).card := grow_card_le_sum R parents ω
    _ ≤ ∑ _u ∈ parents, N := by
      exact Finset.sum_le_sum fun u _ => hR (ω u)
    _ = N * parents.card := by simp [mul_comm]

/-- Population recursively generated from the root by a finite step rule. -/
noncomputable def population
    {α X : Type*} (R : Step.FiniteSelection α X) :
    ℕ → Mark α (Step α X) → Finset (TreeNode α)
  | 0, _ => {[]}
  | n + 1, ω => grow R (population R n ω) (frontierMarks n ω)

@[simp] theorem population_zero
    {α X : Type*} (R : Step.FiniteSelection α X)
    (ω : Mark α (Step α X)) : population R 0 ω = {[]} :=
  rfl

@[simp] theorem population_succ
    {α X : Type*} (R : Step.FiniteSelection α X)
    (n : ℕ) (ω : Mark α (Step α X)) :
    population R (n + 1) ω =
      grow R (population R n ω) (frontierMarks n ω) :=
  rfl

/-- Every retained address lies in the generation indexed by the recursive
population. -/
theorem population_depth
    {α X : Type*} (R : Step.FiniteSelection α X)
    (ω : Mark α (Step α X)) :
    ∀ n u, u ∈ population R n ω → u.length = n := by
  intro n
  induction n with
  | zero =>
      intro u hu
      simpa using hu
  | succ n ih =>
      intro q hq
      obtain ⟨u, hu, i, _, rfl⟩ :=
        (mem_grow_iff R (population R n ω) (frontierMarks n ω) q).mp hq
      rw [List.length_append, ih u hu]
      simp

/-- Every particle retained at the next generation has a retained parent and
a genuinely surviving child slot in the original pre-sampled field. -/
theorem population_succ_parent
    {α X : Type*} (R : Step.FiniteSelection α X)
    (ω : Mark α (Step α X)) (n : ℕ) (q : TreeNode α)
    (hq : q ∈ population R (n + 1) ω) :
    ∃ u ∈ population R n ω, ∃ i,
      survive (ω u) i ∧ q = u ++ [i] := by
  obtain ⟨u, hu, i, hi, hqeq⟩ :=
    (mem_grow_iff R (population R n ω) (frontierMarks n ω) q).mp hq
  have hdepth : u.length = n := population_depth R ω n u hu
  have hfrontier : frontierMarks n ω u = ω u := by
    simp [frontierMarks, hdepth]
  exact ⟨u, hu, i, R.mem_support _ (hfrontier ▸ hi), hqeq⟩

theorem children_measurable
    {α X : Type*} [Countable α] [MeasurableSpace X]
    (R : Step.FiniteSelection α X) (hR : Measurable R.select)
    (u : TreeNode α) :
    Measurable (fun ω : Mark α (Step α X) => children R ω u) := by
  let append : Finset α → Finset (TreeNode α) :=
    fun s => s.image fun i => u ++ [i]
  have happend : Measurable append := measurable_of_countable _
  exact happend.comp (hR.comp (measurable_pi_apply u))

theorem grow_fixed_measurable
    {α X : Type*} [Countable α] [MeasurableSpace X]
    (R : Step.FiniteSelection α X) (hR : Measurable R.select)
    (parents : Finset (TreeNode α)) :
    Measurable (fun ω : Mark α (Step α X) => grow R parents ω) := by
  classical
  induction parents using Finset.induction_on with
  | empty => simp [grow]
  | @insert u parents hu ih =>
      have hunion : Measurable
          (fun p : Finset (TreeNode α) × Finset (TreeNode α) => p.1 ∪ p.2) :=
        measurable_of_countable _
      have h := hunion.comp ((children_measurable R hR u).prodMk ih)
      change Measurable (fun ω =>
        children R ω u ∪ parents.biUnion (children R ω)) at h
      simpa only [grow, Finset.biUnion_insert] using h

theorem grow_measurable
    {α X : Type*} [Countable α] [MeasurableSpace X]
    (R : Step.FiniteSelection α X) (hR : Measurable R.select) :
    Measurable
      (fun p : Finset (TreeNode α) × Mark α (Step α X) =>
        grow R p.1 p.2) :=
  measurable_from_prod_countable_right (grow_fixed_measurable R hR)

/-- The recursively selected population is adapted to the generation domain
flow. -/
theorem population_adapted
    {α X : Type*} [Countable α] [MeasurableSpace X]
    (R : Step.FiniteSelection α X) (hR : Measurable R.select) :
    ∀ n, Measurable[generationFiltration (M := Step α X) n]
      (population R n) := by
  apply frontier_causal_state_adapted
    (population R) (fun p => grow R p.1 p.2) (grow_measurable R hR)
  · exact measurable_const
  · intro n ω
    rfl

theorem population_card_le
    {α X : Type*} (R : Step.FiniteSelection α X) (N : ℕ)
    (hR : R.IsBoundedBy N) (ω : Mark α (Step α X)) :
    ∀ n, (population R n ω).card ≤ N ^ n := by
  intro n
  induction n with
  | zero => simp
  | succ n ih =>
      exact (grow_card_le_mul R N hR (population R n ω)
        (frontierMarks n ω)).trans <| by
          simpa [pow_succ, mul_comm] using Nat.mul_le_mul_left N ih

end ProbabilityTheory.BranchingRandomWalk.StepSelection
