module

public import Combinatorics.BranchingWalk.Step.FiniteSelection
public import Probability.BranchingRandomWalk.Timing.Frontier

/-!
# Populations generated by finite step selections

A `Step.FiniteSelection` is applied independently at every retained parent.
The resulting population is defined recursively from the currently exposed
frontier, hence is causal.  No child slot is distinguished and neither marks
nor positions are specialized to real numbers.
-/

open MeasureTheory

@[expose] public section

namespace ProbabilityTheory.BranchingRandomWalk.StepSelection

open Combinatorics.UlamHarris Combinatorics.Branching

attribute [local instance] Classical.propDecidable Classical.decEq

/-- Selected genuine child addresses of one parent. -/
noncomputable def children
    {α X : Type*} (R : Step.FiniteSelection α X)
    (ω : Mark α (Step α X)) (u : TreeNode α) : Finset (TreeNode α) :=
  (R (ω u)).image fun i => u ++ [i]

theorem mem_children_iff
    {α X : Type*} (R : Step.FiniteSelection α X)
    (ω : Mark α (Step α X)) (u q : TreeNode α) :
    q ∈ children R ω u ↔ ∃ i ∈ R (ω u), q = u ++ [i] := by
  classical
  simp [children, eq_comm]

theorem selected_child_survives
    {α X : Type*} (R : Step.FiniteSelection α X)
    (ω : Mark α (Step α X)) (u q : TreeNode α)
    (hq : q ∈ children R ω u) :
    ∃ i, survive (ω u) i ∧ q = u ++ [i] := by
  obtain ⟨i, hi, rfl⟩ := (mem_children_iff R ω u q).mp hq
  exact ⟨i, R.mem_support (ω u) hi, rfl⟩

theorem children_card_le
    {α X : Type*} (R : Step.FiniteSelection α X)
    (ω : Mark α (Step α X)) (u : TreeNode α) :
    (children R ω u).card ≤ (R (ω u)).card := by
  classical
  exact Finset.card_image_le

/-- Apply the finite step rule to every parent in a finite population. -/
noncomputable def grow
    {α X : Type*} (R : Step.FiniteSelection α X)
    (parents : Finset (TreeNode α))
    (ω : Mark α (Step α X)) : Finset (TreeNode α) :=
  parents.biUnion (children R ω)

theorem mem_grow_iff
    {α X : Type*} (R : Step.FiniteSelection α X)
    (parents : Finset (TreeNode α))
    (ω : Mark α (Step α X)) (q : TreeNode α) :
    q ∈ grow R parents ω ↔
      ∃ u ∈ parents, ∃ i ∈ R (ω u), q = u ++ [i] := by
  classical
  simp [grow, mem_children_iff]

/-- Membership in one growth step can be read from the unique parent and
last slot of a non-root address.  This avoids enumerating the slot type in
measurability arguments. -/
theorem mem_grow_iff_dropLast_getLast
    {α X : Type*} (R : Step.FiniteSelection α X)
    (parents : Finset (TreeNode α))
    (ω : Mark α (Step α X)) (q : TreeNode α) (hq : q ≠ []) :
    q ∈ grow R parents ω ↔
      q.dropLast ∈ parents ∧ q.getLast hq ∈ R (ω q.dropLast) := by
  rw [mem_grow_iff]
  constructor
  · rintro ⟨u, hu, i, hi, rfl⟩
    simpa using ⟨hu, hi⟩
  · rintro ⟨hu, hi⟩
    exact ⟨q.dropLast, hu, q.getLast hq, hi,
      (List.dropLast_append_getLast hq).symm⟩

theorem grow_card_le_sum
    {α X : Type*} (R : Step.FiniteSelection α X)
    (parents : Finset (TreeNode α))
    (ω : Mark α (Step α X)) :
    (grow R parents ω).card ≤
      ∑ u ∈ parents, (R (ω u)).card := by
  classical
  calc
    (grow R parents ω).card ≤
        ∑ u ∈ parents, (children R ω u).card :=
      Finset.card_biUnion_le
    _ ≤ ∑ u ∈ parents, (R (ω u)).card := by
      exact Finset.sum_le_sum fun u _ => children_card_le R ω u

theorem grow_card_le_mul
    {α X : Type*} (R : Step.FiniteSelection α X) (N : ℕ)
    (hR : R.IsBoundedBy N)
    (parents : Finset (TreeNode α))
    (ω : Mark α (Step α X)) :
    (grow R parents ω).card ≤ N * parents.card := by
  calc
    (grow R parents ω).card ≤
        ∑ u ∈ parents, (R (ω u)).card := grow_card_le_sum R parents ω
    _ ≤ ∑ _u ∈ parents, N := by
      exact Finset.sum_le_sum fun u _ => hR (ω u)
    _ = N * parents.card := by simp [mul_comm]

/-- Population recursively generated from the root by a finite step rule. -/
noncomputable def population
    {α X : Type*} (R : Step.FiniteSelection α X) :
    ℕ → Mark α (Step α X) → Finset (TreeNode α)
  | 0, _ => {[]}
  | n + 1, ω => grow R (population R n ω) (frontierMarks n ω)

@[simp] theorem population_zero
    {α X : Type*} (R : Step.FiniteSelection α X)
    (ω : Mark α (Step α X)) : population R 0 ω = {[]} :=
  rfl

@[simp] theorem population_succ
    {α X : Type*} (R : Step.FiniteSelection α X)
    (n : ℕ) (ω : Mark α (Step α X)) :
    population R (n + 1) ω =
      grow R (population R n ω) (frontierMarks n ω) :=
  rfl

/-- Every retained address lies in the generation indexed by the recursive
population. -/
theorem population_depth
    {α X : Type*} (R : Step.FiniteSelection α X)
    (ω : Mark α (Step α X)) :
    ∀ n u, u ∈ population R n ω → u.length = n := by
  intro n
  induction n with
  | zero =>
      intro u hu
      simpa using hu
  | succ n ih =>
      intro q hq
      obtain ⟨u, hu, i, _, rfl⟩ :=
        (mem_grow_iff R (population R n ω) (frontierMarks n ω) q).mp hq
      rw [List.length_append, ih u hu]
      simp

/-- Every particle retained at the next generation has a retained parent and
a genuinely surviving child slot in the original pre-sampled field. -/
theorem population_succ_parent
    {α X : Type*} (R : Step.FiniteSelection α X)
    (ω : Mark α (Step α X)) (n : ℕ) (q : TreeNode α)
    (hq : q ∈ population R (n + 1) ω) :
    ∃ u ∈ population R n ω, ∃ i,
      survive (ω u) i ∧ q = u ++ [i] := by
  obtain ⟨u, hu, i, hi, hqeq⟩ :=
    (mem_grow_iff R (population R n ω) (frontierMarks n ω) q).mp hq
  have hdepth : u.length = n := population_depth R ω n u hu
  have hfrontier : frontierMarks n ω u = ω u := by
    simp [frontierMarks, hdepth]
  exact ⟨u, hu, i, R.mem_support _ (hfrontier ▸ hi), hqeq⟩

/-- Every retained successor records the selected slot of its unique retained
parent. This is stronger than `population_succ_parent`, which forgets the
selection decision and retains only survival. -/
theorem population_succ_selectedParent
    {α X : Type*} (R : Step.FiniteSelection α X)
    (ω : Mark α (Step α X)) (n : ℕ) (q : TreeNode α)
    (hq : q ∈ population R (n + 1) ω) :
    ∃ u ∈ population R n ω, ∃ i,
      i ∈ R (ω u) ∧ q = u ++ [i] := by
  obtain ⟨u, hu, i, hi, hqeq⟩ :=
    (mem_grow_iff R (population R n ω) (frontierMarks n ω) q).mp hq
  have hdepth : u.length = n := population_depth R ω n u hu
  have hfrontier : frontierMarks n ω u = ω u := by
    simp [frontierMarks, hdepth]
  exact ⟨u, hu, i, hfrontier ▸ hi, hqeq⟩

theorem children_measurable
    {α X : Type*} [MeasurableSpace X]
    (R : Step.FiniteSelection α X) (hR : Measurable R.select)
    (u : TreeNode α) :
    Measurable (fun ω : Mark α (Step α X) => children R ω u) := by
  rw [measurable_finset_iff]
  intro q
  by_cases hq : ∃ i, q = u ++ [i]
  · obtain ⟨i, rfl⟩ := hq
    have hselect : Measurable
        (fun ω : Mark α (Step α X) => R (ω u)) :=
      hR.comp (measurable_pi_apply u)
    have hmem := (measurable_finset_mem i).comp hselect
    convert hmem using 1
    funext ω
    apply propext
    constructor
    · intro h
      obtain ⟨j, hj, heq⟩ := (mem_children_iff R ω u (u ++ [i])).mp h
      have hij : i = j := by
        have hs : [i] = [j] := List.append_cancel_left heq
        simpa using hs
      simpa [hij] using hj
    · intro hi
      exact (mem_children_iff R ω u (u ++ [i])).mpr ⟨i, hi, rfl⟩
  · have hempty : (fun ω : Mark α (Step α X) => q ∈ children R ω u) =
        fun _ => False := by
      funext ω
      apply propext
      constructor
      · intro h
        obtain ⟨i, _, hi⟩ := (mem_children_iff R ω u q).mp h
        exact hq ⟨i, hi⟩
      · simp
    rw [hempty]
    exact measurable_const

theorem grow_fixed_measurable
    {α X : Type*} [MeasurableSpace X]
    (R : Step.FiniteSelection α X) (hR : Measurable R.select)
    (parents : Finset (TreeNode α)) :
    Measurable (fun ω : Mark α (Step α X) => grow R parents ω) := by
  classical
  induction parents using Finset.induction_on with
  | empty => simp [grow]
  | @insert u parents hu ih =>
      have hunion : Measurable
          (fun p : Finset (TreeNode α) × Finset (TreeNode α) => p.1 ∪ p.2) := by
        rw [measurable_finset_iff]
        intro q
        simpa only [Finset.mem_union, Function.comp_apply] using
          (((measurable_finset_mem q).comp measurable_fst).or
            ((measurable_finset_mem q).comp measurable_snd))
      have h := hunion.comp ((children_measurable R hR u).prodMk ih)
      change Measurable (fun ω =>
        children R ω u ∪ parents.biUnion (children R ω)) at h
      simpa only [grow, Finset.biUnion_insert] using h

theorem grow_measurable
    {α X : Type*} [MeasurableSpace X]
    (R : Step.FiniteSelection α X) (hR : Measurable R.select) :
    Measurable
      (fun p : Finset (TreeNode α) × Mark α (Step α X) =>
        grow R p.1 p.2) := by
  rw [measurable_finset_iff]
  intro q
  by_cases hq : q = []
  · subst q
    simp [grow, children]
  · have hparent : Measurable
        (fun p : Finset (TreeNode α) × Mark α (Step α X) =>
          q.dropLast ∈ p.1) :=
      (measurable_finset_mem q.dropLast).comp measurable_fst
    have hslot : Measurable
        (fun p : Finset (TreeNode α) × Mark α (Step α X) =>
          q.getLast hq ∈ R (p.2 q.dropLast)) :=
      (measurable_finset_mem (q.getLast hq)).comp
        (hR.comp ((measurable_pi_apply q.dropLast).comp measurable_snd))
    convert hparent.and hslot using 1
    funext p
    exact propext (mem_grow_iff_dropLast_getLast R p.1 p.2 q hq)

/-- The recursively selected population is adapted to the generation domain
flow. -/
theorem population_adapted
    {α X : Type*} [MeasurableSpace X]
    (R : Step.FiniteSelection α X) (hR : Measurable R.select) :
    ∀ n, Measurable[generationFiltration (M := Step α X) n]
      (population R n) := by
  apply frontier_causal_state_adapted
    (population R) (fun p => grow R p.1 p.2) (grow_measurable R hR)
  · exact measurable_const
  · intro n ω
    rfl

theorem population_card_le
    {α X : Type*} (R : Step.FiniteSelection α X) (N : ℕ)
    (hR : R.IsBoundedBy N) (ω : Mark α (Step α X)) :
    ∀ n, (population R n ω).card ≤ N ^ n := by
  intro n
  induction n with
  | zero => simp
  | succ n ih =>
      exact (grow_card_le_mul R N hR (population R n ω)
        (frontierMarks n ω)).trans <| by
          simpa [pow_succ, mul_comm] using Nat.mul_le_mul_left N ih

end ProbabilityTheory.BranchingRandomWalk.StepSelection
