import Probability.BranchingRandomWalk.Genealogy.RootIndexed.Filtration
import Probability.BranchingRandomWalk.Population.Processes.StepSelection.Basic

/-!
# Root-indexed populations generated by step selections

The population at generation `n` is kept as a family indexed by `Root`.
Consequently an arbitrary root type can carry all pre-sampled copies at once;
neither the definition nor its adaptation theorem enumerates the roots.
-/

open MeasureTheory

namespace ProbabilityTheory.BranchingRandomWalk
namespace RootIndexed
namespace StepSelection

open Combinatorics.UlamHarris Combinatorics.Branching

/-- Apply the same finite step-selection rule to every root's pre-sampled
field.  The result retains the root index as an outer function rather than
encoding all roots in one finite container. -/
noncomputable def population
    {Root α X : Type*} (R : Step.FiniteSelection α X) (n : ℕ)
    (ω : RootIndexed.StepField Root α X) :
    Root → Finset (TreeNode α) :=
  fun r => ProbabilityTheory.BranchingRandomWalk.StepSelection.population R n (ω r)

@[simp] theorem population_apply
    {Root α X : Type*} (R : Step.FiniteSelection α X) (n : ℕ)
    (ω : RootIndexed.StepField Root α X) (r : Root) :
    population R n ω r =
      ProbabilityTheory.BranchingRandomWalk.StepSelection.population R n (ω r) :=
  rfl

@[simp] theorem population_zero
    {Root α X : Type*} (R : Step.FiniteSelection α X)
    (ω : RootIndexed.StepField Root α X) :
    population R 0 ω = fun _ => {[]} := by
  funext r
  simp [population]

theorem population_depth
    {Root α X : Type*} (R : Step.FiniteSelection α X)
    (ω : RootIndexed.StepField Root α X) {r : Root} {n : ℕ}
    {u : TreeNode α} (hu : u ∈ population R n ω r) :
    u.length = n :=
  ProbabilityTheory.BranchingRandomWalk.StepSelection.population_depth
    R (ω r) n u hu

theorem population_succ_parent
    {Root α X : Type*} (R : Step.FiniteSelection α X)
    (ω : RootIndexed.StepField Root α X) (r : Root) (n : ℕ)
    (q : TreeNode α) (hq : q ∈ population R (n + 1) ω r) :
    ∃ u ∈ population R n ω r, ∃ i,
      survive (ω r u) i ∧ q = u ++ [i] :=
  ProbabilityTheory.BranchingRandomWalk.StepSelection.population_succ_parent
    R (ω r) n q hq

/-- All root populations are observable at generation `n`.  Countability is
needed only for each finite labelled population's discrete measurable space;
the root index may be arbitrary because product measurability is checked one
coordinate at a time. -/
theorem population_adapted
    {Root α X : Type*} [Countable α] [MeasurableSpace X]
    (R : Step.FiniteSelection α X) (hR : Measurable R.select) (n : ℕ) :
    Measurable[RootIndexed.stepFiltration
      (Root := Root) (α := α) (X := X) n]
      (population (Root := Root) R n) := by
  let _ : MeasurableSpace (RootIndexed.StepField Root α X) :=
    RootIndexed.stepFiltration (Root := Root) (α := α) (X := X) n
  apply Measurable.of_eval
  intro r
  exact (ProbabilityTheory.BranchingRandomWalk.StepSelection.population_adapted
    R hR n).comp
      (ProbabilityTheory.BranchingRandomWalk.RootIndexed.field_measurable
        (X := X) r n)

theorem population_card_le
    {Root α X : Type*} (R : Step.FiniteSelection α X) (N : ℕ)
    (hR : R.IsBoundedBy N) (ω : RootIndexed.StepField Root α X)
    (r : Root) (n : ℕ) :
    (population R n ω r).card ≤ N ^ n :=
  ProbabilityTheory.BranchingRandomWalk.StepSelection.population_card_le
    R N hR (ω r) n

end StepSelection
end RootIndexed
end ProbabilityTheory.BranchingRandomWalk
