import Probability.BranchingRandomWalk.Genealogy.RootIndexed.Filtration
import Probability.BranchingRandomWalk.Population.Processes.StepSelection.Basic
import Combinatorics.BranchingWalk.Selection.Coupling.Offspring

/-!
# Root-indexed populations generated by step selections

The population at generation `n` is kept as a family indexed by `Root`.
Consequently an arbitrary root type can carry all pre-sampled copies at once;
neither the definition nor its adaptation theorem enumerates the roots.
-/

open MeasureTheory

namespace ProbabilityTheory.BranchingRandomWalk
namespace RootIndexed
namespace StepSelection

open Combinatorics.UlamHarris Combinatorics.Branching

/-- Apply the same finite step-selection rule to every root's pre-sampled
field.  The result retains the root index as an outer function rather than
encoding all roots in one finite container. -/
noncomputable def population
    {Root α X : Type*} (R : Step.FiniteSelection α X) (n : ℕ)
    (ω : RootIndexed.StepField Root α X) :
    Root → Finset (TreeNode α) :=
  fun r => ProbabilityTheory.BranchingRandomWalk.StepSelection.population R n (ω r)

@[simp] theorem population_apply
    {Root α X : Type*} (R : Step.FiniteSelection α X) (n : ℕ)
    (ω : RootIndexed.StepField Root α X) (r : Root) :
    population R n ω r =
      ProbabilityTheory.BranchingRandomWalk.StepSelection.population R n (ω r) :=
  rfl

@[simp] theorem population_zero
    {Root α X : Type*} (R : Step.FiniteSelection α X)
    (ω : RootIndexed.StepField Root α X) :
    population R 0 ω = fun _ => {[]} := by
  funext r
  simp [population]

theorem population_depth
    {Root α X : Type*} (R : Step.FiniteSelection α X)
    (ω : RootIndexed.StepField Root α X) {r : Root} {n : ℕ}
    {u : TreeNode α} (hu : u ∈ population R n ω r) :
    u.length = n :=
  ProbabilityTheory.BranchingRandomWalk.StepSelection.population_depth
    R (ω r) n u hu

theorem population_succ_parent
    {Root α X : Type*} (R : Step.FiniteSelection α X)
    (ω : RootIndexed.StepField Root α X) (r : Root) (n : ℕ)
    (q : TreeNode α) (hq : q ∈ population R (n + 1) ω r) :
    ∃ u ∈ population R n ω r, ∃ i,
      survive (ω r u) i ∧ q = u ++ [i] :=
  ProbabilityTheory.BranchingRandomWalk.StepSelection.population_succ_parent
    R (ω r) n q hq

/-- All root populations are observable at generation `n`. Both the root and
child-slot types may be arbitrary: product measurability is checked one root
at a time, and finite populations are observed through membership events. -/
theorem population_adapted
    {Root α X : Type*} [MeasurableSpace X]
    (R : Step.FiniteSelection α X) (hR : Measurable R.select) (n : ℕ) :
    Measurable[RootIndexed.stepFiltration
      (Root := Root) (α := α) (X := X) n]
      (population (Root := Root) R n) := by
  let _ : MeasurableSpace (RootIndexed.StepField Root α X) :=
    RootIndexed.stepFiltration (Root := Root) (α := α) (X := X) n
  apply Measurable.of_eval
  intro r
  exact (ProbabilityTheory.BranchingRandomWalk.StepSelection.population_adapted
    R hR n).comp
      (ProbabilityTheory.BranchingRandomWalk.RootIndexed.field_measurable
        (X := X) r n)

theorem population_card_le
    {Root α X : Type*} (R : Step.FiniteSelection α X) (N : ℕ)
    (hR : R.IsBoundedBy N) (ω : RootIndexed.StepField Root α X)
    (r : Root) (n : ℕ) :
    (population R n ω r).card ≤ N ^ n :=
  ProbabilityTheory.BranchingRandomWalk.StepSelection.population_card_le
    R N hR (ω r) n

/-! ## A single root as a labelled multi-root population -/

/-- Attach a root label to every particle in that root's selected
population. This is the representation consumed by multi-root cloud and
coupling interfaces. -/
noncomputable def labelledPopulation
    {Root α X : Type*} [DecidableEq (RootIndexed.TreeNode Root α)]
    (R : Step.FiniteSelection α X) (n : ℕ)
    (ω : RootIndexed.StepField Root α X) (r : Root) :
    Finset (RootIndexed.TreeNode Root α) :=
  (population R n ω r).map
    ⟨fun u => (r, u), fun _ _ h => congrArg Prod.snd h⟩

@[simp] theorem mem_labelledPopulation
    {Root α X : Type*} [DecidableEq (RootIndexed.TreeNode Root α)]
    (R : Step.FiniteSelection α X) (n : ℕ)
    (ω : RootIndexed.StepField Root α X) (r s : Root)
    (u : TreeNode α) :
    (s, u) ∈ labelledPopulation R n ω r ↔
      s = r ∧ u ∈ population R n ω r := by
  constructor
  · rw [labelledPopulation, Finset.mem_map]
    rintro ⟨v, hv, hp⟩
    have hs : s = r := (congrArg Prod.fst hp).symm
    have hvu : v = u := congrArg Prod.snd hp
    exact ⟨hs, hvu ▸ hv⟩
  · rintro ⟨rfl, hu⟩
    rw [labelledPopulation, Finset.mem_map]
    exact ⟨u, hu, rfl⟩

@[simp] theorem labelledPopulation_card
    {Root α X : Type*} [DecidableEq (RootIndexed.TreeNode Root α)]
    (R : Step.FiniteSelection α X) (n : ℕ)
    (ω : RootIndexed.StepField Root α X) (r : Root) :
    (labelledPopulation R n ω r).card = (population R n ω r).card := by
  simp [labelledPopulation]

@[simp] theorem labelledPopulation_zero
    {Root α X : Type*} [DecidableEq (RootIndexed.TreeNode Root α)]
    (R : Step.FiniteSelection α X)
    (ω : RootIndexed.StepField Root α X) (r : Root) :
    labelledPopulation R 0 ω r = {(r, [])} := by
  ext p
  rcases p with ⟨s, u⟩
  simp

/-- A labelled selected successor belongs to the abstract offspring-address
set generated by the labelled parent population and the selected slots. -/
theorem labelledPopulation_succ_subset
    {Root α X : Type*} [DecidableEq (RootIndexed.TreeNode Root α)]
    (R : Step.FiniteSelection α X) (n : ℕ)
    (ω : RootIndexed.StepField Root α X) (r : Root) :
    ↑(labelledPopulation R (n + 1) ω r) ⊆
      Combinatorics.Branching.Selection.Coupling.offspringAddressSet
        (↑(labelledPopulation R n ω r))
        (fun p => ↑(R (ω p.1 p.2))) := by
  rintro ⟨s, q⟩ hq
  have hmem := (mem_labelledPopulation R (n + 1) ω r s q).mp hq
  rcases hmem with ⟨hs, hqpop⟩
  subst s
  obtain ⟨u, hu, i, hi, rfl⟩ :=
    ProbabilityTheory.BranchingRandomWalk.StepSelection.population_succ_selectedParent
      R (ω r) n q hqpop
  apply Combinatorics.Branching.Selection.Coupling.mem_offspringAddressSet.mpr
  exact ⟨(r, u), by simpa using hu, i, by simpa using hi, rfl⟩

end StepSelection
end RootIndexed
end ProbabilityTheory.BranchingRandomWalk
