import Probability.BranchingRandomWalk.Genealogy.RootIndexed.Filtration
import Probability.BranchingRandomWalk.Population.Processes.StepSelection.Basic
import Combinatorics.BranchingWalk.Selection.Coupling.Offspring

/-!
# Root-indexed populations generated by step selections

The population at generation `n` is kept as a family indexed by `Root`.
Consequently an arbitrary root type can carry all pre-sampled copies at once;
neither the definition nor its adaptation theorem enumerates the roots.
-/

open MeasureTheory

namespace ProbabilityTheory.BranchingRandomWalk
namespace RootIndexed
namespace StepSelection

open Combinatorics.UlamHarris Combinatorics.Branching

/-- Apply the same finite step-selection rule to every root's pre-sampled
field.  The result retains the root index as an outer function rather than
encoding all roots in one finite container. -/
noncomputable def population
    {Root α X : Type*} (R : Step.FiniteSelection α X) (n : ℕ)
    (ω : RootIndexed.StepField Root α X) :
    Root → Finset (TreeNode α) :=
  fun r => ProbabilityTheory.BranchingRandomWalk.StepSelection.population R n (ω r)

@[simp] theorem population_apply
    {Root α X : Type*} (R : Step.FiniteSelection α X) (n : ℕ)
    (ω : RootIndexed.StepField Root α X) (r : Root) :
    population R n ω r =
      ProbabilityTheory.BranchingRandomWalk.StepSelection.population R n (ω r) :=
  rfl

@[simp] theorem population_zero
    {Root α X : Type*} (R : Step.FiniteSelection α X)
    (ω : RootIndexed.StepField Root α X) :
    population R 0 ω = fun _ => {[]} := by
  funext r
  simp [population]

theorem population_depth
    {Root α X : Type*} (R : Step.FiniteSelection α X)
    (ω : RootIndexed.StepField Root α X) {r : Root} {n : ℕ}
    {u : TreeNode α} (hu : u ∈ population R n ω r) :
    u.length = n :=
  ProbabilityTheory.BranchingRandomWalk.StepSelection.population_depth
    R (ω r) n u hu

theorem population_succ_parent
    {Root α X : Type*} (R : Step.FiniteSelection α X)
    (ω : RootIndexed.StepField Root α X) (r : Root) (n : ℕ)
    (q : TreeNode α) (hq : q ∈ population R (n + 1) ω r) :
    ∃ u ∈ population R n ω r, ∃ i,
      survive (ω r u) i ∧ q = u ++ [i] :=
  ProbabilityTheory.BranchingRandomWalk.StepSelection.population_succ_parent
    R (ω r) n q hq

/-- All root populations are observable at generation `n`. Both the root and
child-slot types may be arbitrary: product measurability is checked one root
at a time, and finite populations are observed through membership events. -/
theorem population_adapted
    {Root α X : Type*} [MeasurableSpace X]
    (R : Step.FiniteSelection α X) (hR : Measurable R.select) (n : ℕ) :
    Measurable[RootIndexed.stepFiltration
      (Root := Root) (α := α) (X := X) n]
      (population (Root := Root) R n) := by
  let _ : MeasurableSpace (RootIndexed.StepField Root α X) :=
    RootIndexed.stepFiltration (Root := Root) (α := α) (X := X) n
  apply Measurable.of_eval
  intro r
  exact (ProbabilityTheory.BranchingRandomWalk.StepSelection.population_adapted
    R hR n).comp
      (ProbabilityTheory.BranchingRandomWalk.RootIndexed.field_measurable
        (X := X) r n)

theorem population_card_le
    {Root α X : Type*} (R : Step.FiniteSelection α X) (N : ℕ)
    (hR : R.IsBoundedBy N) (ω : RootIndexed.StepField Root α X)
    (r : Root) (n : ℕ) :
    (population R n ω r).card ≤ N ^ n :=
  ProbabilityTheory.BranchingRandomWalk.StepSelection.population_card_le
    R N hR (ω r) n

/-! ## A single root as a labelled multi-root population -/

/-- Attach a root label to every particle in that root's selected
population. This is the representation consumed by multi-root cloud and
coupling interfaces. -/
noncomputable def labelledPopulation
    {Root α X : Type*} [DecidableEq (RootIndexed.TreeNode Root α)]
    (R : Step.FiniteSelection α X) (n : ℕ)
    (ω : RootIndexed.StepField Root α X) (r : Root) :
    Finset (RootIndexed.TreeNode Root α) :=
  (population R n ω r).map
    ⟨fun u => (r, u), fun _ _ h => congrArg Prod.snd h⟩

@[simp] theorem mem_labelledPopulation
    {Root α X : Type*} [DecidableEq (RootIndexed.TreeNode Root α)]
    (R : Step.FiniteSelection α X) (n : ℕ)
    (ω : RootIndexed.StepField Root α X) (r s : Root)
    (u : TreeNode α) :
    (s, u) ∈ labelledPopulation R n ω r ↔
      s = r ∧ u ∈ population R n ω r := by
  constructor
  · rw [labelledPopulation, Finset.mem_map]
    rintro ⟨v, hv, hp⟩
    have hs : s = r := (congrArg Prod.fst hp).symm
    have hvu : v = u := congrArg Prod.snd hp
    exact ⟨hs, hvu ▸ hv⟩
  · rintro ⟨rfl, hu⟩
    rw [labelledPopulation, Finset.mem_map]
    exact ⟨u, hu, rfl⟩

@[simp] theorem labelledPopulation_card
    {Root α X : Type*} [DecidableEq (RootIndexed.TreeNode Root α)]
    (R : Step.FiniteSelection α X) (n : ℕ)
    (ω : RootIndexed.StepField Root α X) (r : Root) :
    (labelledPopulation R n ω r).card = (population R n ω r).card := by
  simp [labelledPopulation]

@[simp] theorem labelledPopulation_zero
    {Root α X : Type*} [DecidableEq (RootIndexed.TreeNode Root α)]
    (R : Step.FiniteSelection α X)
    (ω : RootIndexed.StepField Root α X) (r : Root) :
    labelledPopulation R 0 ω r = {(r, [])} := by
  ext p
  rcases p with ⟨s, u⟩
  simp

/-- A labelled selected successor belongs to the abstract offspring-address
set generated by the labelled parent population and the selected slots. -/
theorem labelledPopulation_succ_subset
    {Root α X : Type*} [DecidableEq (RootIndexed.TreeNode Root α)]
    (R : Step.FiniteSelection α X) (n : ℕ)
    (ω : RootIndexed.StepField Root α X) (r : Root) :
    ↑(labelledPopulation R (n + 1) ω r) ⊆
      Combinatorics.Branching.Selection.Coupling.offspringAddressSet
        (↑(labelledPopulation R n ω r))
        (fun p => ↑(R (ω p.1 p.2))) := by
  rintro ⟨s, q⟩ hq
  have hmem := (mem_labelledPopulation R (n + 1) ω r s q).mp hq
  rcases hmem with ⟨hs, hqpop⟩
  subst s
  obtain ⟨u, hu, i, hi, rfl⟩ :=
    ProbabilityTheory.BranchingRandomWalk.StepSelection.population_succ_selectedParent
      R (ω r) n q hqpop
  apply Combinatorics.Branching.Selection.Coupling.mem_offspringAddressSet.mpr
  exact ⟨(r, u), by simpa using hu, i, by simpa using hi, rfl⟩

/-! ## A finite family of labelled roots -/

/-- Combine the selected descendants of a finite set of roots while retaining
their root labels.  This is the multi-root source population used by spatial
couplings; the ambient root type itself remains arbitrary. -/
noncomputable def labelledPopulationOn
    {Root α X : Type*} [DecidableEq (RootIndexed.TreeNode Root α)]
    (R : Step.FiniteSelection α X) (roots : Finset Root) (n : ℕ)
    (ω : RootIndexed.StepField Root α X) :
    Finset (RootIndexed.TreeNode Root α) :=
  roots.biUnion fun r => labelledPopulation R n ω r

@[simp] theorem mem_labelledPopulationOn
    {Root α X : Type*} [DecidableEq (RootIndexed.TreeNode Root α)]
    (R : Step.FiniteSelection α X) (roots : Finset Root) (n : ℕ)
    (ω : RootIndexed.StepField Root α X)
    (p : RootIndexed.TreeNode Root α) :
    p ∈ labelledPopulationOn R roots n ω ↔
      ∃ r ∈ roots, p.1 = r ∧ p.2 ∈ population R n ω r := by
  rw [labelledPopulationOn, Finset.mem_biUnion]
  constructor
  · rintro ⟨r, hr, hp⟩
    exact ⟨r, hr, (mem_labelledPopulation R n ω r p.1 p.2).mp hp⟩
  · rintro ⟨r, hr, hpRoot, hpPopulation⟩
    exact ⟨r, hr, (mem_labelledPopulation R n ω r p.1 p.2).mpr
      ⟨hpRoot, hpPopulation⟩⟩

@[simp] theorem labelledPopulationOn_zero
    {Root α X : Type*} [DecidableEq (RootIndexed.TreeNode Root α)]
    (R : Step.FiniteSelection α X) (roots : Finset Root)
    (ω : RootIndexed.StepField Root α X) :
    labelledPopulationOn R roots 0 ω =
      roots.map ⟨fun r => (r, []), fun _ _ h => congrArg Prod.fst h⟩ := by
  ext p
  rcases p with ⟨r, u⟩
  rw [mem_labelledPopulationOn, Finset.mem_map]
  constructor
  · rintro ⟨a, ha, hra, hu⟩
    have hu' : u = [] := by simpa using hu
    subst u
    have hra' : r = a := by simpa using hra
    subst a
    exact ⟨r, ha, rfl⟩
  · rintro ⟨a, ha, h⟩
    have har : a = r := congrArg Prod.fst h
    have hu : ([] : TreeNode α) = u := congrArg Prod.snd h
    subst r
    subst u
    exact ⟨a, ha, rfl, by simp⟩

/-- The successor multi-root population consists only of genuine children of
the preceding multi-root population through slots selected by `R`. -/
theorem labelledPopulationOn_succ_subset
    {Root α X : Type*} [DecidableEq (RootIndexed.TreeNode Root α)]
    (R : Step.FiniteSelection α X) (roots : Finset Root) (n : ℕ)
    (ω : RootIndexed.StepField Root α X) :
    ↑(labelledPopulationOn R roots (n + 1) ω) ⊆
      Combinatorics.Branching.Selection.Coupling.offspringAddressSet
        (↑(labelledPopulationOn R roots n ω))
        (fun p => ↑(R (ω p.1 p.2))) := by
  intro q hq
  obtain ⟨r, hr, hqRoot, hqPopulation⟩ :=
    (mem_labelledPopulationOn R roots (n + 1) ω q).mp hq
  have hq' : q ∈ labelledPopulation R (n + 1) ω r := by
    apply (mem_labelledPopulation R (n + 1) ω r q.1 q.2).mpr
    exact ⟨hqRoot, hqPopulation⟩
  have hchild := labelledPopulation_succ_subset R n ω r hq'
  apply Combinatorics.Branching.Selection.Coupling.mem_offspringAddressSet.mpr
  obtain ⟨p, hp, i, hi, hpi⟩ :=
    Combinatorics.Branching.Selection.Coupling.mem_offspringAddressSet.mp hchild
  exact ⟨p, (mem_labelledPopulationOn R roots n ω p).mpr
    ⟨r, hr, (mem_labelledPopulation R n ω r p.1 p.2).mp hp⟩,
    i, hi, hpi⟩

/-- Every particle in a finite-root labelled population lies at its indexed
generation. -/
theorem labelledPopulationOn_depth
    {Root α X : Type*} [DecidableEq (RootIndexed.TreeNode Root α)]
    (R : Step.FiniteSelection α X) (roots : Finset Root) (n : ℕ)
    (ω : RootIndexed.StepField Root α X)
    {p : RootIndexed.TreeNode Root α}
    (hp : p ∈ labelledPopulationOn R roots n ω) :
    p.2.length = n := by
  obtain ⟨r, _, _, hpPopulation⟩ :=
    (mem_labelledPopulationOn R roots n ω p).mp hp
  exact population_depth R ω hpPopulation

/-- A finite union of root-labelled step-selection populations is adapted to
the generation domain.  The ambient root and slot types remain arbitrary. -/
theorem labelledPopulationOn_adapted
    {Root α X : Type*} [MeasurableSpace X]
    [DecidableEq (RootIndexed.TreeNode Root α)]
    (R : Step.FiniteSelection α X) (hR : Measurable R.select)
    (roots : Finset Root) (n : ℕ) :
    Measurable[RootIndexed.stepFiltration
      (Root := Root) (α := α) (X := X) n]
      (labelledPopulationOn R roots n) := by
  let _ : MeasurableSpace (RootIndexed.StepField Root α X) :=
    RootIndexed.stepFiltration
      (Root := Root) (α := α) (X := X) n
  rw [measurable_finset_iff]
  intro p
  have hpopulation := population_adapted (Root := Root) R hR n
  have hmem : Measurable[RootIndexed.stepFiltration
      (Root := Root) (α := α) (X := X) n]
      (fun ω => p.2 ∈ population R n ω p.1) :=
    (measurable_finset_mem p.2).comp
      ((measurable_pi_apply p.1).comp hpopulation)
  by_cases hpRoot : p.1 ∈ roots
  · convert hmem using 1
    funext ω
    apply propext
    rw [mem_labelledPopulationOn]
    constructor
    · rintro ⟨r, hr, hpr, hpPop⟩
      simpa [hpr] using hpPop
    · intro hpPop
      exact ⟨p.1, hpRoot, rfl, hpPop⟩
  · have hempty : (fun ω => p ∈ labelledPopulationOn R roots n ω) =
        fun _ => False := by
      funext ω
      apply propext
      rw [mem_labelledPopulationOn]
      constructor
      · rintro ⟨r, hr, hpr, _⟩
        exact hpRoot (hpr ▸ hr)
      · simp
    rw [hempty]
    exact measurable_const

end StepSelection
end RootIndexed
end ProbabilityTheory.BranchingRandomWalk
