import Probability.BranchingRandomWalk.Step.Order
import Probability.BranchingRandomWalk.Genealogy.RootIndexed.Law
import Probability.BranchingRandomWalk.Step.PointMeasure
import Probability.BranchingRandomWalk.Step.OrderedSupport

/-!
# Independent multi-root fields generated by a random step

The source is the random variable `Ξ`. Its pushforward law is copied
independently at every address and root. Point measures and ordered support are
derived observations of those deterministic steps.
-/

open MeasureTheory

namespace ProbabilityTheory.BranchingRandomWalk

open Combinatorics.UlamHarris Combinatorics.Branching

theorem step_multiRoot_pointMeasure_marginal
    {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω)
    [IsProbabilityMeasure P] (Ξ : Step Ω ℕ ℝ)
    {m : ℕ} (i : Fin m) (u : 𝕍) :
    (finiteRootStepFieldLaw (Ξ.law P) m).map
        (fun ω : FiniteRootStepField m ℝ => stepPointMeasure (ω i u)) =
      P.map Ξ.pointMeasure := by
  rw [← Ξ.map_pointMeasure_law P]
  calc
    (finiteRootStepFieldLaw (Ξ.law P) m).map
        (fun ω : FiniteRootStepField m ℝ => stepPointMeasure (ω i u)) =
        ((finiteRootStepFieldLaw (Ξ.law P) m).map
          (fun ω : FiniteRootStepField m ℝ => ω i u)).map
            stepPointMeasure := by
          rw [Measure.map_map]
          · rfl
          · exact stepPointMeasure_measurable
          · exact (measurable_pi_apply u).comp (measurable_pi_apply i)
    _ = (Ξ.law P).map stepPointMeasure := by
      rw [finiteRootStepFieldLaw_coordinate_marginal]

theorem step_multiRoot_all_first_child
    {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω)
    [IsProbabilityMeasure P] (Ξ : Step Ω ℕ ℝ) (m : ℕ)
    (hordered : ∀ ω, Ξ ω ∈ orderedSteps)
    (hnonempty : ∀ ω, Ξ ω ∈ nonemptySupport) :
    ∀ᵐ field ∂finiteRootStepFieldLaw (Ξ.law P) m,
      ∀ i : Fin m, ∀ u : 𝕍, survive (field i u) 0 := by
  apply finiteRootStepFieldLaw_all_first_child
  · simpa using Ξ.law_ordered P
      (orderedSteps_measurable (ι := ℕ)) hordered
  · simpa using Ξ.law_nonempty P hnonempty

end ProbabilityTheory.BranchingRandomWalk
