module

public import Probability.BranchingRandomWalk.Step.Order
public import Probability.BranchingRandomWalk.Genealogy.RootIndexed.Law
public import Probability.BranchingRandomWalk.Step.PointMeasure
public import Probability.BranchingRandomWalk.Step.OrderedSupport

@[expose] public section

/-!
# Independent multi-root fields generated by a random step

The source is the random variable `S`. Its pushforward law is copied
independently at every address and root. Point measures and ordered support are
derived observations of those deterministic steps.
-/

open MeasureTheory

namespace ProbabilityTheory.BranchingRandomWalk

open Combinatorics.UlamHarris Combinatorics.Branching

theorem step_rootIndexed_pointMeasure_marginal
    {Root Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω)
    [IsProbabilityMeasure P] (S : Step Ω ℕ ℝ)
    (r : Root) (u : 𝕍) :
    (RootIndexed.stepFieldLaw (Root := Root) (S.indexedLaw P)).map
        (fun ω : RootIndexed.StepField Root ℕ ℝ =>
          stepPointMeasure (ω r u)) =
      S.branchingLaw P := by
  rw [← S.indexedLaw_map_pointMeasure P]
  calc
    (RootIndexed.stepFieldLaw (Root := Root) (S.indexedLaw P)).map
        (fun ω : RootIndexed.StepField Root ℕ ℝ =>
          stepPointMeasure (ω r u)) =
        ((RootIndexed.stepFieldLaw (Root := Root) (S.indexedLaw P)).map
          (fun ω : RootIndexed.StepField Root ℕ ℝ => ω r u)).map
            stepPointMeasure := by
          rw [Measure.map_map]
          · rfl
          · exact stepPointMeasure_measurable
          · exact (measurable_pi_apply u).comp (measurable_pi_apply r)
    _ = (S.indexedLaw P).map stepPointMeasure := by
      rw [RootIndexed.stepFieldLaw_coordinate_marginal]

theorem step_multiRoot_pointMeasure_marginal
    {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω)
    [IsProbabilityMeasure P] (S : Step Ω ℕ ℝ)
    {m : ℕ} (i : Fin m) (u : 𝕍) :
    (finiteRootStepFieldLaw (S.indexedLaw P) m).map
        (fun ω : FiniteRootStepField m ℕ ℝ => stepPointMeasure (ω i u)) =
      S.branchingLaw P := by
  exact step_rootIndexed_pointMeasure_marginal P S i u

theorem step_rootIndexed_all_first_child
    {Root Ω : Type*} [Countable Root] [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P] (S : Step Ω ℕ ℝ)
    (hordered : ∀ ω, S ω ∈ orderedSteps)
    (hnonempty : ∀ ω, S ω ∈ nonemptySupport) :
    ∀ᵐ field ∂RootIndexed.stepFieldLaw (Root := Root) (S.indexedLaw P),
      ∀ r : Root, ∀ u : 𝕍, survive (field r u) 0 := by
  have horderedLaw : S.indexedLaw P orderedSteps = 1 := by
    simpa using S.indexedLaw_ordered P
      (orderedSteps_measurable (ι := ℕ)) hordered
  have hnonemptyLaw : S.indexedLaw P nonemptySupport = 1 := by
    simpa using S.indexedLaw_nonempty P hnonempty
  filter_upwards
    [RootIndexed.stepFieldLaw_ae_all_of_measure_one
      (Root := Root) orderedSteps_measurable (S.indexedLaw P) horderedLaw,
     RootIndexed.stepFieldLaw_ae_all_of_measure_one
      (Root := Root) nonemptySupport_measurable (S.indexedLaw P) hnonemptyLaw]
      with field hord hne
  intro r u
  obtain ⟨j, hj⟩ := hne r u
  exact orderedSteps_survive_of_le (field r u) (hord r u) (Nat.zero_le j) hj

theorem step_multiRoot_all_first_child
    {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω)
    [IsProbabilityMeasure P] (S : Step Ω ℕ ℝ) (m : ℕ)
    (hordered : ∀ ω, S ω ∈ orderedSteps)
    (hnonempty : ∀ ω, S ω ∈ nonemptySupport) :
    ∀ᵐ field ∂finiteRootStepFieldLaw (S.indexedLaw P) m,
      ∀ i : Fin m, ∀ u : 𝕍, survive (field i u) 0 := by
  exact step_rootIndexed_all_first_child
    (Root := Fin m) P S hordered hnonempty

end ProbabilityTheory.BranchingRandomWalk
