import Probability.Process.RandomWalk.SmallDeviation.Mogulskii.Rate.EndpointWindowSelection

#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.centralEndpointBandTargetMass_lower
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.eventually_lowerBound_le_centralEndpointBandTargetMass_of_diffusiveRatio
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.eventually_forall_sevenCentralEndpointWindowTargetMass_lower
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.ofReal_centralEndpointWindowTargetMassSum_le_endpointWindowBlockEvent
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.eventually_forall_sevenRademacherEndpointWindowBlockEvent_ge_of_diffusiveRatio
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.eventually_forall_sevenRademacherNormalizedEndpointWindowProbability_ge_of_diffusiveRatio
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.eventually_forall_integer_sevenRademacherNormalizedEndpointWindowProbability_ge_of_diffusiveRatio
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.eventually_forall_sevenCenteredUnitVarianceEndpointWindowProbability_ge_of_spectralBands
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.iidSequenceLaw_map_div_endpointWindowBlockEvent_eq_normalizedAlong
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.one_div_constant_mul_log_toReal_le_liminf_scaledLog_horizontalTubeProbability_of_endpointWindowBlocks
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.one_div_constant_mul_log_toReal_le_liminf_scaledLog_horizontalTubeProbability_of_spectralEndpointWindows
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.neg_half_pi_sq_le_liminf_scaledLog_horizontalTubeProbability_of_floorEndpointWindows
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.tendsto_scaledLog_horizontalTubeProbability_of_centeredUnitSecondMoment
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.returnKernel_apply_univ_lower_of_endpointWindowEvents
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.horizontalTubeProbability_ge_pow_endpointWindows
