import Combinatorics.UlamHarris.MarkedTree.Forget
import Combinatorics.UlamHarris.RootIndexedMarkedTree.Measurability
import Combinatorics.UlamHarris.RootIndexedMarkedTree.Singleton
import Combinatorics.UlamHarris.RootIndexedTree.Singleton

/-!
# Forgetting the marks of a root-indexed marked tree

`RootIndexedMarkedTree Root α X` is one marked tree per initial ancestor, and
`RootIndexedTree Root α` is one tree per initial ancestor. Forgetting the marks
at every root, `forgetMark`, is the connection from the multi-root marked object
to the multi-root tree object; it is the root-indexed case of
`MarkedTree.forgetMark`, and it commutes with reindexing the roots and with the
identification of the one-root case.

The map is measurable for the product σ-algebras on both sides: each coordinate
`M ↦ (M r).tree` is measurable, and the σ-algebra on a root-indexed tree is
generated by those coordinates.
-/

namespace Combinatorics

namespace UlamHarris

namespace RootIndexedMarkedTree

variable {Root NewRoot α X : Type*} [LT α]

/-- Forget the marks of every tree of a root-indexed marked family, keeping the
family of trees. -/
def forgetMark (M : RootIndexedMarkedTree Root α X) : RootIndexedTree Root α :=
  fun r => (M r).forgetMark

@[simp] theorem forgetMark_apply (M : RootIndexedMarkedTree Root α X) (r : Root) :
    M.forgetMark r = (M r).forgetMark := rfl

/-- Forgetting the marks of a family is forgetting the marks of each tree, so it
is the realized-tree map `tree` that the family already carries. -/
@[simp] theorem forgetMark_eq_tree (M : RootIndexedMarkedTree Root α X) :
    M.forgetMark = M.tree := rfl

/-- Forgetting the marks commutes with reindexing the initial ancestors. -/
@[simp] theorem forgetMark_reindex (f : NewRoot → Root)
    (M : RootIndexedMarkedTree Root α X) :
    (M.reindex f).forgetMark = M.forgetMark.reindex f := rfl

section Measurable

variable [MeasurableSpace X]

/-- Forgetting the marks of a root-indexed family is measurable. -/
theorem measurable_forgetMark :
    Measurable (forgetMark (Root := Root) (α := α) (X := X)) := by
  rw [measurable_pi_iff]
  intro r
  exact UlamHarris.measurable_tree.comp (measurable_apply r)

end Measurable

section Unique

variable [Unique Root]

/-- The forgetful map of families is the forgetful map of marked trees under the
identification of the one-root case. -/
theorem forgetMark_equivOfUnique (M : RootIndexedMarkedTree Root α X) :
    RootIndexedTree.equivOfUnique (forgetMark M) =
      MarkedTree.forgetMark (equivOfUnique M) := rfl

end Unique

end RootIndexedMarkedTree

end UlamHarris

end Combinatorics
