module

public import MeasureTheory.Measure.FiniteOnFamily
public import Mathlib.MeasureTheory.Measure.GiryMonad
public import Mathlib.MeasureTheory.Measure.Typeclasses.Finite
public import MeasureTheory.Measure.IntegerValued

public section

/-!
# Abstract point processes

`PointProcess Ω E 𝒜` is the abstract object: a measurable map from `Ω` to the
space of counting measures on a measurable space `E` that are finite on every
member of a family `𝒜` of sets. The measurable space on `Measure E` is
Mathlib's evaluation sigma-algebra (the Giry-monad measurable space), so
measurability is exactly the usual point-process measurability generated by
the evaluations `ν ↦ ν s`.

The family is a parameter rather than a fixed condition: `compactFamily` gives
the standard locally-finite point process, while `leftRayFamily` on `ℝ` gives
the paper's left-half-line condition. The thesis never hardcodes either one.

`PointProcess` is the probability-theoretic object, so its abstract core lives
under `Probability/PointProcess/`; compare Mathlib's `Probability/Kernel/`.
The corresponding random `Step` adapter belongs to the branching random walk
and lives in `Probability/BranchingRandomWalk/Step/PointProcess.lean`. This
file keeps only the measure-theoretic core, so nothing below it depends on
slot order, roots, trees, or a selection rule.
-/

open MeasureTheory
open scoped ENNReal

namespace ProbabilityTheory

/-- An abstract point process: a measurable random counting measure on `E`
that is finite on every member of the family `𝒜`. The zero measure is
allowed. -/
structure PointProcess (Ω E : Type*) [MeasurableSpace Ω] [MeasurableSpace E]
    (𝒜 : Set (Set E)) where
  toMeasure : Ω → Measure E
  measurable_toMeasure : Measurable toMeasure
  counting : ∀ ω, Measure.IsIntegerValued (toMeasure ω)
  finiteOn : ∀ ω, IsFiniteOnFamily (toMeasure ω) 𝒜

instance {Ω E : Type*} [MeasurableSpace Ω] [MeasurableSpace E]
    (𝒜 : Set (Set E)) :
    CoeFun (PointProcess Ω E 𝒜) (fun _ => Ω → Measure E) :=
  ⟨PointProcess.toMeasure⟩

/-- The zero point process exists at the abstract level and preserves the
samplewise absence of children. -/
def emptyPointProcess (Ω E : Type*) [MeasurableSpace Ω] [MeasurableSpace E]
    (𝒜 : Set (Set E)) : PointProcess Ω E 𝒜 where
  toMeasure := fun _ => 0
  measurable_toMeasure := measurable_const
  counting := fun _ => Measure.isIntegerValued_zero
  finiteOn := by
    intro ω
    exact IsFiniteOnFamily.of_finiteMeasure

end ProbabilityTheory
