import Combinatorics.UlamHarris.Basic
import Mathlib.MeasureTheory.Constructions.Pi
import Mathlib.Probability.Process.Filtration

/-!
# The generation filtration on a pre-sampled mark field

`generationSpace n` is the σ-algebra generated by all marks at addresses of
depth strictly below `n`, and `generationFiltration` turns these spaces into a
filtration of the full product space. The file proves that the mark at depth
`d` is revealed at generation `d + 1`, that the current frontier is a
measurable observation, and the two random-index measurability steps used by
the restart and reserve arguments: `selected_mark_measurable` for an address
chosen from generation-`n` information, and `causal_lineage_adapted` for an
unconditionally pre-defined lineage that extends one generation at a time.
The adapted-state corollary `frontier_causal_state_adapted` is proved in
`Probability/BranchingRandomWalk/Timing/Frontier.lean`, since it needs the restart lemmas.
-/

open MeasureTheory

namespace ProbabilityTheory.BranchingRandomWalk

open UlamHarris MeasureTheory



variable {M : Type*} [MeasurableSpace M]

variable {α : Type*}

/-- Node addresses carry the discrete σ-algebra. -/
instance instMeasurableSpaceTreeNode (α : Type*) : MeasurableSpace (TreeNode α) := ⊤

/-- Information revealed by generation `n`: all marks at addresses of
depth strictly below `n`. -/
@[instance_reducible] def generationSpace (n : ℕ) :
    MeasurableSpace (Mark α M) :=
  MeasurableSpace.generateFrom
    {s | ∃ u : TreeNode α, u.length < n ∧
      ∃ t : Set M, MeasurableSet t ∧
        s = {ω : Mark α M | ω u ∈ t}}

/-- Before the root reproduces, no child mark is revealed. -/
theorem generationSpace_zero :
    generationSpace (α := α) (M := M) 0 = ⊥ := by
  unfold generationSpace
  have hgen :
      {s : Set (Mark α M) | ∃ u : TreeNode α, u.length < 0 ∧
        ∃ t : Set M, MeasurableSet t ∧
          s = {ω : Mark α M | ω u ∈ t}} = ∅ := by
    ext s
    simp
  rw [hgen, MeasurableSpace.generateFrom_empty]

/-- The generation information forms a filtration of the full product space. -/
def generationFiltration :
    Filtration ℕ (inferInstance : MeasurableSpace (Mark α M)) where
  seq := generationSpace
  mono' := by
    intro i j hij
    apply MeasurableSpace.generateFrom_mono
    rintro s ⟨u, hu, t, ht, rfl⟩
    exact ⟨u, lt_of_lt_of_le hu hij, t, ht, rfl⟩
  le' := by
    intro n
    apply MeasurableSpace.generateFrom_le
    rintro s ⟨u, hu, t, ht, rfl⟩
    exact (measurable_pi_apply u) ht

/-- A node's mark is observable from the next generation onward. -/
theorem mark_measurable_of_depth_lt (u : TreeNode α) (n : ℕ)
    (hu : u.length < n) :
    Measurable[generationFiltration (M := M) n]
      (fun ω : Mark α M => ω u) := by
  intro t ht
  exact MeasurableSpace.measurableSet_generateFrom ⟨u, hu, t, ht, rfl⟩

theorem mark_measurable_next (u : TreeNode α) :
    Measurable[generationFiltration (M := M) (u.length + 1)]
      (fun ω : Mark α M => ω u) :=
  mark_measurable_of_depth_lt u _ (Nat.lt_succ_self _)

/-- Only marks of parents in generation `n` are supplied to a generation
update. All deeper marks are hidden behind a dummy value. -/
def frontierMarks [Inhabited M] (n : ℕ)
    (ω : Mark α M) : Mark α M :=
  fun u => if u.length = n then ω u else default

/-- The entire current frontier, regarded as a product-valued observation, is
measurable when generation `n + 1` has been exposed. -/
theorem frontierMarks_measurable [Inhabited M] (n : ℕ) :
    Measurable[generationFiltration (α := α) (M := M) (n + 1)]
      (frontierMarks (α := α) (M := M) n) := by
  apply (@measurable_pi_iff (Mark α M) (TreeNode α) (fun _ => M)
    (generationFiltration (α := α) (M := M) (n + 1))
    (fun _ => inferInstance) (frontierMarks (α := α) (M := M) n)).2
  intro u
  by_cases hu : u.length = n
  · simpa [frontierMarks, hu] using
      (mark_measurable_of_depth_lt u (n + 1)
        (by rw [hu]; exact Nat.lt_succ_self n))
  · simp [frontierMarks, hu]

/-- A node selected using generation-`n` information has an observable mark,
provided its address lies among nodes whose marks have already been revealed.
This is the random-index measurability step used for reserve lineages. -/
theorem selected_mark_measurable [Countable α] (n : ℕ)
    (chosen : Mark α M → TreeNode α)
    (hchosen : Measurable[generationFiltration (M := M) n] chosen)
    (hdepth : ∀ ω, (chosen ω).length < n) :
    Measurable[generationFiltration (M := M) n]
      (fun ω : Mark α M => ω (chosen ω)) := by
  intro t ht
  have hset :
      {ω : Mark α M | ω (chosen ω) ∈ t} =
        ⋃ u : TreeNode α,
          {ω : Mark α M | chosen ω = u} ∩
            {ω : Mark α M | ω u ∈ t} := by
    ext ω
    simp only [Set.mem_ofPred_eq, Set.mem_iUnion, Set.mem_inter_iff]
    constructor
    · intro h
      exact ⟨chosen ω, rfl, h⟩
    · rintro ⟨u, hu, hmark⟩
      simpa [hu] using hmark
  change MeasurableSet[generationFiltration (M := M) n]
    {ω : Mark α M | ω (chosen ω) ∈ t}
  rw [hset]
  apply MeasurableSet.iUnion
  intro u
  by_cases hu : u.length < n
  · exact (hchosen (measurableSet_singleton u)).inter
      ((mark_measurable_of_depth_lt u n hu) ht)
  · have hempty : {ω : Mark α M | chosen ω = u} = ∅ := by
      ext ω
      simp only [Set.mem_ofPred_eq, Set.mem_empty_iff_false, iff_false]
      intro heq
      exact hu (heq ▸ hdepth ω)
    simp [hempty]

/-- An unconditionally pre-defined lineage that extends one generation at a
time from its own currently revealed mark is adapted. The premise about
length rules out a retrospectively chosen ancestor. -/
theorem causal_lineage_adapted [Countable α]
    (path : ℕ → Mark α M → TreeNode α)
    (step : TreeNode α × M → TreeNode α)
    (hstep : Measurable step)
    (hroot : Measurable[generationFiltration (M := M) 0] (path 0))
    (hdepth : ∀ n ω, (path n ω).length = n)
    (hrec : ∀ n ω, path (n + 1) ω =
      step (path n ω, ω (path n ω))) :
    ∀ n, Measurable[generationFiltration (M := M) n] (path n) := by
  intro n
  induction n with
  | zero => exact hroot
  | succ n ih =>
      have hold : Measurable[generationFiltration (M := M) (n + 1)]
          (path n) :=
        ih.mono (generationFiltration (M := M) |>.mono (Nat.le_succ n)) le_rfl
      have hmark : Measurable[generationFiltration (M := M) (n + 1)]
          (fun ω : Mark α M => ω (path n ω)) :=
        selected_mark_measurable (n + 1) (path n) hold
          (fun ω => by rw [hdepth n ω]; exact Nat.lt_succ_self n)
      have hpair : Measurable[generationFiltration (M := M) (n + 1)]
          (fun ω : Mark α M => (path n ω, ω (path n ω))) :=
        hold.prodMk hmark
      convert hstep.comp hpair using 1
      funext ω
      exact hrec n ω

end ProbabilityTheory.BranchingRandomWalk
