module

public import Combinatorics.UlamHarris.Basic
public import Mathlib.MeasureTheory.MeasurableSpace.Constructions
public import Mathlib.MeasureTheory.MeasurableSpace.Instances

/-!
# Deterministic Ulam--Harris trees

`Tree α` is a deterministic rooted tree of addresses `TreeNode α`, carrying
the root, parent, and ordered-sibling axioms, so a bare `Set (List α)` is only
its carrier. The structure is not assumed to be finite, countable, or locally
finite; `Tree ℕ` is the Ulam--Harris case in standard notation.

`Tree.siblingRel` is the address-level parent relation, "one further child
label", and it is the single parent relation reused by the graph projections in
`Tree/Graph/`. It is a different relation from `BranchingWalk.siblingRel`, which
orders the survive slots of one branching step.

The measurable space on `Tree α` is the one induced by the carrier: it is the
smallest σ-algebra making `T ↦ T.carrier` measurable, where `Set (List α)`
carries mathlib's coordinate σ-algebra. Equivalently it is generated by the
sets `{T | u ∈ T.carrier}` for `u : List α`, so a random tree is measurable
exactly when membership of every address is measurable. This is the
σ-algebra under which the realized tree of a branching-step field is a random
variable.
-/

@[expose] public section

namespace Combinatorics

namespace UlamHarris

/-- A rooted tree of addresses. The carrier contains the root, is parent
closed, and for ordered child labels contains every smaller sibling below a
survive child. `Set (List α)` is only the underlying carrier of this
structure. -/
structure Tree (α : Type*) [LT α] where
  carrier : Set (List α)
  root_mem : [] ∈ carrier
  parent_closed : ∀ {u v : List α}, u ++ v ∈ carrier → u ∈ carrier
  sibling_closed : ∀ {u : List α} {i j : α},
    u ++ [j] ∈ carrier → i < j → u ++ [i] ∈ carrier

/-- Two trees are equal as soon as their carriers are equal: the remaining
fields of `Tree` are propositions and hence proof irrelevant. -/
@[ext]
theorem Tree.ext {α : Type*} [LT α] {T T' : Tree α}
    (h : T.carrier = T'.carrier) : T = T' := by
  cases T
  cases T'
  simp only at h
  cases h
  rfl

@[simp] theorem Tree.root_mem' {α : Type*} [LT α]
    (T : Tree α) :
    [] ∈ T.carrier := T.root_mem

theorem Tree.mem_parent {α : Type*} [LT α] (T : Tree α)
    {u v : List α} (h : u ++ v ∈ T.carrier) : u ∈ T.carrier :=
  T.parent_closed h

/-- The parent relation on addresses: `siblingRel a b` says that `b` is a child
of `a`, obtained by appending one further label to the address `a`.

This is an address-level relation, independent of any particular tree. It is
the single parent relation reused by every graph projection of a tree, so the
digraph, quiver, and simple-graph views of a tree have one definition to share.

It is *not* `BranchingWalk.siblingRel`: that one is a condition on a single
branching step, saying that the slots survive in the step are listed in the
prescribed order. The two relate the same tree picture at different levels, the
slot order of one node versus the addresses of a node and its child. -/
def Tree.siblingRel {α : Type*} (a b : List α) : Prop :=
  ∃ i : α, b = a ++ [i]

@[simp]
theorem Tree.siblingRel_def {α : Type*} {a b : List α} :
    Tree.siblingRel a b ↔ ∃ i : α, b = a ++ [i] :=
  Iff.rfl

/-- A child address is strictly longer than its parent. -/
theorem Tree.siblingRel_length_lt {α : Type*} {a b : List α}
    (h : Tree.siblingRel a b) : a.length < b.length := by
  rcases h with ⟨i, rfl⟩
  simp [List.length_append]

/-- Every address has at most one parent: the parent relation is left unique. -/
theorem Tree.siblingRel_left_unique {α : Type*} {a b c : List α}
    (hab : Tree.siblingRel a c) (hbc : Tree.siblingRel b c) : a = b := by
  rcases hab with ⟨i, rfl⟩
  rcases hbc with ⟨j, hj⟩
  have h := congrArg List.dropLast hj
  simpa using h

/-- No address is its own parent. -/
theorem Tree.siblingRel_irrefl {α : Type*} (a : List α) : ¬ Tree.siblingRel a a :=
  fun h => absurd (Tree.siblingRel_length_lt h) (lt_irrefl _)

/-- The measurable space on trees: the σ-algebra induced by the carrier. -/
instance instMeasurableSpaceTree {α : Type*} [LT α] :
    MeasurableSpace (Tree α) :=
  MeasurableSpace.comap (fun T : Tree α => T.carrier) inferInstance

theorem measurable_carrier {α : Type*} [LT α] :
    Measurable (fun T : Tree α => T.carrier) :=
  Measurable.of_comap_le le_rfl

/-- Membership of a fixed address is measurable for the tree σ-algebra. -/
theorem measurableSet_carrier {α : Type*} [LT α] (u : List α) :
    MeasurableSet {T : Tree α | u ∈ T.carrier} :=
  MeasurableSet.preimage (measurableSet_mem u) measurable_carrier

namespace RootIndexed

/-! ### Families indexed by several initial ancestors

The root-indexed tree is an indexed family of ordinary trees.  Its definition
and elementary carrier predicates live beside the single-root definition;
there is no second source hierarchy for the same object.
-/

/-- A deterministic tree for every initial ancestor. -/
abbrev Tree (Root α : Type*) [LT α] := Root → UlamHarris.Tree α

namespace Tree

variable {Root NewRoot α : Type*} [LT α]

/-- Every initial ancestor carries a realized root. -/
theorem root_mem (T : RootIndexed.Tree Root α) (r : Root) :
    [] ∈ (T r).carrier :=
  (T r).root_mem

/-- Parent closure holds separately in every root-indexed tree. -/
theorem mem_parent (T : RootIndexed.Tree Root α) (r : Root)
    {u v : List α} (h : u ++ v ∈ (T r).carrier) : u ∈ (T r).carrier :=
  UlamHarris.Tree.mem_parent (T r) h

/-- Sibling closure holds separately in every root-indexed tree. -/
theorem sibling_closed (T : RootIndexed.Tree Root α) (r : Root)
    {u : List α} {i j : α} (h : u ++ [j] ∈ (T r).carrier) (hij : i < j) :
    u ++ [i] ∈ (T r).carrier :=
  (T r).sibling_closed h hij

@[ext (iff := false)]
theorem ext {S T : RootIndexed.Tree Root α} (h : ∀ r, S r = T r) : S = T := by
  funext r
  exact h r

/-- Reindex a family of trees along a map of initial ancestors. -/
def reindex (f : NewRoot → Root) (T : RootIndexed.Tree Root α) :
    RootIndexed.Tree NewRoot α :=
  fun r => T (f r)

@[simp]
theorem reindex_apply (f : NewRoot → Root) (T : RootIndexed.Tree Root α)
    (r : NewRoot) : T.reindex f r = T (f r) := rfl

@[simp]
theorem reindex_id (T : RootIndexed.Tree Root α) : T.reindex id = T := rfl

@[simp]
theorem reindex_comp (f : NewRoot → Root) {NewerRoot : Type*}
    (g : NewerRoot → NewRoot) (T : RootIndexed.Tree Root α) :
    (T.reindex f).reindex g = T.reindex (f ∘ g) := rfl

abbrev FiniteRootTree (m : ℕ) (α : Type*) [LT α] := RootIndexed.Tree (Fin m) α

abbrev CountableRootTree (α : Type*) [LT α] := RootIndexed.Tree ℕ α

theorem finiteRootTree_ext {m : ℕ} {S T : FiniteRootTree m α}
    (h : ∀ r, S r = T r) : S = T := ext h

end Tree

namespace Tree

variable {Root α : Type*} [LT α]

/-- The product σ-algebra of the single-tree σ-algebras. -/
theorem measurableSpace_eq_iSup :
    (inferInstance : MeasurableSpace (RootIndexed.Tree Root α)) =
      ⨆ r : Root,
        MeasurableSpace.comap
          (fun T : RootIndexed.Tree Root α => T r) inferInstance :=
  rfl

/-- Each initial ancestor coordinate is measurable. -/
theorem measurable_apply (r : Root) :
    Measurable (fun T : RootIndexed.Tree Root α => T r) :=
  measurable_pi_apply r

/-- Membership of a fixed address in a fixed root's tree is measurable. -/
theorem measurableSet_carrier (r : Root) (u : List α) :
    MeasurableSet {T : RootIndexed.Tree Root α | u ∈ (T r).carrier} :=
  MeasurableSet.preimage (UlamHarris.measurableSet_carrier (α := α) u)
    (measurable_apply r)

/-- A map into root-indexed trees is measurable when all root/address
membership coordinates are measurable. -/
theorem measurable_iff_forall_mem_carrier {β : Type*} [MeasurableSpace β]
    (f : β → RootIndexed.Tree Root α) :
    Measurable f ↔ ∀ r u, MeasurableSet {b | u ∈ (f b r).carrier} := by
  constructor
  · intro hf r u
    exact (measurableSet_carrier r u).preimage hf
  · intro h
    rw [measurable_pi_iff]
    intro r
    rw [measurable_comap_iff]
    rw [measurable_set_iff]
    intro u
    exact (measurableSet_setOfPred).1 (h r u)

end Tree

end RootIndexed

end UlamHarris

end Combinatorics

end
