import Combinatorics.UlamHarris.Basic
import Mathlib.MeasureTheory.MeasurableSpace.Constructions

/-!
# Deterministic Ulam--Harris trees

`Tree α` is a deterministic rooted tree of addresses `TreeNode α`, carrying
the root, parent, and ordered-sibling axioms, so a bare `Set (List α)` is only
its carrier. The structure is not assumed to be finite, countable, or locally
finite; `Tree ℕ` is the Ulam--Harris case in standard notation.

`Tree.siblingRel` is the address-level parent relation, "one further child
label", and it is the single parent relation reused by the graph projections in
`Tree/Graph/`. It is a different relation from `BranchingWalk.siblingRel`, which
orders the survive slots of one branching step.

The measurable space on `Tree α` is the one induced by the carrier: it is the
smallest σ-algebra making `T ↦ T.carrier` measurable, where `Set (List α)`
carries mathlib's coordinate σ-algebra. Equivalently it is generated by the
sets `{T | u ∈ T.carrier}` for `u : List α`, so a random tree is measurable
exactly when membership of every address is measurable. This is the
σ-algebra under which the realized tree of a branching-step field is a random
variable.
-/

namespace Combinatorics

namespace UlamHarris

/-- A rooted tree of addresses. The carrier contains the root, is parent
closed, and for ordered child labels contains every smaller sibling below a
survive child. `Set (List α)` is only the underlying carrier of this
structure. -/
structure Tree (α : Type*) [LT α] where
  carrier : Set (List α)
  root_mem : [] ∈ carrier
  parent_closed : ∀ {u v : List α}, u ++ v ∈ carrier → u ∈ carrier
  sibling_closed : ∀ {u : List α} {i j : α},
    u ++ [j] ∈ carrier → i < j → u ++ [i] ∈ carrier

/-- Two trees are equal as soon as their carriers are equal: the remaining
fields of `Tree` are propositions and hence proof irrelevant. -/
@[ext]
theorem Tree.ext {α : Type*} [LT α] {T T' : Tree α}
    (h : T.carrier = T'.carrier) : T = T' := by
  cases T
  cases T'
  simp only at h
  cases h
  rfl

@[simp] theorem Tree.root_mem' {α : Type*} [LT α]
    (T : Tree α) :
    [] ∈ T.carrier := T.root_mem

theorem Tree.mem_parent {α : Type*} [LT α] (T : Tree α)
    {u v : List α} (h : u ++ v ∈ T.carrier) : u ∈ T.carrier :=
  T.parent_closed h

/-- The parent relation on addresses: `siblingRel a b` says that `b` is a child
of `a`, obtained by appending one further label to the address `a`.

This is an address-level relation, independent of any particular tree. It is
the single parent relation reused by every graph projection of a tree, so the
digraph, quiver, and simple-graph views of a tree have one definition to share.

It is *not* `BranchingWalk.siblingRel`: that one is a condition on a single
branching step, saying that the slots survive in the step are listed in the
prescribed order. The two relate the same tree picture at different levels, the
slot order of one node versus the addresses of a node and its child. -/
def Tree.siblingRel {α : Type*} (a b : List α) : Prop :=
  ∃ i : α, b = a ++ [i]

@[simp]
theorem Tree.siblingRel_def {α : Type*} {a b : List α} :
    Tree.siblingRel a b ↔ ∃ i : α, b = a ++ [i] :=
  Iff.rfl

/-- A child address is strictly longer than its parent. -/
theorem Tree.siblingRel_length_lt {α : Type*} {a b : List α}
    (h : Tree.siblingRel a b) : a.length < b.length := by
  rcases h with ⟨i, rfl⟩
  simp [List.length_append]

/-- Every address has at most one parent: the parent relation is left unique. -/
theorem Tree.siblingRel_left_unique {α : Type*} {a b c : List α}
    (hab : Tree.siblingRel a c) (hbc : Tree.siblingRel b c) : a = b := by
  rcases hab with ⟨i, rfl⟩
  rcases hbc with ⟨j, hj⟩
  have h := congrArg List.dropLast hj
  simpa using h

/-- No address is its own parent. -/
theorem Tree.siblingRel_irrefl {α : Type*} (a : List α) : ¬ Tree.siblingRel a a :=
  fun h => absurd (Tree.siblingRel_length_lt h) (lt_irrefl _)

/-- The measurable space on trees: the σ-algebra induced by the carrier. -/
instance instMeasurableSpaceTree {α : Type*} [LT α] :
    MeasurableSpace (Tree α) :=
  MeasurableSpace.comap (fun T : Tree α => T.carrier) inferInstance

theorem measurable_carrier {α : Type*} [LT α] :
    Measurable (fun T : Tree α => T.carrier) :=
  Measurable.of_comap_le le_rfl

/-- Membership of a fixed address is measurable for the tree σ-algebra. -/
theorem measurableSet_carrier {α : Type*} [LT α] (u : List α) :
    MeasurableSet {T : Tree α | u ∈ T.carrier} :=
  MeasurableSet.preimage (measurableSet_mem u) measurable_carrier

end UlamHarris

end Combinatorics
