module

public import Combinatorics.UlamHarris.Tree.Defs
public import Mathlib.MeasureTheory.MeasurableSpace.Constructions
public import Mathlib.MeasureTheory.MeasurableSpace.Instances

/-!
# Measurable spaces on Ulam--Harris trees

The measurable space on `Tree α` is induced by the carrier: it is the smallest
σ-algebra making `T ↦ T.carrier` measurable. Equivalently, it is generated by
the membership events `{T | u ∈ T.carrier}` for addresses `u`. A random tree
is measurable exactly when membership of every address is measurable.
-/

@[expose] public section

namespace Combinatorics

namespace UlamHarris

/-- The measurable space on trees, induced by the carrier map. -/
instance instMeasurableSpaceTree {α : Type*} [LT α] :
    MeasurableSpace (Tree α) :=
  MeasurableSpace.comap (fun T : Tree α => T.carrier) inferInstance

theorem measurable_carrier {α : Type*} [LT α] :
    Measurable (fun T : Tree α => T.carrier) :=
  Measurable.of_comap_le le_rfl

/-- Membership of a fixed address is measurable for the tree σ-algebra. -/
theorem measurableSet_carrier {α : Type*} [LT α] (u : List α) :
    MeasurableSet {T : Tree α | u ∈ T.carrier} :=
  MeasurableSet.preimage (measurableSet_mem u) measurable_carrier

namespace RootIndexed.Tree

variable {Root α : Type*} [LT α]

/-- The product σ-algebra of the single-tree σ-algebras. -/
theorem measurableSpace_eq_iSup :
    (inferInstance : MeasurableSpace (RootIndexed.Tree Root α)) =
      ⨆ r : Root,
        MeasurableSpace.comap
          (fun T : RootIndexed.Tree Root α => T r) inferInstance :=
  rfl

/-- Each initial ancestor coordinate is measurable. -/
theorem measurable_apply (r : Root) :
    Measurable (fun T : RootIndexed.Tree Root α => T r) :=
  measurable_pi_apply r

/-- Membership of a fixed address in a fixed root's tree is measurable. -/
theorem measurableSet_carrier (r : Root) (u : List α) :
    MeasurableSet {T : RootIndexed.Tree Root α | u ∈ (T r).carrier} :=
  MeasurableSet.preimage (UlamHarris.measurableSet_carrier (α := α) u)
    (measurable_apply r)

/-- A map into root-indexed trees is measurable when all root/address
membership coordinates are measurable. -/
theorem measurable_iff_forall_mem_carrier {β : Type*} [MeasurableSpace β]
    (f : β → RootIndexed.Tree Root α) :
    Measurable f ↔ ∀ r u, MeasurableSet {b | u ∈ (f b r).carrier} := by
  constructor
  · intro hf r u
    exact (measurableSet_carrier r u).preimage hf
  · intro h
    rw [measurable_pi_iff]
    intro r
    rw [measurable_comap_iff]
    rw [measurable_set_iff]
    intro u
    exact (measurableSet_setOfPred).1 (h r u)

end RootIndexed.Tree

end UlamHarris

end Combinatorics

end
