module

public import Combinatorics.UlamHarris.Tree.Defs
public import Combinatorics.UlamHarris.Tree.Truncation
public import Mathlib.Topology.Bases
public import Mathlib.Topology.Constructions
public import Mathlib.Topology.Order
public import Mathlib.Topology.Separation.Basic

/-!
# Topologies on Ulam--Harris trees

The default topology on `Tree α` is the pointwise (initial) topology of the
membership evaluations `T ↦ (u ∈ T.carrier)`, with the Sierpinski topology on
`Prop`. It is exposed under the name `treePointwiseTopology` and registered as
the global instance `instTopologicalSpaceTree`.

The truncation topology generated by the balls
`{S | S.truncate n = T.truncate n}` is a separate, finer topology. It is the
topology induced by the tree metric introduced in `Tree/Metric.lean`; it is not
registered as an instance, so importing this file does not change the default
topology of `Tree α`.

The Borel comparison of these topologies with the cylinder σ-algebra lives in
`Tree/Borel.lean`.
-/

@[expose] public section

open scoped Topology
open TopologicalSpace

set_option linter.style.haveILetI false

namespace Combinatorics

namespace UlamHarris

namespace Tree

variable {α : Type*} [LT α]

/-- The pointwise topology on trees: the initial topology of the membership
evaluations `T ↦ (u ∈ T.carrier)`, with the Sierpinski topology on `Prop`.
This is the default topology of `Tree α`; the metric topology is an additional
structure and does not replace it. -/
@[instance_reducible]
def treePointwiseTopology : TopologicalSpace (Tree α) :=
  TopologicalSpace.induced (fun T : Tree α => fun u : List α => u ∈ T.carrier)
    inferInstance

/-- The default topology of `Tree α` is the pointwise topology. -/
instance instTopologicalSpaceTree : TopologicalSpace (Tree α) :=
  treePointwiseTopology

/-- The truncation topology on trees, generated by the truncation balls
`{S | S.truncate n = T.truncate n}`. It is finer than the pointwise topology
and is the topology induced by the tree metric. It is a named topology, not
the default instance on `Tree α`. -/
@[instance_reducible]
def treeTruncationTopology : TopologicalSpace (Tree α) :=
  TopologicalSpace.generateFrom {s | ∃ T n, s = Tree.truncationBall T n}

theorem isOpen_truncationBall (T : Tree α) (n : ℕ) :
    IsOpen[treeTruncationTopology] (Tree.truncationBall T n) :=
  TopologicalSpace.isOpen_generateFrom_of_mem ⟨T, n, rfl⟩

theorem truncationBall_anti (T : Tree α) {m n : ℕ} (hmn : m ≤ n) :
    Tree.truncationBall T n ⊆ Tree.truncationBall T m := by
  intro S hS
  rw [Tree.mem_truncationBall] at hS ⊢
  calc
    S.truncate m = (S.truncate n).truncate m := by
      rw [Tree.truncate_truncate, min_eq_right hmn]
    _ = (T.truncate n).truncate m := by rw [hS]
    _ = T.truncate m := by rw [Tree.truncate_truncate, min_eq_right hmn]

theorem truncationBall_zero (T : Tree α) :
    Tree.truncationBall T 0 = Set.univ := by
  ext S
  rw [Tree.mem_truncationBall]
  constructor
  · intro _
    trivial
  · intro _
    ext u
    rw [Tree.mem_truncate, Tree.mem_truncate]
    constructor
    · rintro ⟨hlen, _⟩
      have hu : u = [] := List.length_eq_zero_iff.1 (Nat.eq_zero_of_le_zero hlen)
      subst u
      exact ⟨by simp, T.root_mem⟩
    · rintro ⟨hlen, _⟩
      have hu : u = [] := List.length_eq_zero_iff.1 (Nat.eq_zero_of_le_zero hlen)
      subst u
      exact ⟨by simp, S.root_mem⟩

theorem truncationBall_eq_of_mem {S T : Tree α} {n : ℕ}
    (h : S ∈ Tree.truncationBall T n) :
    Tree.truncationBall S n = Tree.truncationBall T n := by
  ext U
  rw [Tree.mem_truncationBall, Tree.mem_truncationBall]
  exact ⟨fun hU => hU.trans h, fun hU => hU.trans h.symm⟩

theorem truncationBall_inter_of_mem {S T U : Tree α} {m n : ℕ}
    (hU : U ∈ Tree.truncationBall S m ∩ Tree.truncationBall T n) :
    Tree.truncationBall S m ∩ Tree.truncationBall T n =
      Tree.truncationBall U (max m n) := by
  have hUS : U ∈ Tree.truncationBall S m := hU.1
  have hUT : U ∈ Tree.truncationBall T n := hU.2
  rw [Tree.mem_truncationBall] at hUS hUT
  ext X
  rw [Set.mem_inter_iff, Tree.mem_truncationBall, Tree.mem_truncationBall,
    Tree.mem_truncationBall]
  constructor
  · rintro ⟨hXS, hXT⟩
    rcases le_total m n with hmn | hnm
    · rw [max_eq_right hmn]
      exact hXT.trans hUT.symm
    · rw [max_eq_left hnm]
      exact hXS.trans hUS.symm
  · intro hX
    constructor
    · calc
        X.truncate m = (X.truncate (max m n)).truncate m := by
          rw [Tree.truncate_truncate, min_eq_right (le_max_left m n)]
        _ = (U.truncate (max m n)).truncate m := by rw [hX]
        _ = U.truncate m := by
          rw [Tree.truncate_truncate, min_eq_right (le_max_left m n)]
        _ = S.truncate m := hUS
    · calc
        X.truncate n = (X.truncate (max m n)).truncate n := by
          rw [Tree.truncate_truncate, min_eq_right (le_max_right m n)]
        _ = (U.truncate (max m n)).truncate n := by rw [hX]
        _ = U.truncate n := by
          rw [Tree.truncate_truncate, min_eq_right (le_max_right m n)]
        _ = T.truncate n := hUT

private def singletonTree : Tree α where
  carrier := {[]}
  root_mem := by simp
  parent_closed := by
    intro u v h
    simp only [Set.mem_singleton_iff] at h ⊢
    exact (List.append_eq_nil_iff.mp h).1
  sibling_closed := by
    intro u i j h hij
    simp only [Set.mem_singleton_iff] at h
    simp at h

private theorem finiteInter_truncationBalls :
    FiniteInter (insert ∅ {s : Set (Tree α) | ∃ T n, s = Tree.truncationBall T n}) := by
  refine ⟨?_, ?_⟩
  · right
    exact ⟨singletonTree, 0, (Tree.truncationBall_zero _).symm⟩
  · intro s hs t ht
    rcases hs with rfl | ⟨S, m, rfl⟩
    · exact Or.inl (by ext X; simp)
    rcases ht with rfl | ⟨T, n, rfl⟩
    · exact Or.inl (by ext X; simp)
    by_cases hne : (Tree.truncationBall S m ∩ Tree.truncationBall T n).Nonempty
    · right
      obtain ⟨U, hU⟩ := hne
      exact ⟨U, max m n, truncationBall_inter_of_mem hU⟩
    · left
      exact Set.not_nonempty_iff_eq_empty.1 hne

private theorem isTopologicalBasis_truncationBalls :
    @TopologicalSpace.IsTopologicalBasis (Tree α) treeTruncationTopology
      (insert ∅ {s : Set (Tree α) | ∃ T n, s = Tree.truncationBall T n}) := by
  have hgen : TopologicalSpace.generateFrom
      (insert ∅ {s : Set (Tree α) | ∃ T n, s = Tree.truncationBall T n}) =
      treeTruncationTopology := by
    rw [generateFrom_insert_empty]
    rfl
  exact TopologicalSpace.isTopologicalBasis_of_subbasis_of_finiteInter
    (t := treeTruncationTopology) hgen.symm finiteInter_truncationBalls

/-- A set is open for the truncation topology exactly when every point in it
contains a truncation ball that is still contained in the set. -/
theorem isOpen_truncation_iff_ball (U : Set (Tree α)) :
    IsOpen[treeTruncationTopology] U ↔
      ∀ T ∈ U, ∃ n, Tree.truncationBall T n ⊆ U := by
  letI : TopologicalSpace (Tree α) := treeTruncationTopology
  rw [isTopologicalBasis_truncationBalls.isOpen_iff]
  constructor
  · intro h T hT
    rcases h T hT with ⟨b, hb, hTb, hbU⟩
    rcases hb with rfl | ⟨S, n, rfl⟩
    · exact (hTb).elim
    · exact ⟨n, by rw [truncationBall_eq_of_mem hTb]; exact hbU⟩
  · intro h T hT
    obtain ⟨n, hn⟩ := h T hT
    exact ⟨Tree.truncationBall T n, Or.inr ⟨T, n, rfl⟩,
      Tree.mem_truncationBall.2 rfl, hn⟩

/-- Every cylinder set is open for the truncation topology: around a tree
containing `u`, the truncation ball of height `|u|` is contained in the
cylinder. -/
theorem isOpen_cylinder_truncation (u : List α) :
    IsOpen[treeTruncationTopology] {T : Tree α | u ∈ T.carrier} := by
  have hset : {T : Tree α | u ∈ T.carrier} =
      ⋃ (T : Tree α) (_ : u ∈ T.carrier), Tree.truncationBall T u.length := by
    ext S
    constructor
    · intro hS
      exact Set.mem_iUnion.2 ⟨S, Set.mem_iUnion.2 ⟨hS, by simp [Tree.truncationBall]⟩⟩
    · intro hS
      obtain ⟨T, hT⟩ := Set.mem_iUnion.1 hS
      obtain ⟨huT, hSball⟩ := Set.mem_iUnion.1 hT
      have hEq : S.truncate u.length = T.truncate u.length := hSball
      have hmem : u ∈ (T.truncate u.length).carrier :=
        Tree.mem_truncate.2 ⟨le_rfl, huT⟩
      have : u ∈ (S.truncate u.length).carrier := by
        rw [hEq]
        exact hmem
      exact (Tree.mem_truncate.1 this).2
  rw [hset]
  letI : TopologicalSpace (Tree α) := treeTruncationTopology
  exact isOpen_iUnion fun T => isOpen_iUnion fun _ => isOpen_truncationBall T u.length

/-- The truncation topology is finer than the pointwise topology. -/
theorem treeTruncationTopology_le_pointwise :
    treeTruncationTopology (α := α) ≤ treePointwiseTopology (α := α) := by
  rw [treePointwiseTopology]
  have hcont : Continuous[treeTruncationTopology,
      (inferInstance : TopologicalSpace (List α → Prop))]
      (fun T : Tree α => fun u : List α => u ∈ T.carrier) := by
    letI : TopologicalSpace (Tree α) := treeTruncationTopology
    rw [continuous_pi_iff]
    intro u
    rw [continuous_generateFrom_iff]
    intro s hs
    rw [Set.mem_singleton_iff] at hs
    subst hs
    simpa using isOpen_cylinder_truncation u
  exact hcont.le_induced

/-- With countably many labels, the pointwise topology on trees is second
countable: it is induced by the carrier map into the countably based product
space `List α → Prop`. -/
instance instSecondCountableTopologyTree [Countable α] :
    SecondCountableTopology (Tree α) := by
  let f : Tree α → (List α → Prop) := fun T => fun u => u ∈ T.carrier
  change @SecondCountableTopology (Tree α)
    (TopologicalSpace.induced f inferInstance)
  exact TopologicalSpace.secondCountableTopology_induced (Tree α) (List α → Prop) f

end Tree

namespace RootIndexed.Tree

variable {Root α : Type*} [LT α]

/-- The default topology of a root-indexed tree is the product of the
pointwise topologies of its coordinate trees. -/
theorem pointwiseTopology_eq_iInf :
    (inferInstance : TopologicalSpace (RootIndexed.Tree Root α)) =
      ⨅ r : Root,
        TopologicalSpace.induced (fun T : RootIndexed.Tree Root α => T r)
          (Tree.treePointwiseTopology (α := α)) :=
  rfl

/-- The product of the single-tree truncation topologies. -/
@[instance_reducible]
def productTruncationTopology : TopologicalSpace (RootIndexed.Tree Root α) :=
  ⨅ r : Root,
    TopologicalSpace.induced (fun T : RootIndexed.Tree Root α => T r)
      (Tree.treeTruncationTopology (α := α))

theorem productTruncationTopology_le_pointwise :
    productTruncationTopology (Root := Root) (α := α) ≤
      (inferInstance : TopologicalSpace (RootIndexed.Tree Root α)) := by
  rw [pointwiseTopology_eq_iInf]
  exact iInf_mono fun _ => induced_mono Tree.treeTruncationTopology_le_pointwise

/-- The uniform ball around `T` of level `n`: every initial ancestor agrees
with `T` up to generation `n`. -/
def uniformBall (T : RootIndexed.Tree Root α) (n : ℕ) :
    Set (RootIndexed.Tree Root α) :=
  {S | ∀ r, S r ∈ Tree.truncationBall (T r) n}

@[simp]
theorem mem_uniformBall {S T : RootIndexed.Tree Root α} {n : ℕ} :
    S ∈ uniformBall T n ↔ ∀ r, S r ∈ Tree.truncationBall (T r) n :=
  Iff.rfl

theorem uniformBall_zero (T : RootIndexed.Tree Root α) :
    uniformBall T 0 = Set.univ := by
  ext S
  simp [uniformBall, Tree.truncationBall_zero]

theorem uniformBall_anti (T : RootIndexed.Tree Root α) {m n : ℕ} (hmn : m ≤ n) :
    uniformBall T n ⊆ uniformBall T m :=
  fun _ hS _ => Tree.truncationBall_anti (T _) hmn (hS _)

theorem uniformBall_subset_of_mem {S T : RootIndexed.Tree Root α} {n : ℕ}
    (hST : S ∈ uniformBall T n) :
    uniformBall S n ⊆ uniformBall T n := by
  intro U hUS r
  exact Tree.mem_truncationBall.2
    ((Tree.mem_truncationBall.1 (hUS r)).trans
      (Tree.mem_truncationBall.1 (hST r)))

/-- The topology generated by uniform balls. -/
@[instance_reducible]
def uniformTopology : TopologicalSpace (RootIndexed.Tree Root α) :=
  TopologicalSpace.generateFrom {s | ∃ T n, s = uniformBall T n}

theorem isOpen_uniformBall (T : RootIndexed.Tree Root α) (n : ℕ) :
    IsOpen[uniformTopology (Root := Root) (α := α)] (uniformBall T n) := by
  letI : TopologicalSpace (RootIndexed.Tree Root α) :=
    uniformTopology (Root := Root) (α := α)
  exact isOpen_generateFrom_of_mem ⟨T, n, rfl⟩

private theorem isTopologicalBasis_isOpen_truncation :
    letI : TopologicalSpace (UlamHarris.Tree α) := Tree.treeTruncationTopology (α := α)
    IsTopologicalBasis {s : Set (UlamHarris.Tree α) | IsOpen s} := by
  letI : TopologicalSpace (UlamHarris.Tree α) := Tree.treeTruncationTopology (α := α)
  exact isTopologicalBasis_of_isOpen_of_nhds (fun _ h => h)
    (fun _ u ha hu => ⟨u, hu, ha, subset_rfl⟩)

theorem isTopologicalBasis_productTruncation :
    @IsTopologicalBasis (RootIndexed.Tree Root α)
      (productTruncationTopology (Root := Root) (α := α))
      {S : Set (RootIndexed.Tree Root α) |
        ∃ (V : Root → Set (UlamHarris.Tree α)) (F : Finset Root),
          (∀ r, r ∈ F → IsOpen[Tree.treeTruncationTopology (α := α)] (V r)) ∧
          S = ⋂ r ∈ F, (fun T : RootIndexed.Tree Root α => T r) ⁻¹' V r} := by
  letI : TopologicalSpace (RootIndexed.Tree Root α) :=
    productTruncationTopology (Root := Root) (α := α)
  have h := IsTopologicalBasis.iInf_induced
    (t := fun _ : Root => Tree.treeTruncationTopology (α := α))
    (T := fun _ : Root =>
      {s : Set (UlamHarris.Tree α) | IsOpen[Tree.treeTruncationTopology (α := α)] s})
    (cond := fun _ => isTopologicalBasis_isOpen_truncation (α := α))
    (f := fun (r : Root) (T : RootIndexed.Tree Root α) => T r)
  rw [show productTruncationTopology (Root := Root) (α := α) =
      ⨅ r : Root,
        TopologicalSpace.induced (fun T : RootIndexed.Tree Root α => T r)
          (Tree.treeTruncationTopology (α := α)) from rfl]
  simpa only [Set.mem_ofPred_eq] using h

theorem exists_uniformBall_subset_of_isOpen_productTruncation
    {U : Set (RootIndexed.Tree Root α)}
    (hU : IsOpen[productTruncationTopology (Root := Root) (α := α)] U)
    {T : RootIndexed.Tree Root α} (hT : T ∈ U) :
    ∃ n : ℕ, uniformBall T n ⊆ U := by
  classical
  letI : TopologicalSpace (RootIndexed.Tree Root α) :=
    productTruncationTopology (Root := Root) (α := α)
  obtain ⟨b, hb, hTb, hbU⟩ :=
    (isTopologicalBasis_productTruncation (Root := Root) (α := α)).exists_subset_of_mem_open
      hT hU
  rcases hb with ⟨V, F, hVF, rfl⟩
  have hTV : ∀ r ∈ F, T r ∈ V r := by
    intro r hr
    have h := hTb
    simp only [Set.mem_iInter, Set.mem_preimage] at h
    exact h r hr
  choose n hn using fun r (hr : r ∈ F) =>
    (Tree.isOpen_truncation_iff_ball (V r)).1 (hVF r hr) (T r) (hTV r hr)
  refine ⟨F.attach.sup (fun r => n r.1 r.2), ?_⟩
  intro S hS
  refine hbU ?_
  simp only [Set.mem_iInter, Set.mem_preimage]
  intro r hr
  refine hn r hr ?_
  have hle : n r hr ≤ F.attach.sup
      (fun r : {x : Root // x ∈ F} => n r.1 r.2) :=
    Finset.le_sup (f := fun r : {x : Root // x ∈ F} => n r.1 r.2)
      (Finset.mem_attach F ⟨r, hr⟩)
  exact Tree.truncationBall_anti (T r) hle (hS r)

theorem uniformTopology_le_productTruncation :
    uniformTopology (Root := Root) (α := α) ≤
      productTruncationTopology (Root := Root) (α := α) := by
  rw [TopologicalSpace.le_def]
  intro U hU
  choose n hn using fun p : {T : RootIndexed.Tree Root α // T ∈ U} =>
    exists_uniformBall_subset_of_isOpen_productTruncation hU p.2
  have hUnion : U = ⋃ p : {T : RootIndexed.Tree Root α // T ∈ U},
      uniformBall p.1 (n p) := by
    refine Set.Subset.antisymm (fun T hT => Set.mem_iUnion.2 ⟨⟨T, hT⟩, ?_⟩) ?_
    · simp [uniformBall]
    · exact Set.iUnion_subset fun p => hn p
  rw [hUnion]
  exact @isOpen_iUnion (RootIndexed.Tree Root α)
    {T : RootIndexed.Tree Root α // T ∈ U} (uniformTopology (Root := Root) (α := α))
    (fun p => uniformBall p.1 (n p)) (fun p => isOpen_uniformBall p.1 (n p))

end RootIndexed.Tree

end UlamHarris

end Combinatorics

end
