import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
import Topology.Cadlag.Skorokhod.EDistance

/-!
# The Skorokhod pseudo-emetric topology

The verified self-distance, symmetry, and triangle lemmas for `j1EDist`
define a pseudo-emetric topology on càdlàg paths.  Separation is deliberately
not asserted here: proving it requires the càdlàg continuity-point argument.
The Borel measurable space below is generated by this topology.
-/

namespace Skorokhod

noncomputable instance instPseudoEMetricSpaceCadlagPath
    {E : Type*} [EMetricSpace E] :
    PseudoEMetricSpace (CadlagPath UnitInterval E) :=
  PseudoEMetricSpace.ofEDist j1EDist j1EDist_self j1EDist_comm j1EDist_triangle

@[simp]
theorem edist_cadlagPath_eq_j1EDist {E : Type*} [EMetricSpace E]
    (f g : CadlagPath UnitInterval E) : edist f g = j1EDist f g :=
  rfl

noncomputable instance instMeasurableSpaceCadlagPath
    {E : Type*} [EMetricSpace E] :
    MeasurableSpace (CadlagPath UnitInterval E) :=
  borel _

instance instBorelSpaceCadlagPath {E : Type*} [EMetricSpace E] :
    BorelSpace (CadlagPath UnitInterval E) :=
  ⟨rfl⟩

end Skorokhod
