/-
Copyright (c) 2026 WANG Yiyang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: WANG Yiyang
-/

module

public import Probability.Sequence.Filtration
public import Mathlib.Probability.Independence.Basic

/-!
# Independence from the prefix filtration

An independent coordinate is independent of the sigma-algebra generated by
any disjoint set of coordinates. In particular, every future coordinate is
independent of the finite-prefix filtration.
-/

open MeasureTheory

@[expose] public section

namespace ProbabilityTheory

variable {E : Type*} [MeasurableSpace E]

section Independence

variable {Omega : Type*} [MeasurableSpace Omega] {mu : Measure Omega}
  {coordinate : ℕ → Omega → E}

/-- A member of an independent coordinate family is independent of the
sigma-algebra generated by the first `n` coordinates whenever its index is
at least `n`. -/
theorem iIndepFun.indep_coordinatePrefixFiltration_of_le
    (hindep : iIndepFun coordinate mu)
    (hmeasurable : ∀ k, Measurable (coordinate k))
    {n k : ℕ} (hnk : n ≤ k) :
    Indep (MeasurableSpace.comap (coordinate k) inferInstance)
      (⨆ j : Fin n, MeasurableSpace.comap (coordinate j) inferInstance) mu := by
  have h := indep_iSup_of_disjoint
    (fun j ↦ (hmeasurable j).comap_le) hindep.iIndep
    (S := {k}) (T := Set.Iio n) (by
      rw [Set.disjoint_singleton_left]
      exact not_lt_of_ge hnk)
  have hpast :
      (⨆ j : {j : ℕ // j ∈ Set.Iio n},
          MeasurableSpace.comap (coordinate j) inferInstance) =
        ⨆ j : Fin n, MeasurableSpace.comap (coordinate j) inferInstance := by
    apply le_antisymm
    · refine iSup_le fun j ↦ ?_
      exact le_iSup_of_le (⟨j, j.property⟩ : Fin n) (by rfl)
    · refine iSup_le fun j ↦ ?_
      exact le_iSup_of_le (⟨j, j.isLt⟩ : {j : ℕ // j ∈ Set.Iio n})
        (by rfl)
  rw [iSup_singleton, iSup_subtype', hpast] at h
  exact h

end Independence

end ProbabilityTheory

end
