/-
Copyright (c) 2026 WANG Yiyang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: WANG Yiyang
-/

module

public import Mathlib.Algebra.Group.Defs
public import Mathlib.MeasureTheory.MeasurableSpace.Defs
public import Mathlib.MeasureTheory.Group.Arithmetic
public import Probability.BranchingRandomWalk.Walk.Law
public import Combinatorics.BranchingWalk.Walk.Path.Basic
public import MeasureTheory.Measure.Convolution.Power
public import Probability.Kernel.Step
public import Mathlib.MeasureTheory.Measure.GiryMonad
public import Mathlib.MeasureTheory.Measure.Typeclasses.Probability
public import Mathlib.Probability.Kernel.Defs
public import Mathlib.Probability.Kernel.Composition.CompProd
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.Probability.Kernel.Composition.MeasureComp

/-!
# Transition kernels of random walks

An increment law induces the translation invariant Markov kernel sending a
position `x` to the law of `x + Z`.  This is the kernel interface of an
independent increment random walk; the walk itself remains the singleton-slot
specialization of a branching random walk.
-/

open MeasureTheory
open scoped ProbabilityTheory

@[expose] public section

namespace ProbabilityTheory.RandomWalk

open Combinatorics.Branching.Walk

variable {E : Type*} [MeasurableSpace E] [AddCommMonoid E] [MeasurableAdd₂ E]

/-- The transition kernel generated by an additive increment law. -/
noncomputable def incrementKernel (ν : Measure E) [SFinite ν] : Kernel E E :=
  Kernel.ofStep ν (fun x z => x + z) measurable_add

noncomputable instance incrementKernel.instIsMarkovKernel
    (ν : Measure E) [IsProbabilityMeasure ν] :
    IsMarkovKernel (incrementKernel ν) := by
  change IsMarkovKernel
    (Kernel.ofStep ν (fun x z : E => x + z) measurable_add)
  exact Kernel.ofStep.instIsMarkovKernel ν _ measurable_add

/-- At `x`, the increment kernel is the pushforward of the increment law by
translation by `x`. -/
theorem incrementKernel_apply [MeasurableSingletonClass E]
    (ν : Measure E) [SFinite ν] (x : E) :
    incrementKernel ν x = ν.map (fun z => x + z) := by
  ext s hs
  rw [incrementKernel, Kernel.ofStep_apply _ _ measurable_add _ _ hs,
    Measure.map_apply (measurable_const_add x) hs]
  rfl

/-- Applying the transition kernel to a position law convolves that law with
the increment law. -/
theorem incrementKernel_comp [MeasurableSingletonClass E]
    (ν μ : Measure E) [SFinite ν] [SFinite μ] :
    incrementKernel ν ∘ₘ μ = μ ∗ ν := by
  ext s hs
  rw [Measure.bind_apply hs (Kernel.aemeasurable _)]
  simp_rw [incrementKernel_apply ν, Measure.map_apply (measurable_const_add _) hs]
  rw [← lintegral_indicator_one hs]
  calc
    (∫⁻ a, ν ((fun z => a + z) ⁻¹' s) ∂μ) =
        ∫⁻ a, ∫⁻ z, s.indicator 1 (a + z) ∂ν ∂μ := by
      congr with a
      rw [← lintegral_indicator_one (hs.preimage (measurable_const_add a))]
      rfl
    _ = ∫⁻ a, s.indicator 1 a ∂(μ ∗ ν) :=
      (Measure.lintegral_conv (measurable_const.indicator hs)).symm

omit [AddCommMonoid E] [MeasurableAdd₂ E] in
private theorem kernel_pow_succ_apply (κ : Kernel E E)
    [IsSFiniteKernel κ] (n : ℕ) (x : E) :
    (κ ^ (n + 1)) x = κ ∘ₘ ((κ ^ n) x) := by
  ext s hs
  rw [Kernel.pow_succ_apply_eq_lintegral κ n x hs,
    Measure.bind_apply hs (Kernel.aemeasurable _)]

/-- The `n`-step transition law is translation of the `n`-fold convolution
of the increment law.  This is the Chapman--Kolmogorov form of the random
walk law. -/
theorem incrementKernel_pow_apply [MeasurableSingletonClass E]
    (ν : Measure E) [IsProbabilityMeasure ν] (n : ℕ) (x : E) :
    (incrementKernel ν ^ n) x =
      Measure.dirac x ∗ ν.convPower n := by
  induction n with
  | zero =>
      change Measure.dirac x = Measure.dirac x ∗ Measure.dirac 0
      simp
  | succ n ih =>
      rw [kernel_pow_succ_apply, ih, incrementKernel_comp,
        Measure.convPower_succ, Measure.conv_assoc,
        Measure.convPower_rotate]

/-- Under the canonical IID sequence law, the first `n` increments have
distribution equal to the `n`-fold convolution of their common law. -/
theorem iidSequenceLaw_map_partialSum [MeasurableSingletonClass E]
    (ν : Measure E) [IsProbabilityMeasure ν] (n : ℕ) :
    (iidSequenceLaw ν).map (partialSum (E := E) n) = ν.convPower n := by
  induction n with
  | zero =>
      rw [Measure.convPower_zero]
      exact (hasLaw_dirac_of_ae_eq
        (P := iidSequenceLaw ν) (X := partialSum (E := E) 0)
        (Filter.Eventually.of_forall partialSum_zero)).map_eq
  | succ n ih =>
      have hiid := iidSequenceLaw_independent ν
      have hgroup := hiid.indepFun_finset (Finset.range n) {n}
        (by simp) (fun _ => measurable_pi_apply _)
      have hind : IndepFun (partialSum (E := E) n)
          (fun increment : ℕ → E => increment n) (iidSequenceLaw ν) := by
        have hcomp := hgroup.comp
          (Finset.measurable_sum Finset.univ
            (fun k _ => measurable_pi_apply k))
          (measurable_pi_apply ⟨n, Finset.mem_singleton_self n⟩)
        change IndepFun (fun x : ℕ → E => ∑ k ∈ Finset.range n, x k)
          (fun x : ℕ → E => x n) (iidSequenceLaw ν)
        simpa [Function.comp_def, Finset.sum_attach] using hcomp
      have hsum := hind.hasLaw_add
        ⟨(partialSum_measurable n).aemeasurable, ih⟩
        ⟨(measurable_pi_apply n).aemeasurable,
          iidSequenceLaw_map_apply ν n⟩
      have hsum_eq := hsum.map_eq
      calc
        (iidSequenceLaw ν).map (partialSum (E := E) (n + 1)) =
            (iidSequenceLaw ν).map
              (partialSum n + fun increment => increment n) := by
          congr 1
          funext increment
          exact partialSum_succ n increment
        _ = ν.convPower n ∗ ν := hsum_eq
        _ = ν ∗ ν.convPower n := Measure.convPower_rotate ν n
        _ = ν.convPower (n + 1) := (Measure.convPower_succ ν n).symm

/-- Therefore the position at time `n` of the canonical IID random walk has
the same law as the `n`-step transition kernel. -/
theorem iidSequenceLaw_map_initial_add_partialSum
    [MeasurableSingletonClass E] (ν : Measure E) [IsProbabilityMeasure ν]
    (n : ℕ) (initial : E) :
    (iidSequenceLaw ν).map (fun increment => initial + partialSum n increment) =
      (incrementKernel ν ^ n) initial := by
  calc
    _ = ((iidSequenceLaw ν).map (partialSum (E := E) n)).map
        (fun y => initial + y) := by
      rw [Measure.map_map (measurable_const_add initial) (partialSum_measurable n)]
      rfl
    _ = (ν.convPower n).map (fun y => initial + y) := by
      rw [iidSequenceLaw_map_partialSum]
    _ = Measure.dirac initial ∗ ν.convPower n :=
      (Measure.dirac_conv initial (ν.convPower n)).symm
    _ = _ := (incrementKernel_pow_apply ν n initial).symm

end ProbabilityTheory.RandomWalk
