/-
Copyright (c) 2026 WANG Yiyang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: WANG Yiyang
-/

module

public import Combinatorics.BranchingWalk.Population.Cloud
public import Combinatorics.BranchingWalk.Walk.Basic
public import Algebra.BigOperators.AdditivePath.Block

/-!
# Additive paths along a singleton branching walk

This module proves only the branching-specific correspondence between a
singleton-slot branching walk and its additive increment path.
-/

open scoped BigOperators

@[expose] public section

namespace Combinatorics.Branching.Walk

open Combinatorics.UlamHarris

variable {Mark Position : Type*} [AddCommMonoid Position]

/-- Displacement along the unique lineage is the sum of its mapped
increments. -/
theorem displaceWith_lineNode_eq_displacement (d : Mark → Position)
    (increment : ℕ → Mark) (n : ℕ) :
    displaceWith d (stepFieldOfIncrements increment) [] (lineNode n) =
      AdditivePath.displacement n (d ∘ increment) := by
  simpa [AdditivePath.displacement, Function.comp_apply] using
    displaceWith_lineNode d increment n

/-- The unique lineage's position is the additive path generated by its
increments. -/
theorem position_lineNode_eq_fromIncrements (d : Mark → Position)
    (initial : Position) (increment : ℕ → Mark) (n : ℕ) :
    (ofIncrements initial increment).position d PUnit.unit (lineNode n) =
      AdditivePath.fromIncrements initial (d ∘ increment) n := by
  rw [position_lineNode]
  rfl

/-- Advancing across a block adds the mapped block increments to the current
singleton-lineage position. -/
theorem position_lineNode_add (d : Mark → Position)
    (initial : Position) (increment : ℕ → Mark) (start length : ℕ) :
    (ofIncrements initial increment).position d PUnit.unit
        (lineNode (start + length)) =
      (ofIncrements initial increment).position d PUnit.unit
          (lineNode start) +
        AdditivePath.blockSum start length (d ∘ increment) := by
  rw [position_lineNode_eq_fromIncrements, position_lineNode_eq_fromIncrements]
  simp only [AdditivePath.fromIncrements]
  rw [AdditivePath.displacement_add_eq_add_blockSum]
  ac_rfl

/-- The generation cloud records the same additive path along its unique
lineage. -/
theorem discreteTimeCloud_position_lineNode_eq_fromIncrements
    (d : Mark → Position) (initial : Position) (increment : ℕ → Mark)
    (n : ℕ) :
    (Cloud.discreteTimeCloud_ofBranchingWalk d
        (ofIncrements initial increment)).position PUnit.unit (lineNode n) =
      AdditivePath.fromIncrements initial (d ∘ increment) n := by
  exact position_lineNode_eq_fromIncrements d initial increment n

/-- The unique lineage is present in the generation cloud built from an
everywhere-present increment path. -/
theorem lineNode_mem_discreteTimeCloud (d : Mark → Position)
    (initial : Position) (increment : ℕ → Mark) (n : ℕ) :
    ((PUnit.unit, lineNode n) : RootIndexed.TreeNode PUnit PUnit) ∈
      (Cloud.discreteTimeCloud_ofBranchingWalk d
        (ofIncrements initial increment)).particles n := by
  simp [Cloud.discreteTimeCloud_ofBranchingWalk, Cloud.ofBranchingWalk,
    generation]
  exact surviveAlong_stepFieldOfIncrements increment [] (lineNode n)

end Combinatorics.Branching.Walk

end
