/-
Copyright (c) 2026 WANG Yiyang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: WANG Yiyang
-/

module

public import Mathlib.Data.Set.Function
public import Combinatorics.UlamHarris.Basic

/-!
# Address-level offspring coupling

This file defines the root-preserving child address map and its set-valued
parent-slot interface.  It contains no finiteness or spatial-order assumptions.
-/

@[expose] public section

namespace Combinatorics.Branching.Selection.Coupling

open Combinatorics.UlamHarris

variable {Root α : Type*}

/-- Append a child slot to a parent address without changing its root. -/
def childAddress (p : RootIndexed.TreeNode Root α) (i : α) :
    RootIndexed.TreeNode Root α :=
  (p.1, p.2 ++ [i])

@[simp] theorem childAddress_fst (p : RootIndexed.TreeNode Root α) (i : α) :
    (childAddress p i).1 = p.1 :=
  rfl

@[simp] theorem childAddress_snd (p : RootIndexed.TreeNode Root α) (i : α) :
    (childAddress p i).2 = p.2 ++ [i] :=
  rfl

/-- Parent and child slot are recoverable from the resulting multi-root child
address.  In particular, different roots can never be conflated. -/
theorem childAddress_joint_injective :
    Function.Injective (fun pi : RootIndexed.TreeNode Root α × α =>
      childAddress pi.1 pi.2) := by
  rintro ⟨p, i⟩ ⟨q, j⟩ h
  change (p.1, p.2 ++ [i]) = (q.1, q.2 ++ [j]) at h
  obtain ⟨hroot, hlist⟩ := Prod.ext_iff.mp h
  have hparts := List.append_inj' hlist (by simp)
  have hparent : p.2 = q.2 := hparts.1
  have hslot : i = j := by simpa using hparts.2
  cases p
  cases q
  simp_all

/-- All parent-slot candidates generated by an arbitrary parent population.
Neither the parent population nor an individual offspring population is
assumed finite or countable. -/
def offspringPairSet
    (parents : Set (RootIndexed.TreeNode Root α))
    (slots : RootIndexed.TreeNode Root α → Set α) :
    Set (RootIndexed.TreeNode Root α × α) :=
  {pi | pi.1 ∈ parents ∧ pi.2 ∈ slots pi.1}

@[simp] theorem mem_offspringPairSet
    {parents : Set (RootIndexed.TreeNode Root α)}
    {slots : RootIndexed.TreeNode Root α → Set α}
    {p : RootIndexed.TreeNode Root α} {i : α} :
    (p, i) ∈ offspringPairSet parents slots ↔ p ∈ parents ∧ i ∈ slots p :=
  Iff.rfl

/-- Genuine child addresses generated by arbitrary parent and slot sets. -/
def offspringAddressSet
    (parents : Set (RootIndexed.TreeNode Root α))
    (slots : RootIndexed.TreeNode Root α → Set α) :
    Set (RootIndexed.TreeNode Root α) :=
  (fun pi : RootIndexed.TreeNode Root α × α =>
    childAddress pi.1 pi.2) '' offspringPairSet parents slots

@[simp] theorem mem_offspringAddressSet
    {parents : Set (RootIndexed.TreeNode Root α)}
    {slots : RootIndexed.TreeNode Root α → Set α}
    {q : RootIndexed.TreeNode Root α} :
    q ∈ offspringAddressSet parents slots ↔
      ∃ p ∈ parents, ∃ i ∈ slots p, q = childAddress p i := by
  constructor
  · rintro ⟨⟨p, i⟩, ⟨hp, hi⟩, rfl⟩
    exact ⟨p, hp, i, hi, rfl⟩
  · rintro ⟨p, hp, i, hi, rfl⟩
    exact ⟨(p, i), ⟨hp, hi⟩, rfl⟩

/-- Matching parents and reusing the same slot gives an injective map of the
entire source offspring population into the target population.  This is the
set-level coupling statement; it has no finiteness or countability premise. -/
theorem offspringPairSet_injection
    (source target : Set (RootIndexed.TreeNode Root α))
    (sourceSlots targetSlots : RootIndexed.TreeNode Root α → Set α)
    (matchParent : RootIndexed.TreeNode Root α → RootIndexed.TreeNode Root α)
    (hmatch_mem : Set.MapsTo matchParent source target)
    (hmatch_inj : Set.InjOn matchParent source)
    (hslot : ∀ p ∈ source, sourceSlots p ⊆ targetSlots (matchParent p)) :
    ∃ pairMatch : RootIndexed.TreeNode Root α × α →
        RootIndexed.TreeNode Root α × α,
      Set.MapsTo pairMatch (offspringPairSet source sourceSlots)
        (offspringPairSet target targetSlots) ∧
      Set.InjOn pairMatch (offspringPairSet source sourceSlots) := by
  let pairMatch : RootIndexed.TreeNode Root α × α →
      RootIndexed.TreeNode Root α × α := fun pi => (matchParent pi.1, pi.2)
  refine ⟨pairMatch, ?_, ?_⟩
  · rintro ⟨p, i⟩ ⟨hp, hi⟩
    exact ⟨hmatch_mem hp, hslot p hp hi⟩
  · rintro ⟨p, i⟩ ⟨hp, hi⟩ ⟨q, j⟩ ⟨hq, hj⟩ heq
    change (matchParent p, i) = (matchParent q, j) at heq
    obtain ⟨hparent, hchild⟩ := Prod.ext_iff.mp heq
    exact Prod.ext (hmatch_inj hp hq hparent) hchild

end Combinatorics.Branching.Selection.Coupling

end
