/-
Copyright (c) 2026 WANG Yiyang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: WANG Yiyang
-/

module

public import Mathlib.Data.Finset.Sigma
public import Combinatorics.BranchingWalk.Selection.Coupling.Offspring.Address

/-!
# Finite offspring candidates

This file realizes the parent-slot interface on finite multi-root populations
and records the address/pair cardinality identities used by selection.
-/

@[expose] public section

namespace Combinatorics.Branching.Selection.Coupling

open Combinatorics.UlamHarris

variable {Root α : Type*}

/-- The finite candidate labels generated by a finite multi-root population.
Each parent may expose its own finite set of surviving slots. -/
noncomputable def offspringPairs
    (parents : Finset (RootIndexed.TreeNode Root α))
    (slots : RootIndexed.TreeNode Root α → Finset α) :
    Finset (RootIndexed.TreeNode Root α × α) := by
  classical
  exact parents.biUnion fun p => (slots p).image fun i => (p, i)

@[simp] theorem mem_offspringPairs
    {parents : Finset (RootIndexed.TreeNode Root α)}
    {slots : RootIndexed.TreeNode Root α → Finset α}
    {p : RootIndexed.TreeNode Root α} {i : α} :
    (p, i) ∈ offspringPairs parents slots ↔ p ∈ parents ∧ i ∈ slots p := by
  classical
  simp [offspringPairs]

/-- The finite helper is exactly the finite realization of the general
parent-slot candidate set. -/
@[simp] theorem coe_offspringPairs
    (parents : Finset (RootIndexed.TreeNode Root α))
    (slots : RootIndexed.TreeNode Root α → Finset α) :
    ↑(offspringPairs parents slots) =
      offspringPairSet (↑parents) (fun p => ↑(slots p)) := by
  classical
  ext pi
  rcases pi with ⟨p, i⟩
  simp

/-- Convert parent-slot candidate labels to their genuine multi-root child
addresses.  Joint injectivity ensures that this conversion loses neither
particle identity nor multiplicity. -/
noncomputable def offspringAddresses
    (parents : Finset (RootIndexed.TreeNode Root α))
    (slots : RootIndexed.TreeNode Root α → Finset α) :
    Finset (RootIndexed.TreeNode Root α) := by
  classical
  exact (offspringPairs parents slots).image fun pi => childAddress pi.1 pi.2

@[simp] theorem mem_offspringAddresses
    {parents : Finset (RootIndexed.TreeNode Root α)}
    {slots : RootIndexed.TreeNode Root α → Finset α}
    {q : RootIndexed.TreeNode Root α} :
    q ∈ offspringAddresses parents slots ↔
      ∃ p ∈ parents, ∃ i ∈ slots p, q = childAddress p i := by
  classical
  constructor
  · intro hq
    obtain ⟨⟨p, i⟩, hpi, hchild⟩ :=
      Finset.mem_image.mp (show q ∈ (offspringPairs parents slots).image
        (fun pi => childAddress pi.1 pi.2) from hq)
    obtain ⟨hp, hi⟩ := mem_offspringPairs.mp hpi
    exact ⟨p, hp, i, hi, hchild.symm⟩
  · rintro ⟨p, hp, i, hi, rfl⟩
    show childAddress p i ∈ (offspringPairs parents slots).image
      (fun pi => childAddress pi.1 pi.2)
    exact Finset.mem_image.mpr
      ⟨(p, i), mem_offspringPairs.mpr ⟨hp, hi⟩, rfl⟩

/-- Finite child addresses agree with the general set-valued construction. -/
@[simp] theorem coe_offspringAddresses
    (parents : Finset (RootIndexed.TreeNode Root α))
    (slots : RootIndexed.TreeNode Root α → Finset α) :
    ↑(offspringAddresses parents slots) =
      offspringAddressSet (↑parents) (fun p => ↑(slots p)) := by
  classical
  ext q
  simp

/-- Filtering genuine child addresses has the same cardinality as filtering
their unique parent-slot labels by the pulled-back predicate. -/
theorem card_filter_offspringAddresses
    (parents : Finset (RootIndexed.TreeNode Root α))
    (slots : RootIndexed.TreeNode Root α → Finset α)
    (P : RootIndexed.TreeNode Root α → Prop) [DecidablePred P] :
    ((offspringAddresses parents slots).filter P).card =
      ((offspringPairs parents slots).filter fun pi =>
        P (childAddress pi.1 pi.2)).card := by
  classical
  rw [offspringAddresses, Finset.filter_image]
  exact Finset.card_image_of_injective _ childAddress_joint_injective

end Combinatorics.Branching.Selection.Coupling

end
