import Probability.BranchingRandomWalk.Population.Processes.StepSelection.RootIndexed

/-!
# Causal finite branching populations

A causal finite population records the genealogically labelled particles
retained at every generation.  Retention may use the whole available
generation domain and may vary with time.  The only structural requirement is
that every successor is a genuine child of a retained parent in the supplied
pre-sampled step field.

This is the process-level abstraction for killed branching random walks.
Local, time-homogeneous `Step.FiniteSelection` processes are a special case.
-/

open MeasureTheory

namespace ProbabilityTheory.BranchingRandomWalk
namespace RootIndexed

open Combinatorics.UlamHarris Combinatorics.Branching

attribute [local instance] Classical.propDecidable Classical.decEq

/-- A finite genealogically labelled population adapted to a generation
domain flow and obtained by causally killing genuine offspring.

No mechanism is stored: two different killing algorithms that produce the
same retained population define the same mathematical process. -/
structure CausalFinitePopulation
    (Ω Root α X : Type*) [MeasurableSpace Ω]
    [MeasurableSpace (RootIndexed.TreeNode Root α)]
    (ℱ : ℕ → MeasurableSpace Ω)
    (stepField : Ω → RootIndexed.StepField Root α X) where
  population : ℕ → Ω → Finset (RootIndexed.TreeNode Root α)
  adapted : ∀ n, @Measurable Ω (Finset (RootIndexed.TreeNode Root α))
    (ℱ n) inferInstance (population n)
  depth : ∀ n ω p, p ∈ population n ω → p.2.length = n
  successor : ∀ n ω,
    ↑(population (n + 1) ω) ⊆
      Combinatorics.Branching.Selection.Coupling.offspringAddressSet
        (↑(population n ω))
        (fun p => support (stepField ω p.1 p.2))

namespace CausalFinitePopulation

variable {Ω Root α X : Type*} [MeasurableSpace Ω]
    [MeasurableSpace (RootIndexed.TreeNode Root α)]
    {ℱ : ℕ → MeasurableSpace Ω}
    {stepField : Ω → RootIndexed.StepField Root α X}

instance : CoeFun (CausalFinitePopulation Ω Root α X ℱ stepField)
    (fun _ => ℕ → Ω → Finset (RootIndexed.TreeNode Root α)) :=
  ⟨CausalFinitePopulation.population⟩

theorem measurable (P : CausalFinitePopulation Ω Root α X ℱ stepField)
    (n : ℕ) : @Measurable Ω (Finset (RootIndexed.TreeNode Root α))
      (ℱ n) inferInstance (P n) :=
  P.adapted n

theorem mem_depth (P : CausalFinitePopulation Ω Root α X ℱ stepField)
    {n : ℕ} {ω : Ω} {p : RootIndexed.TreeNode Root α} (hp : p ∈ P n ω) :
    p.2.length = n :=
  P.depth n ω p hp

/-- Pull a causal population back along a map that is measurable at every
generation and intertwines the pre-sampled step fields.  This changes only
the sample-space realization; the retained genealogical population is
unchanged. -/
noncomputable def pullback
    {Ω' : Type*} [MeasurableSpace Ω'] {ℱ' : ℕ → MeasurableSpace Ω'}
    {stepField' : Ω' → RootIndexed.StepField Root α X}
    (P : CausalFinitePopulation Ω' Root α X ℱ' stepField')
    (f : Ω → Ω')
    (hf : ∀ n, @Measurable Ω Ω' (ℱ n) (ℱ' n) f)
    (hfield : stepField' ∘ f = stepField) :
    CausalFinitePopulation Ω Root α X ℱ stepField where
  population n ω := P n (f ω)
  adapted n := (P.adapted n).comp (hf n)
  depth n ω p hp := P.depth n (f ω) p hp
  successor n ω := by
    have hω : stepField' (f ω) = stepField ω := congrFun hfield ω
    rw [← hω]
    exact P.successor n (f ω)

@[simp] theorem pullback_population
    {Ω' : Type*} [MeasurableSpace Ω'] {ℱ' : ℕ → MeasurableSpace Ω'}
    {stepField' : Ω' → RootIndexed.StepField Root α X}
    (P : CausalFinitePopulation Ω' Root α X ℱ' stepField')
    (f : Ω → Ω')
    (hf : ∀ n, @Measurable Ω Ω' (ℱ n) (ℱ' n) f)
    (hfield : stepField' ∘ f = stepField) (n : ℕ) (ω : Ω) :
    P.pullback f hf hfield n ω = P n (f ω) :=
  rfl

/-- A population generated by one fixed finite selection at every node is a
causal finite population.  This constructor is a specialization theorem, not
the definition of causal killing. -/
noncomputable def ofStepSelectionOn
    [MeasurableSpace X]
    (R : Step.FiniteSelection α X) (hR : Measurable R.select)
    (roots : Finset Root) :
    CausalFinitePopulation
      (RootIndexed.StepField Root α X) Root α X
      (RootIndexed.stepFiltration
        (Root := Root) (α := α) (X := X)) id where
  population := RootIndexed.StepSelection.labelledPopulationOn R roots
  adapted := RootIndexed.StepSelection.labelledPopulationOn_adapted R hR roots
  depth := RootIndexed.StepSelection.labelledPopulationOn_depth R roots
  successor := by
    intro n field p hp
    have hselected :=
      RootIndexed.StepSelection.labelledPopulationOn_succ_subset
        R roots n field hp
    obtain ⟨parent, hparent, i, hi, rfl⟩ :=
      Combinatorics.Branching.Selection.Coupling.mem_offspringAddressSet.mp
        hselected
    apply Combinatorics.Branching.Selection.Coupling.mem_offspringAddressSet.mpr
    exact ⟨parent, hparent, i, R.mem_support (field parent.1 parent.2) hi, rfl⟩

@[simp] theorem ofStepSelectionOn_population
    [MeasurableSpace X]
    (R : Step.FiniteSelection α X) (hR : Measurable R.select)
    (roots : Finset Root) (n : ℕ)
    (field : RootIndexed.StepField Root α X) :
    ofStepSelectionOn R hR roots n field =
      RootIndexed.StepSelection.labelledPopulationOn R roots n field :=
  rfl

end CausalFinitePopulation
end RootIndexed
end ProbabilityTheory.BranchingRandomWalk
