import Probability.Process.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.PathClassRegimes

#print axioms ProbabilityTheory.cdf_gaussianReal_zero_lt_one
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.tendsto_log_probability_ratio_of_IsM_of_index_two
#print axioms ProbabilityTheory.RandomWalk.SmallDeviation.Mogulskii.Stable.Discrete.tendsto_log_probability_ratio_of_IsM_of_index_two_of_brownian
