/-
Copyright (c) 2026 WANG Yiyang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: WANG Yiyang
-/

module

public import Probability.Process.IndepIncrements.DisjointPaths
public import Probability.Process.SmallDeviation.Mogulskii.PathClass.Boundary.Partition
public import Order.Interval.RationalCoordinate.UnitInterval
public import Topology.Order.UnitInterval.Rational

/-!
# Independent increment paths on a step-corridor partition

The union of the two finite boundary-knot sets gives a nonuniform finite
partition. Each cell is parametrized by rational unit-interval coordinates.
Independent increments make the resulting translated cell paths mutually
independent. The cell immediately before a knot includes its left endpoint;
the value at the right endpoint is kept as a coordinate for return events.
-/

@[expose] public section

open MeasureTheory
open scoped NNReal

namespace ProbabilityTheory.Process.SmallDeviation.Mogulskii

/-- Rational coordinates strictly before the right endpoint. Boundary jumps
are assigned to the cell on their right, so upper corridor restrictions on a
cell use this half-open coordinate type. -/
abbrev CellInteriorCoordinate :=
  {q : ↑RationalCoordinate.UnitInterval // q < ⊤}

/-- The rational coordinate interval embeds monotonically into the real unit
interval, fixing its left endpoint. -/
private theorem rationalCoordinate_toUnitInterval_bot :
    RationalCoordinate.toUnitInterval (⊥ : RationalCoordinate.UnitInterval) =
      (⊥ : unitInterval) := by
  apply Subtype.ext
  norm_num [RationalCoordinate.toUnitInterval]

private theorem monotone_rationalCoordinate_toUnitInterval :
    Monotone (RationalCoordinate.toUnitInterval :
      RationalCoordinate.UnitInterval → unitInterval) := by
  intro p q hpq
  change ((p : ℚ) : ℝ) ≤ ((q : ℚ) : ℝ)
  exact_mod_cast hpq

/-- On the nonuniform finite partition generated by both step boundaries, the
translated rational-coordinate cell paths of any process with independent
increments are mutually independent. This form applies directly to the
canonical coordinate process under a stable path law. -/
theorem HasIndepIncrements.iIndepFun_commonStepBoundaryCells
    {Ω : Type*} [MeasurableSpace Ω] {X : unitInterval → Ω → ℝ}
    {P : Measure Ω} [IsProbabilityMeasure P]
    (hX : HasIndepIncrements X P)
    (hXmeas : ∀ t, AEMeasurable (X t) P) (upper lower : StepBoundary) :
    let knots := StepBoundary.commonKnots upper lower
    iIndepFun
      (fun (i : Fin (knots.card - 1)) ω q =>
        X (StepBoundary.commonPartitionCellTime upper lower i.val
          (RationalCoordinate.toUnitInterval q)) ω -
          X (StepBoundary.commonPartitionGrid upper lower i.val) ω) P := by
  let knots := StepBoundary.commonKnots upper lower
  let count := knots.card - 1
  let grid : ℕ → unitInterval := StepBoundary.commonPartitionGrid upper lower
  let τ : ℕ → RationalCoordinate.UnitInterval → unitInterval := fun k q =>
    StepBoundary.commonPartitionCellTime upper lower k
      (RationalCoordinate.toUnitInterval q)
  have hgrid : Monotone grid := StepBoundary.monotone_commonPartitionGrid upper lower
  have hleft : ∀ i < count, ∀ q, grid i ≤ τ i q := by
    intro i hi q
    exact StepBoundary.commonPartitionCellTime_left_le upper lower i
      (RationalCoordinate.toUnitInterval q)
  have hright : ∀ i < count, ∀ q, τ i q ≤ grid (i + 1) := by
    intro i hi q
    exact StepBoundary.commonPartitionCellTime_le_right upper lower i
      (RationalCoordinate.toUnitInterval q)
  have hstart : ∀ i < count, τ i ⊥ = grid i := by
    intro i hi
    change StepBoundary.commonPartitionCellTime upper lower i
      (RationalCoordinate.toUnitInterval ⊥) =
        StepBoundary.commonPartitionGrid upper lower i
    rw [rationalCoordinate_toUnitInterval_bot,
      StepBoundary.commonPartitionCellTime_bot]
  have hindep := hX.iIndepFun_finiteAdjacentPaths
    hXmeas count grid hgrid ⊥ τ hleft hright hstart
  simpa [knots, count, grid, τ] using hindep

/-- Restrict the independent closed-cell observation families to rational
times strictly before the right endpoint. This is the family used to impose
the old step-boundary values on `[tᵢ,tᵢ₊₁)`; endpoint return conditions are
handled separately at the next knot. -/
theorem HasIndepIncrements.iIndepFun_commonStepBoundaryInteriorCells
    {Ω : Type*} [MeasurableSpace Ω] {X : unitInterval → Ω → ℝ}
    {P : Measure Ω} [IsProbabilityMeasure P]
    (hX : HasIndepIncrements X P)
    (hXmeas : ∀ t, AEMeasurable (X t) P) (upper lower : StepBoundary) :
    let knots := StepBoundary.commonKnots upper lower
    iIndepFun
      (fun (i : Fin (knots.card - 1)) (ω : Ω) (q : CellInteriorCoordinate) =>
        X (StepBoundary.commonPartitionCellTime upper lower i.val
          (RationalCoordinate.toUnitInterval q.val)) ω -
          X (StepBoundary.commonPartitionGrid upper lower i.val) ω) P := by
  let knots := StepBoundary.commonKnots upper lower
  let restrict : (↑RationalCoordinate.UnitInterval → ℝ) →
      (CellInteriorCoordinate → ℝ) := fun path q => path q.val
  have hrestrict : Measurable restrict := by
    rw [measurable_pi_iff]
    intro q
    exact measurable_pi_apply q.val
  have hindep := (HasIndepIncrements.iIndepFun_commonStepBoundaryCells
    hX hXmeas upper lower).comp
    (fun _ => restrict) (fun _ => hrestrict)
  convert hindep using 1
  funext i ω q
  rfl

end ProbabilityTheory.Process.SmallDeviation.Mogulskii

end
