import Combinatorics.BranchingWalk.Walk.Path.Basic
import Probability.Sequence.IID
import Mathlib.Probability.Independence.Basic
import Mathlib.Probability.Process.Adapted

/-!
# The filtration of an increment path

At time `n`, a walk position uses exactly the increments with indices below
`n`.  This file records that alignment explicitly.  In particular, it avoids
using the natural filtration of the coordinate process itself, whose value at
time `n` already exposes increment `n`.
-/

open MeasureTheory
open scoped BigOperators

namespace ProbabilityTheory.RandomWalk

open Combinatorics.Branching.Walk

variable {E : Type*} [MeasurableSpace E]

/-- The first `n` coordinates of an increment path. -/
def incrementPrefix (n : ℕ) : (ℕ → E) → (Fin n → E) :=
  fun increment k ↦ increment k

theorem measurable_incrementPrefix (n : ℕ) :
    Measurable (incrementPrefix (E := E) n) := by
  exact Measurable.of_eval fun k ↦ by
    change Measurable (fun increment : ℕ → E ↦ increment (k : ℕ))
    exact measurable_pi_apply (k : ℕ)

/-- The walk filtration: at time `n` it contains exactly the first `n`
increments.  It is implemented as the natural filtration of finite-prefix
observations so that it reuses mathlib's filtration API. -/
def incrementFiltration :
    Filtration ℕ (inferInstance : MeasurableSpace (ℕ → E)) where
  seq n := ⨆ k : Fin n,
    MeasurableSpace.comap (fun increment : ℕ → E ↦ increment (k : ℕ))
      inferInstance
  mono' n m hnm := by
    refine iSup_le fun k ↦ ?_
    let k' : Fin m := ⟨k, lt_of_lt_of_le k.isLt hnm⟩
    simpa [k'] using le_iSup
      (fun j : Fin m ↦ MeasurableSpace.comap
        (fun increment : ℕ → E ↦ increment (j : ℕ)) inferInstance) k'
  le' n := by
    refine iSup_le fun k ↦ ?_
    exact (measurable_pi_apply (k : ℕ)).comap_le

theorem incrementPrefix_measurable (n : ℕ) :
    Measurable[incrementFiltration (E := E) n]
      (incrementPrefix (E := E) n) := by
  rw [measurable_iff_comap_le]
  simp only [MeasurableSpace.pi, MeasurableSpace.comap_iSup,
    MeasurableSpace.comap_comp]
  exact iSup_le fun k ↦ le_iSup
    (fun j : Fin n ↦ MeasurableSpace.comap
      (fun increment : ℕ → E ↦ increment (j : ℕ)) inferInstance) k

/-- The walk domain at time `n` is exactly the domain generated by the
finite prefix map. -/
theorem incrementFiltration_eq_comap_incrementPrefix (n : ℕ) :
    incrementFiltration (E := E) n =
      MeasurableSpace.comap (incrementPrefix (E := E) n) inferInstance := by
  simp only [incrementFiltration, MeasurableSpace.pi,
    MeasurableSpace.comap_iSup, MeasurableSpace.comap_comp]
  apply iSup_congr
  intro k
  congr 1

theorem incrementPrefix_adapted :
    Adapted (incrementFiltration (E := E)) (incrementPrefix (E := E)) :=
  incrementPrefix_measurable

theorem increment_measurable (n : ℕ) (k : Fin n) :
    Measurable[incrementFiltration (E := E) n]
      (fun increment : ℕ → E ↦ increment k) :=
  (measurable_pi_apply k).comp
    (incrementPrefix_measurable n)

section Independence

variable {Omega : Type*} [MeasurableSpace Omega] {mu : Measure Omega}
  {increment : ℕ → Omega → E}

/-- A future increment is independent of the walk domain at every earlier
time.  No countability or topological assumption on the increment space is
needed. -/
theorem iIndepFun.indep_incrementFiltration_of_le
    (hindep : iIndepFun increment mu)
    (hmeasurable : ∀ k, Measurable (increment k))
    {n k : ℕ} (hnk : n ≤ k) :
    Indep (MeasurableSpace.comap (increment k) inferInstance)
      (⨆ j : Fin n, MeasurableSpace.comap (increment j) inferInstance) mu := by
  have h := indep_iSup_of_disjoint
    (fun j ↦ (hmeasurable j).comap_le) hindep.iIndep
    (S := {k}) (T := Set.Iio n) (by
      rw [Set.disjoint_singleton_left]
      exact not_lt_of_ge hnk)
  have hpast :
      (⨆ j : {j : ℕ // j ∈ Set.Iio n},
          MeasurableSpace.comap (increment j) inferInstance) =
        ⨆ j : Fin n, MeasurableSpace.comap (increment j) inferInstance := by
    apply le_antisymm
    · refine iSup_le fun j ↦ ?_
      exact le_iSup_of_le (⟨j, j.property⟩ : Fin n) (by rfl)
    · refine iSup_le fun j ↦ ?_
      exact le_iSup_of_le (⟨j, j.isLt⟩ : {j : ℕ // j ∈ Set.Iio n})
        (by rfl)
  rw [iSup_singleton, iSup_subtype', hpast] at h
  exact h

end Independence

/-- Under the canonical IID law, every not-yet-exposed coordinate is
independent of the current walk domain. -/
theorem independentIncrementLaw.indep_coordinate_incrementFiltration
    (nu : Measure E) [IsProbabilityMeasure nu]
    {n k : ℕ} (hnk : n ≤ k) :
    Indep (MeasurableSpace.comap
        (fun increment : ℕ → E ↦ increment k) inferInstance)
      (incrementFiltration (E := E) n) (iidSequenceLaw nu) := by
  exact iIndepFun.indep_incrementFiltration_of_le
    (iidSequenceLaw_independent nu) (fun j ↦ measurable_pi_apply j) hnk

section AddCommMonoid

variable [AddCommMonoid E] [MeasurableAdd₂ E]

/-- The position process is adapted to the filtration exposing precisely the
increments already used in the position. -/
theorem positionProcess_adapted (initial : E) :
    Adapted (incrementFiltration (E := E)) (positionProcess initial) := by
  intro n
  rw [show positionProcess initial n = fun increment : ℕ → E ↦
      initial + ∑ k : Fin n, increment k by
    funext increment
    simp only [positionProcess, partialSum]
    rw [Fin.sum_univ_eq_sum_range]]
  exact measurable_const.add
    (Finset.measurable_sum Finset.univ fun k _ ↦ increment_measurable n k)

end AddCommMonoid

end ProbabilityTheory.RandomWalk
