import MeasureTheory.UlamHarris.Basic
import Mathlib.MeasureTheory.MeasurableSpace.Constructions

/-!
# Deterministic Ulam--Harris trees

`Tree α` is a deterministic rooted tree of addresses `TreeNode α`, carrying
the root, parent, and ordered-sibling axioms, so a bare `Set (List α)` is only
its carrier. The structure is not assumed to be finite, countable, or locally
finite; `Tree ℕ` is the Ulam--Harris case of the paper.

The measurable space on `Tree α` is the one induced by the carrier: it is the
smallest σ-algebra making `T ↦ T.carrier` measurable, where `Set (List α)`
carries mathlib's coordinate σ-algebra. Equivalently it is generated by the
sets `{T | u ∈ T.carrier}` for `u : List α`, so a random tree is measurable
exactly when membership of every address is measurable. This is the
σ-algebra under which the realized tree of a branching-step field is a random
variable.
-/

namespace MeasureTheory

namespace UlamHarris

/-- A rooted tree of addresses. The carrier contains the root, is parent
closed, and for ordered child labels contains every smaller sibling below a
present child. `Set (List α)` is only the underlying carrier of this
structure. -/
structure Tree (α : Type*) [LT α] where
  carrier : Set (List α)
  root_mem : [] ∈ carrier
  parent_closed : ∀ {u v : List α}, u ++ v ∈ carrier → u ∈ carrier
  sibling_closed : ∀ {u : List α} {i j : α},
    u ++ [j] ∈ carrier → i < j → u ++ [i] ∈ carrier

@[simp] theorem Tree.root_mem' {α : Type*} [LT α]
    (T : Tree α) :
    [] ∈ T.carrier := T.root_mem

theorem Tree.mem_parent {α : Type*} [LT α] (T : Tree α)
    {u v : List α} (h : u ++ v ∈ T.carrier) : u ∈ T.carrier :=
  T.parent_closed h

/-- The measurable space on trees: the σ-algebra induced by the carrier. -/
instance instMeasurableSpaceTree {α : Type*} [LT α] :
    MeasurableSpace (Tree α) :=
  MeasurableSpace.comap (fun T : Tree α => T.carrier) inferInstance

theorem measurable_carrier {α : Type*} [LT α] :
    Measurable (fun T : Tree α => T.carrier) :=
  Measurable.of_comap_le le_rfl

/-- Membership of a fixed address is measurable for the tree σ-algebra. -/
theorem measurableSet_carrier {α : Type*} [LT α] (u : List α) :
    MeasurableSet {T : Tree α | u ∈ T.carrier} :=
  MeasurableSet.preimage (measurableSet_mem u) measurable_carrier

end UlamHarris

end MeasureTheory
