import MeasureTheory.UlamHarris.Tree.Basic
import MeasureTheory.UlamHarris.Tree.Truncation
import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
import Mathlib.Topology.Constructions
import Mathlib.Topology.Order
import Mathlib.Topology.Separation.Basic

/-!
# Topologies and Borel structure on Ulam--Harris trees

The σ-algebra `instMeasurableSpaceTree` on `Tree α` is the cylinder σ-algebra:
the smallest σ-algebra making every membership evaluation
`T ↦ (u ∈ T.carrier)` measurable. This file carries the two topologies that
the Borel discussion needs, both defined on `Tree α` itself and using only the
current mathlib.

* `instTopologicalSpaceTree` is the pointwise (initial) topology of the
  evaluations `T ↦ (u ∈ T.carrier)`. Its Borel σ-algebra is exactly the
  cylinder σ-algebra (`borel_tree_eq_cylinder`).
* `treeTruncationTopology` is generated by the truncation balls
  `{S | S.truncate n = T.truncate n}`. It is the topology of the tree metric
  used in the RandomGraph development, and it is finer than the pointwise
  topology. Consequently the cylinder σ-algebra is contained in its Borel
  σ-algebra (`cylinder_le_borel_truncation`), which is the precise form of
  "the cylinder σ-algebra is coarser than the Borel σ-algebra".

The two local instances on `Prop` fill small gaps in the current mathlib: the
Sierpinski topology on `Prop` is T0, and `MeasurableSpace Prop` is `⊤`, hence
Borel. They are `local`, so importing this file does not alter the instance
graph seen by other files.
-/

set_option linter.style.haveILetI false

open MeasureTheory
open scoped Topology

namespace MeasureTheory

namespace UlamHarris

local instance instT0SpaceProp : T0Space Prop := by
  rw [t0Space_iff_exists_isOpen_xor_mem]
  intro x y _hxy
  refine ⟨{True}, ?_, ?_⟩
  · exact TopologicalSpace.isOpen_generateFrom_of_mem (by simp)
  · by_cases hx : x <;> by_cases hy : y <;> simp_all [Xor]

local instance instBorelSpaceProp : BorelSpace Prop where
  measurable_eq := by
    rw [borel_eq_top_of_countable]
    rfl

section Tree

variable {α : Type*} [LT α]

/-- The pointwise topology on trees: the initial topology of the membership
evaluations `T ↦ (u ∈ T.carrier)`, with the Sierpinski topology on `Prop`. -/
instance instTopologicalSpaceTree : TopologicalSpace (Tree α) :=
  TopologicalSpace.induced (fun T : Tree α => fun u : List α => u ∈ T.carrier)
    inferInstance

/-- The truncation topology on trees, generated by the truncation balls
`{S | S.truncate n = T.truncate n}`. It is the topology of the tree metric used
for the Borel structure in the RandomGraph development, and it is finer than
the pointwise topology. -/
@[instance_reducible]
def treeTruncationTopology : TopologicalSpace (Tree α) :=
  TopologicalSpace.generateFrom {s | ∃ T n, s = Tree.truncationBall T n}

theorem isOpen_truncationBall (T : Tree α) (n : ℕ) :
    IsOpen[treeTruncationTopology] (Tree.truncationBall T n) :=
  TopologicalSpace.isOpen_generateFrom_of_mem ⟨T, n, rfl⟩

/-- Every cylinder set is open for the truncation topology: around a tree
containing `u`, the truncation ball of height `|u|` is contained in the
cylinder. -/
theorem isOpen_cylinder_truncation (u : List α) :
    IsOpen[treeTruncationTopology] {T : Tree α | u ∈ T.carrier} := by
  have hset : {T : Tree α | u ∈ T.carrier} =
      ⋃ (T : Tree α) (_ : u ∈ T.carrier), Tree.truncationBall T u.length := by
    ext S
    constructor
    · intro hS
      exact Set.mem_iUnion.2 ⟨S, Set.mem_iUnion.2 ⟨hS, by simp [Tree.truncationBall]⟩⟩
    · intro hS
      obtain ⟨T, hT⟩ := Set.mem_iUnion.1 hS
      obtain ⟨huT, hSball⟩ := Set.mem_iUnion.1 hT
      have hEq : S.truncate u.length = T.truncate u.length := hSball
      have hmem : u ∈ (T.truncate u.length).carrier :=
        Tree.mem_truncate.2 ⟨le_rfl, huT⟩
      have : u ∈ (S.truncate u.length).carrier := by
        rw [hEq]
        exact hmem
      exact (Tree.mem_truncate.1 this).2
  rw [hset]
  letI : TopologicalSpace (Tree α) := treeTruncationTopology
  exact isOpen_iUnion fun T => isOpen_iUnion fun _ => isOpen_truncationBall T u.length

/-- The truncation topology is finer than the pointwise topology. -/
theorem treeTruncationTopology_le_pointwise :
    treeTruncationTopology (α := α) ≤ instTopologicalSpaceTree := by
  rw [instTopologicalSpaceTree]
  have hcont : Continuous[treeTruncationTopology,
      (inferInstance : TopologicalSpace (List α → Prop))]
      (fun T : Tree α => fun u : List α => u ∈ T.carrier) := by
    letI : TopologicalSpace (Tree α) := treeTruncationTopology
    rw [continuous_pi_iff]
    intro u
    rw [continuous_generateFrom_iff]
    intro s hs
    rw [Set.mem_singleton_iff] at hs
    subst hs
    simpa using isOpen_cylinder_truncation u
  exact hcont.le_induced

variable [Countable α]

/-- For the pointwise topology, the Borel σ-algebra on trees is exactly the
cylinder σ-algebra already carried by `Tree α`. -/
theorem borel_tree_eq_cylinder :
    @borel (Tree α) instTopologicalSpaceTree = instMeasurableSpaceTree := by
  unfold instTopologicalSpaceTree instMeasurableSpaceTree
  rw [borel_comap, ← BorelSpace.measurable_eq (α := List α → Prop)]
  rfl

/-- Every topology finer than the pointwise one (below it in mathlib's lattice
order) has a Borel σ-algebra containing the cylinder σ-algebra. -/
theorem cylinder_le_borel_of_le {t : TopologicalSpace (Tree α)}
    (h : t ≤ instTopologicalSpaceTree) :
    instMeasurableSpaceTree ≤ @borel (Tree α) t := by
  rw [← borel_tree_eq_cylinder]
  exact borel_anti h

/-- The cylinder σ-algebra is contained in the Borel σ-algebra of the
truncation topology. -/
theorem cylinder_le_borel_truncation :
    instMeasurableSpaceTree ≤ @borel (Tree α) treeTruncationTopology :=
  cylinder_le_borel_of_le treeTruncationTopology_le_pointwise

/-- The cylinder σ-algebra is a Borel σ-algebra for the pointwise topology. -/
instance instBorelSpaceTree : BorelSpace (Tree α) :=
  ⟨borel_tree_eq_cylinder.symm⟩

end Tree

end UlamHarris

end MeasureTheory
