/-
Copyright (c) 2026 WANG Yiyang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: WANG Yiyang
-/

module

public import Mathlib.Probability.Process.Adapted

/-!
# Prefix filtration of a sequence

The filtration generated by the first `n` coordinates of a sequence. This
construction is independent of any interpretation of the coordinates as
increments or states of a particular process.
-/

open MeasureTheory

@[expose] public section

namespace ProbabilityTheory

variable {E : Type*} [MeasurableSpace E]

/-- The first `n` coordinates of a sequence. -/
def sequencePrefix (n : ℕ) : (ℕ → E) → Fin n → E :=
  fun sequence k ↦ sequence k

theorem measurable_sequencePrefix (n : ℕ) :
    Measurable (sequencePrefix (E := E) n) := by
  exact Measurable.of_eval fun k ↦ measurable_pi_apply (k : ℕ)

/-- Dropping a finite prefix is measurable on sequence space. -/
theorem measurable_sequenceNatAdd (offset : ℕ) :
    Measurable (fun sequence : ℕ → E => fun n => sequence (offset + n)) := by
  exact Measurable.of_eval fun n => measurable_pi_apply (offset + n)

/-- Sigma-algebra generated by the first `n` coordinate evaluations. -/
def sequencePrefixFiltration : Filtration ℕ (inferInstance : MeasurableSpace (ℕ → E)) where
  seq n := ⨆ k : Fin n,
    MeasurableSpace.comap (fun sequence : ℕ → E ↦ sequence (k : ℕ)) inferInstance
  mono' n m hnm := by
    refine iSup_le fun k ↦ ?_
    let k' : Fin m := ⟨k, lt_of_lt_of_le k.isLt hnm⟩
    simpa [k'] using le_iSup
      (fun j : Fin m ↦ MeasurableSpace.comap
        (fun sequence : ℕ → E ↦ sequence (j : ℕ)) inferInstance) k'
  le' n := by
    refine iSup_le fun k ↦ ?_
    exact (measurable_pi_apply (k : ℕ)).comap_le

theorem sequencePrefix_measurable (n : ℕ) :
    Measurable[sequencePrefixFiltration (E := E) n]
      (sequencePrefix (E := E) n) := by
  rw [measurable_iff_comap_le]
  simp only [MeasurableSpace.pi, MeasurableSpace.comap_iSup,
    MeasurableSpace.comap_comp]
  exact iSup_le fun k ↦ le_iSup
    (fun j : Fin n ↦ MeasurableSpace.comap
      (fun sequence : ℕ → E ↦ sequence (j : ℕ)) inferInstance) k

/-- The prefix filtration is exactly the domain of its finite-coordinate map. -/
theorem sequencePrefixFiltration_eq_comap_sequencePrefix (n : ℕ) :
    sequencePrefixFiltration (E := E) n =
      MeasurableSpace.comap (sequencePrefix (E := E) n) inferInstance := by
  simp only [sequencePrefixFiltration, MeasurableSpace.pi,
    MeasurableSpace.comap_iSup, MeasurableSpace.comap_comp]
  apply iSup_congr
  intro k
  congr 1

theorem sequencePrefix_adapted :
    Adapted (sequencePrefixFiltration (E := E)) (sequencePrefix (E := E)) :=
  sequencePrefix_measurable

end ProbabilityTheory

end
