/-
Copyright (c) 2026 WANG Yiyang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: WANG Yiyang
-/

module

public import Probability.Sequence.Block
public import Mathlib.Probability.Process.Adapted

/-!
# Prefix filtration of a sequence

The filtration generated by the first `n` coordinates of a sequence. This
construction is independent of any interpretation of the coordinates as
increments or states of a particular process.
-/

open MeasureTheory

@[expose] public section

namespace ProbabilityTheory

variable {E : Type*} [MeasurableSpace E]

/-- Sigma-algebra generated by the first `n` coordinate evaluations. -/
def sequencePrefixFiltration : Filtration ℕ (inferInstance : MeasurableSpace (ℕ → E)) where
  seq n := ⨆ k : Fin n,
    MeasurableSpace.comap (fun sequence : ℕ → E ↦ sequence (k : ℕ)) inferInstance
  mono' n m hnm := by
    refine iSup_le fun k ↦ ?_
    let k' : Fin m := ⟨k, lt_of_lt_of_le k.isLt hnm⟩
    simpa [k'] using le_iSup
      (fun j : Fin m ↦ MeasurableSpace.comap
        (fun sequence : ℕ → E ↦ sequence (j : ℕ)) inferInstance) k'
  le' n := by
    refine iSup_le fun k ↦ ?_
    exact (measurable_pi_apply (k : ℕ)).comap_le

/-- The prefix filtration is exactly the domain of its finite-coordinate map. -/
theorem sequencePrefixFiltration_eq_comap_blockCoordinates (n : ℕ) :
    sequencePrefixFiltration (E := E) n =
      MeasurableSpace.comap
        (Combinatorics.Sequence.blockCoordinates 0 n) inferInstance := by
  simp only [sequencePrefixFiltration, MeasurableSpace.pi,
    MeasurableSpace.comap_iSup, MeasurableSpace.comap_comp]
  apply iSup_congr
  intro k
  congr 1
  funext sequence
  simp [Combinatorics.Sequence.blockCoordinates]

/-- Each coordinate exposed by the time-`n` prefix is measurable with respect
to the prefix filtration at time `n`. -/
theorem sequenceCoordinate_measurable (n : ℕ) (k : Fin n) :
    Measurable[sequencePrefixFiltration (E := E) n]
      (fun sequence : ℕ → E => sequence k) := by
  rw [measurable_iff_comap_le]
  exact le_iSup
    (fun j : Fin n => MeasurableSpace.comap
      (fun sequence : ℕ → E => sequence (j : ℕ)) inferInstance) k

end ProbabilityTheory

end
