module

public import Mathlib.Data.Finset.Sigma
public import Combinatorics.UlamHarris.Basic
public import Combinatorics.BranchingWalk.Cloud.Order.SliceDominatingMap

/-!
# Multi-root offspring coupling

This file isolates the combinatorial step used when a coupling gives matched
parents the same offspring marks.  Roots and child slots are arbitrary: no
enumeration or countability assumption is made on either type.  General
offspring populations are sets.  Finsets occur only in the finite comparison
lemmas used by a capacity selection.

Candidates are first represented by `(parent, slot)` pairs.  This representation
retains multiplicity and makes the parent matching visibly injective.  Turning a
pair into the address obtained by appending its slot is a separate, deterministic
operation.
-/

@[expose] public section

namespace Combinatorics.Branching.Selection.Coupling

open Combinatorics.UlamHarris

variable {Root α Position Value : Type*}

/-- Append a child slot to a parent address without changing its root. -/
def childAddress (p : RootIndexed.TreeNode Root α) (i : α) :
    RootIndexed.TreeNode Root α :=
  (p.1, p.2 ++ [i])

@[simp] theorem childAddress_fst (p : RootIndexed.TreeNode Root α) (i : α) :
    (childAddress p i).1 = p.1 :=
  rfl

@[simp] theorem childAddress_snd (p : RootIndexed.TreeNode Root α) (i : α) :
    (childAddress p i).2 = p.2 ++ [i] :=
  rfl

/-- Parent and child slot are recoverable from the resulting multi-root child
address.  In particular, different roots can never be conflated. -/
theorem childAddress_joint_injective :
    Function.Injective (fun pi : RootIndexed.TreeNode Root α × α =>
      childAddress pi.1 pi.2) := by
  rintro ⟨p, i⟩ ⟨q, j⟩ h
  change (p.1, p.2 ++ [i]) = (q.1, q.2 ++ [j]) at h
  obtain ⟨hroot, hlist⟩ := Prod.ext_iff.mp h
  have hparts := List.append_inj' hlist (by simp)
  have hparent : p.2 = q.2 := hparts.1
  have hslot : i = j := by simpa using hparts.2
  cases p
  cases q
  simp_all

/-- All parent-slot candidates generated by an arbitrary parent population.
Neither the parent population nor an individual offspring population is
assumed finite or countable. -/
def offspringPairSet
    (parents : Set (RootIndexed.TreeNode Root α))
    (slots : RootIndexed.TreeNode Root α → Set α) :
    Set (RootIndexed.TreeNode Root α × α) :=
  {pi | pi.1 ∈ parents ∧ pi.2 ∈ slots pi.1}

@[simp] theorem mem_offspringPairSet
    {parents : Set (RootIndexed.TreeNode Root α)}
    {slots : RootIndexed.TreeNode Root α → Set α}
    {p : RootIndexed.TreeNode Root α} {i : α} :
    (p, i) ∈ offspringPairSet parents slots ↔ p ∈ parents ∧ i ∈ slots p :=
  Iff.rfl

/-- Genuine child addresses generated by arbitrary parent and slot sets. -/
def offspringAddressSet
    (parents : Set (RootIndexed.TreeNode Root α))
    (slots : RootIndexed.TreeNode Root α → Set α) :
    Set (RootIndexed.TreeNode Root α) :=
  (fun pi => childAddress pi.1 pi.2) '' offspringPairSet parents slots

@[simp] theorem mem_offspringAddressSet
    {parents : Set (RootIndexed.TreeNode Root α)}
    {slots : RootIndexed.TreeNode Root α → Set α}
    {q : RootIndexed.TreeNode Root α} :
    q ∈ offspringAddressSet parents slots ↔
      ∃ p ∈ parents, ∃ i ∈ slots p, q = childAddress p i := by
  constructor
  · rintro ⟨⟨p, i⟩, ⟨hp, hi⟩, rfl⟩
    exact ⟨p, hp, i, hi, rfl⟩
  · rintro ⟨p, hp, i, hi, rfl⟩
    exact ⟨(p, i), ⟨hp, hi⟩, rfl⟩

/-- Matching parents and reusing the same slot gives an injective map of the
entire source offspring population into the target population.  This is the
set-level coupling statement; it has no finiteness or countability premise. -/
theorem offspringPairSet_injection
    (source target : Set (RootIndexed.TreeNode Root α))
    (sourceSlots targetSlots : RootIndexed.TreeNode Root α → Set α)
    (matchParent : RootIndexed.TreeNode Root α → RootIndexed.TreeNode Root α)
    (hmatch_mem : Set.MapsTo matchParent source target)
    (hmatch_inj : Set.InjOn matchParent source)
    (hslot : ∀ p ∈ source, sourceSlots p ⊆ targetSlots (matchParent p)) :
    ∃ pairMatch : RootIndexed.TreeNode Root α × α →
        RootIndexed.TreeNode Root α × α,
      Set.MapsTo pairMatch (offspringPairSet source sourceSlots)
        (offspringPairSet target targetSlots) ∧
      Set.InjOn pairMatch (offspringPairSet source sourceSlots) := by
  let pairMatch : RootIndexed.TreeNode Root α × α →
      RootIndexed.TreeNode Root α × α := fun pi => (matchParent pi.1, pi.2)
  refine ⟨pairMatch, ?_, ?_⟩
  · rintro ⟨p, i⟩ ⟨hp, hi⟩
    exact ⟨hmatch_mem hp, hslot p hp hi⟩
  · rintro ⟨p, i⟩ ⟨hp, hi⟩ ⟨q, j⟩ ⟨hq, hj⟩ heq
    change (matchParent p, i) = (matchParent q, j) at heq
    obtain ⟨hparent, hchild⟩ := Prod.ext_iff.mp heq
    exact Prod.ext (hmatch_inj hp hq hparent) hchild

-- Because `childAddress` is jointly injective, the set-level pair injection
-- can be transported to child addresses without losing particle identity.
-- The pair representation remains the primary coupling witness and avoids a
-- choice of decomposition for addresses outside the candidate set.

/-- The finite candidate labels generated by a finite multi-root population.
Each parent may expose its own finite set of surviving slots. -/
noncomputable def offspringPairs
    (parents : Finset (RootIndexed.TreeNode Root α))
    (slots : RootIndexed.TreeNode Root α → Finset α) :
    Finset (RootIndexed.TreeNode Root α × α) := by
  classical
  exact parents.biUnion fun p => (slots p).image fun i => (p, i)

@[simp] theorem mem_offspringPairs
    {parents : Finset (RootIndexed.TreeNode Root α)}
    {slots : RootIndexed.TreeNode Root α → Finset α}
    {p : RootIndexed.TreeNode Root α} {i : α} :
    (p, i) ∈ offspringPairs parents slots ↔ p ∈ parents ∧ i ∈ slots p := by
  classical
  simp [offspringPairs]

/-- The finite helper is exactly the finite realization of the general
parent-slot candidate set. -/
@[simp] theorem coe_offspringPairs
    (parents : Finset (RootIndexed.TreeNode Root α))
    (slots : RootIndexed.TreeNode Root α → Finset α) :
    ↑(offspringPairs parents slots) =
      offspringPairSet (↑parents) (fun p => ↑(slots p)) := by
  classical
  ext pi
  rcases pi with ⟨p, i⟩
  simp

/-- Convert parent-slot candidate labels to their genuine multi-root child
addresses.  Joint injectivity ensures that this conversion loses neither
particle identity nor multiplicity. -/
noncomputable def offspringAddresses
    (parents : Finset (RootIndexed.TreeNode Root α))
    (slots : RootIndexed.TreeNode Root α → Finset α) :
    Finset (RootIndexed.TreeNode Root α) := by
  classical
  exact (offspringPairs parents slots).image fun pi => childAddress pi.1 pi.2

@[simp] theorem mem_offspringAddresses
    {parents : Finset (RootIndexed.TreeNode Root α)}
    {slots : RootIndexed.TreeNode Root α → Finset α}
    {q : RootIndexed.TreeNode Root α} :
    q ∈ offspringAddresses parents slots ↔
      ∃ p ∈ parents, ∃ i ∈ slots p, q = childAddress p i := by
  classical
  constructor
  · intro hq
    obtain ⟨⟨p, i⟩, hpi, hchild⟩ :=
      Finset.mem_image.mp (show q ∈ (offspringPairs parents slots).image
        (fun pi => childAddress pi.1 pi.2) from hq)
    obtain ⟨hp, hi⟩ := mem_offspringPairs.mp hpi
    exact ⟨p, hp, i, hi, hchild.symm⟩
  · rintro ⟨p, hp, i, hi, rfl⟩
    show childAddress p i ∈ (offspringPairs parents slots).image
      (fun pi => childAddress pi.1 pi.2)
    exact Finset.mem_image.mpr
      ⟨(p, i), mem_offspringPairs.mpr ⟨hp, hi⟩, rfl⟩

/-- Finite child addresses agree with the general set-valued construction. -/
@[simp] theorem coe_offspringAddresses
    (parents : Finset (RootIndexed.TreeNode Root α))
    (slots : RootIndexed.TreeNode Root α → Finset α) :
    ↑(offspringAddresses parents slots) =
      offspringAddressSet (↑parents) (fun p => ↑(slots p)) := by
  classical
  ext q
  simp

/-- Filtering genuine child addresses has the same cardinality as filtering
their unique parent-slot labels by the pulled-back predicate. -/
theorem card_filter_offspringAddresses
    (parents : Finset (RootIndexed.TreeNode Root α))
    (slots : RootIndexed.TreeNode Root α → Finset α)
    (P : RootIndexed.TreeNode Root α → Prop) [DecidablePred P] :
    ((offspringAddresses parents slots).filter P).card =
      ((offspringPairs parents slots).filter fun pi =>
        P (childAddress pi.1 pi.2)).card := by
  classical
  rw [offspringAddresses, Finset.filter_image]
  exact Finset.card_image_of_injective _ childAddress_joint_injective

/-- Shared offspring preserve the lower-tail count comparison.  A source
parent `p` is coupled to `matchParent p`; both use the same slot `i`.  The
target may contain additional parents or slots.  The sole spatial hypothesis
is that advancing the matched target parent by the shared mark lies weakly to
the left of advancing the source parent.

This is the multi-root one-generation core: `Root` is arbitrary, and the map
may match particles belonging to different roots while the child construction
retains the target particle's root. -/
theorem offspringPairs_filter_card_le
    [Preorder Value] [DecidableRel (· ≤ · : Value → Value → Prop)]
    (source target : Finset (RootIndexed.TreeNode Root α))
    (sourceSlots targetSlots : RootIndexed.TreeNode Root α → Finset α)
    (matchParent : RootIndexed.TreeNode Root α → RootIndexed.TreeNode Root α)
    (hmatch_mem : ∀ p ∈ source, matchParent p ∈ target)
    (hmatch_inj : Set.InjOn matchParent source)
    (hslot : ∀ p ∈ source, sourceSlots p ⊆ targetSlots (matchParent p))
    (sourceValue targetValue : RootIndexed.TreeNode Root α → α → Value)
    (hle : ∀ p ∈ source, ∀ i ∈ sourceSlots p,
      targetValue (matchParent p) i ≤ sourceValue p i)
    (a : Value) :
    ((offspringPairs source sourceSlots).filter fun
        (pi : RootIndexed.TreeNode Root α × α) =>
        sourceValue pi.1 pi.2 ≤ a).card ≤
      ((offspringPairs target targetSlots).filter fun
        (qi : RootIndexed.TreeNode Root α × α) =>
        targetValue qi.1 qi.2 ≤ a).card := by
  classical
  let pairMatch : RootIndexed.TreeNode Root α × α →
      RootIndexed.TreeNode Root α × α := fun pi => (matchParent pi.1, pi.2)
  apply Finset.card_le_card_of_injOn pairMatch
  · intro pi hpi
    rcases Finset.mem_filter.mp hpi with ⟨hpair, hvalue⟩
    rcases (mem_offspringPairs.mp hpair) with ⟨hp, hi⟩
    apply Finset.mem_filter.mpr
    exact ⟨mem_offspringPairs.mpr ⟨hmatch_mem pi.1 hp, hslot pi.1 hp hi⟩,
      (hle pi.1 hp pi.2 hi).trans hvalue⟩
  · intro pi hpi qi hqi heq
    have hp : pi.1 ∈ source :=
      (mem_offspringPairs.mp (Finset.mem_filter.mp hpi).1).1
    have hq : qi.1 ∈ source :=
      (mem_offspringPairs.mp (Finset.mem_filter.mp hqi).1).1
    change (matchParent pi.1, pi.2) = (matchParent qi.1, qi.2) at heq
    obtain ⟨hmatched, hslots⟩ := Prod.ext_iff.mp heq
    have hparents : pi.1 = qi.1 := hmatch_inj hp hq hmatched
    exact Prod.ext hparents hslots

/-- The address-order-free form of one-generation offspring propagation.
An injective spatial matching of multi-root parents, followed by compatible
shared slots, gives the lower-tail comparison of candidate pairs. -/
theorem offspringPairs_filter_card_le_of_injectivelyDominatesBy
    [Preorder Value] [DecidableRel (· ≤ · : Value → Value → Prop)]
    (φ : Position → Value) {Time : Type*}
    {C D : Cloud Time Root α Position} (t : Time)
    (hCfinite : (C.particles t).Finite)
    (hDfinite : (D.particles t).Finite)
    (hdom : C.InjectivelyDominatesBy φ D t)
    (sourceSlots targetSlots : RootIndexed.TreeNode Root α → Finset α)
    (sourceValue targetValue : RootIndexed.TreeNode Root α → α → Value)
    (hshared : ∀ p ∈ C.particles t, ∀ q ∈ D.particles t,
      φ (D.position q.1 q.2) ≤ φ (C.position p.1 p.2) →
      ∀ i ∈ sourceSlots p,
        i ∈ targetSlots q ∧ targetValue q i ≤ sourceValue p i)
    (a : Value) :
    ((offspringPairs hCfinite.toFinset sourceSlots).filter fun
        (pi : RootIndexed.TreeNode Root α × α) =>
        sourceValue pi.1 pi.2 ≤ a).card ≤
      ((offspringPairs hDfinite.toFinset targetSlots).filter fun
        (qi : RootIndexed.TreeNode Root α × α) =>
        targetValue qi.1 qi.2 ≤ a).card := by
  classical
  obtain ⟨matchParticle, hmem, hinj, hleft⟩ := hdom
  apply offspringPairs_filter_card_le hCfinite.toFinset hDfinite.toFinset
    sourceSlots targetSlots matchParticle
  · intro p hp
    apply hDfinite.mem_toFinset.mpr
    exact hmem (hCfinite.mem_toFinset.mp hp)
  · intro p hp q hq hpq
    apply hinj (hCfinite.mem_toFinset.mp hp) (hCfinite.mem_toFinset.mp hq) hpq
  · intro p hp i hi
    exact (hshared p (hCfinite.mem_toFinset.mp hp) (matchParticle p)
      (hmem (hCfinite.mem_toFinset.mp hp))
      (hleft p (hCfinite.mem_toFinset.mp hp)) i hi).1
  · intro p hp i hi
    exact (hshared p (hCfinite.mem_toFinset.mp hp) (matchParticle p)
      (hmem (hCfinite.mem_toFinset.mp hp))
      (hleft p (hCfinite.mem_toFinset.mp hp)) i hi).2

/-- Rankwise domination of two finite multi-root parent clouds yields the
lower-tail comparison for their coupled offspring candidates.  The hypothesis
`hshared` states the local fact supplied by the coupling: equal-rank matched
parents expose the same source slots in the target construction, and applying
the same slot keeps the target child weakly to the left.

This theorem composes the two formerly separate steps of the induction:
extracting an injective parent matching and propagating it through one shared
offspring step. -/
theorem offspringPairs_filter_card_le_of_rankwiseDominatesBy
    [LinearOrder (RootIndexed.TreeNode Root α)] [Preorder Value]
    [DecidableRel (· ≤ · : Value → Value → Prop)]
    (φ : Position → Value) {Time : Type*}
    {C D : Cloud Time Root α Position} (t : Time)
    (hCfinite : (C.particles t).Finite)
    (hDfinite : (D.particles t).Finite)
    (hdom : C.RankwiseDominatesBy φ D t)
    (sourceSlots targetSlots : RootIndexed.TreeNode Root α → Finset α)
    (sourceValue targetValue : RootIndexed.TreeNode Root α → α → Value)
    (hshared : ∀ p ∈ C.particles t, ∀ q ∈ D.particles t,
      (D.mapPosition φ).sliceRank t q = (C.mapPosition φ).sliceRank t p →
      φ (D.position q.1 q.2) ≤ φ (C.position p.1 p.2) →
      ∀ i ∈ sourceSlots p,
        i ∈ targetSlots q ∧ targetValue q i ≤ sourceValue p i)
    (a : Value) :
    ((offspringPairs hCfinite.toFinset sourceSlots).filter fun
        (pi : RootIndexed.TreeNode Root α × α) =>
        sourceValue pi.1 pi.2 ≤ a).card ≤
      ((offspringPairs hDfinite.toFinset targetSlots).filter fun
        (qi : RootIndexed.TreeNode Root α × α) =>
        targetValue qi.1 qi.2 ≤ a).card := by
  classical
  obtain ⟨matchParticle, hmem, hinj, hrank, hleft⟩ :=
    Cloud.exists_injective_match_of_rankwiseDominatesBy_of_finite
      φ t hCfinite hdom
  apply offspringPairs_filter_card_le hCfinite.toFinset hDfinite.toFinset
    sourceSlots targetSlots matchParticle
  · intro p hp
    apply hDfinite.mem_toFinset.mpr
    exact hmem (hCfinite.mem_toFinset.mp hp)
  · intro p hp q hq hpq
    apply hinj (hCfinite.mem_toFinset.mp hp) (hCfinite.mem_toFinset.mp hq) hpq
  · intro p hp i hi
    exact (hshared p (hCfinite.mem_toFinset.mp hp) (matchParticle p)
      (hmem (hCfinite.mem_toFinset.mp hp))
      (hrank p (hCfinite.mem_toFinset.mp hp))
      (hleft p (hCfinite.mem_toFinset.mp hp)) i hi).1
  · intro p hp i hi
    exact (hshared p (hCfinite.mem_toFinset.mp hp) (matchParticle p)
      (hmem (hCfinite.mem_toFinset.mp hp))
      (hrank p (hCfinite.mem_toFinset.mp hp))
      (hleft p (hCfinite.mem_toFinset.mp hp)) i hi).2


end Combinatorics.Branching.Selection.Coupling

end
