import Mathlib.Data.Finset.Sigma
import Combinatorics.UlamHarris.Basic

/-!
# Multi-root offspring coupling

This file isolates the combinatorial step used when a coupling gives matched
parents the same offspring marks.  Roots are arbitrary: a parent is a member
of `RootIndexed.TreeNode Root α`, and no enumeration or countability assumption
is made on `Root` or on the slot type.  Finiteness enters only through the two
finite populations and the finite set of slots actually used at this step.

Candidates are first represented by `(parent, slot)` pairs.  This representation
retains multiplicity and makes the parent matching visibly injective.  Turning a
pair into the address obtained by appending its slot is a separate, deterministic
operation.
-/

namespace Combinatorics.Branching.Selection.Coupling

open Combinatorics.UlamHarris

variable {Root α Position Value : Type*}

/-- Append a child slot to a parent address without changing its root. -/
def childAddress (p : RootIndexed.TreeNode Root α) (i : α) :
    RootIndexed.TreeNode Root α :=
  (p.1, p.2 ++ [i])

@[simp] theorem childAddress_fst (p : RootIndexed.TreeNode Root α) (i : α) :
    (childAddress p i).1 = p.1 :=
  rfl

@[simp] theorem childAddress_snd (p : RootIndexed.TreeNode Root α) (i : α) :
    (childAddress p i).2 = p.2 ++ [i] :=
  rfl

/-- Parent and child slot are recoverable from the resulting multi-root child
address.  In particular, different roots can never be conflated. -/
theorem childAddress_joint_injective :
    Function.Injective (fun pi : RootIndexed.TreeNode Root α × α =>
      childAddress pi.1 pi.2) := by
  rintro ⟨p, i⟩ ⟨q, j⟩ h
  change (p.1, p.2 ++ [i]) = (q.1, q.2 ++ [j]) at h
  obtain ⟨hroot, hlist⟩ := Prod.ext_iff.mp h
  have hparts := List.append_inj' hlist (by simp)
  have hparent : p.2 = q.2 := hparts.1
  have hslot : i = j := by simpa using hparts.2
  cases p
  cases q
  simp_all

/-- The finite candidate labels generated by a finite multi-root population.
Each parent may expose its own finite set of surviving slots. -/
def offspringPairs [DecidableEq (RootIndexed.TreeNode Root α)] [DecidableEq α]
    (parents : Finset (RootIndexed.TreeNode Root α))
    (slots : RootIndexed.TreeNode Root α → Finset α) :
    Finset (RootIndexed.TreeNode Root α × α) :=
  parents.biUnion fun p => (slots p).image fun i => (p, i)

@[simp] theorem mem_offspringPairs
    [DecidableEq (RootIndexed.TreeNode Root α)] [DecidableEq α]
    {parents : Finset (RootIndexed.TreeNode Root α)}
    {slots : RootIndexed.TreeNode Root α → Finset α}
    {p : RootIndexed.TreeNode Root α} {i : α} :
    (p, i) ∈ offspringPairs parents slots ↔ p ∈ parents ∧ i ∈ slots p := by
  classical
  simp [offspringPairs]

/-- Shared offspring preserve the lower-tail count comparison.  A source
parent `p` is coupled to `matchParent p`; both use the same slot `i`.  The
target may contain additional parents or slots.  The sole spatial hypothesis
is that advancing the matched target parent by the shared mark lies weakly to
the left of advancing the source parent.

This is the multi-root one-generation core: `Root` is arbitrary, and the map
may match particles belonging to different roots while the child construction
retains the target particle's root. -/
theorem offspringPairs_filter_card_le
    [DecidableEq (RootIndexed.TreeNode Root α)] [DecidableEq α]
    [Preorder Value] [DecidableRel (· ≤ · : Value → Value → Prop)]
    (source target : Finset (RootIndexed.TreeNode Root α))
    (sourceSlots targetSlots : RootIndexed.TreeNode Root α → Finset α)
    (matchParent : RootIndexed.TreeNode Root α → RootIndexed.TreeNode Root α)
    (hmatch_mem : ∀ p ∈ source, matchParent p ∈ target)
    (hmatch_inj : Set.InjOn matchParent source)
    (hslot : ∀ p ∈ source, sourceSlots p ⊆ targetSlots (matchParent p))
    (sourceValue targetValue : RootIndexed.TreeNode Root α → α → Value)
    (hle : ∀ p ∈ source, ∀ i ∈ sourceSlots p,
      targetValue (matchParent p) i ≤ sourceValue p i)
    (a : Value) :
    ((offspringPairs source sourceSlots).filter fun
        (pi : RootIndexed.TreeNode Root α × α) =>
        sourceValue pi.1 pi.2 ≤ a).card ≤
      ((offspringPairs target targetSlots).filter fun
        (qi : RootIndexed.TreeNode Root α × α) =>
        targetValue qi.1 qi.2 ≤ a).card := by
  classical
  let pairMatch : RootIndexed.TreeNode Root α × α →
      RootIndexed.TreeNode Root α × α := fun pi => (matchParent pi.1, pi.2)
  apply Finset.card_le_card_of_injOn pairMatch
  · intro pi hpi
    rcases Finset.mem_filter.mp hpi with ⟨hpair, hvalue⟩
    rcases (mem_offspringPairs.mp hpair) with ⟨hp, hi⟩
    apply Finset.mem_filter.mpr
    exact ⟨mem_offspringPairs.mpr ⟨hmatch_mem pi.1 hp, hslot pi.1 hp hi⟩,
      (hle pi.1 hp pi.2 hi).trans hvalue⟩
  · intro pi hpi qi hqi heq
    have hp : pi.1 ∈ source :=
      (mem_offspringPairs.mp (Finset.mem_filter.mp hpi).1).1
    have hq : qi.1 ∈ source :=
      (mem_offspringPairs.mp (Finset.mem_filter.mp hqi).1).1
    change (matchParent pi.1, pi.2) = (matchParent qi.1, qi.2) at heq
    obtain ⟨hmatched, hslots⟩ := Prod.ext_iff.mp heq
    have hparents : pi.1 = qi.1 := hmatch_inj hp hq hmatched
    exact Prod.ext hparents hslots

end Combinatorics.Branching.Selection.Coupling
