import Combinatorics.UlamHarris.Tree.RootIndexed.Basic
import Combinatorics.UlamHarris.Tree.Topology
import Mathlib.Topology.Bases
import Mathlib.Topology.Constructions

/-!
# Topologies on root-indexed trees

Two non-default topologies are compared with the default one.

* The **default** topology of `RootIndexed.Tree Root α = Root → Tree α` is the
  product of the pointwise topologies of the single trees; it is the ambient
  instance, and `pointwiseTopology_eq_iInf` records it as the infimum of the
  coordinate topologies.
* `productTruncationTopology` is the product of the single-tree truncation
  topologies: it constrains finitely many initial ancestors to lie in
  truncation balls.
* `uniformTopology` is generated by the uniform balls
  `{S | ∀ r, S r ∈ truncationBall (T r) n}`, which impose the *same* level `n`
  on every initial ancestor. It is the topology induced by the sup tree metric
  of `RootIndexed.Tree/Metric.lean`.

For infinitely many initial ancestors the uniform topology is strictly finer
than the two product topologies, because a uniform ball is an infinite
intersection of coordinate constraints and is not in general product open. The
chain proved here is

`uniformTopology ≤ productTruncationTopology ≤ default topology`,

in mathlib's order on topologies, where `t ≤ s` means that `t` is finer. For
finitely many roots the uniform topology is the product of the single-tree
truncation topologies, since a finite intersection of balls becomes a single
uniform ball.
-/

open MeasureTheory
open scoped Topology
open TopologicalSpace

set_option linter.style.haveILetI false

namespace Combinatorics

namespace UlamHarris

namespace RootIndexed.Tree

variable {Root α : Type*} [LT α]

/-- The default topology of a root-indexed tree is the product of the pointwise
topologies of its coordinate trees. -/
theorem pointwiseTopology_eq_iInf :
    (inferInstance : TopologicalSpace (RootIndexed.Tree Root α)) =
      ⨅ r : Root,
        TopologicalSpace.induced (fun T : RootIndexed.Tree Root α => T r)
          (Tree.treePointwiseTopology (α := α)) :=
  rfl

/-- The product of the single-tree truncation topologies. It is a named
topology and does not replace the default product topology. -/
@[instance_reducible]
def productTruncationTopology : TopologicalSpace (RootIndexed.Tree Root α) :=
  ⨅ r : Root,
    TopologicalSpace.induced (fun T : RootIndexed.Tree Root α => T r)
      (Tree.treeTruncationTopology (α := α))

/-- The product of the truncation topologies is finer than the default product
topology, coordinate by coordinate. -/
theorem productTruncationTopology_le_pointwise :
    productTruncationTopology (Root := Root) (α := α) ≤
      (inferInstance : TopologicalSpace (RootIndexed.Tree Root α)) := by
  rw [pointwiseTopology_eq_iInf]
  exact iInf_mono fun _ =>
    induced_mono Tree.treeTruncationTopology_le_pointwise

/-- The uniform ball around `T` of level `n`: every initial ancestor agrees with
`T` up to generation `n`. -/
def uniformBall (T : RootIndexed.Tree Root α) (n : ℕ) :
    Set (RootIndexed.Tree Root α) :=
  {S | ∀ r, S r ∈ Tree.truncationBall (T r) n}

@[simp]
theorem mem_uniformBall {S T : RootIndexed.Tree Root α} {n : ℕ} :
    S ∈ uniformBall T n ↔ ∀ r, S r ∈ Tree.truncationBall (T r) n :=
  Iff.rfl

/-- A uniform ball of level zero is the whole space, because all trees have the
same truncation at level zero. -/
theorem uniformBall_zero (T : RootIndexed.Tree Root α) :
    uniformBall T 0 = Set.univ := by
  ext S
  simp [uniformBall, Tree.truncationBall_zero]

/-- Uniform balls around a fixed centre are monotone in the level. -/
theorem uniformBall_anti (T : RootIndexed.Tree Root α) {m n : ℕ} (hmn : m ≤ n) :
    uniformBall T n ⊆ uniformBall T m :=
  fun _ hS _ => Tree.truncationBall_anti (T _) hmn (hS _)

/-- If `S` and `T` agree up to generation `n`, then every tree agreeing with
`S` up to generation `n` also agrees with `T` up to generation `n`. -/
theorem uniformBall_subset_of_mem {S T : RootIndexed.Tree Root α} {n : ℕ}
    (hST : S ∈ uniformBall T n) :
    uniformBall S n ⊆ uniformBall T n := by
  intro U hUS r
  exact Tree.mem_truncationBall.2
    ((Tree.mem_truncationBall.1 (hUS r)).trans
      (Tree.mem_truncationBall.1 (hST r)))

/-- The uniform topology, generated by the uniform balls. It is the topology
induced by the sup tree metric of `RootIndexed.Tree/Metric.lean`. -/
@[instance_reducible]
def uniformTopology : TopologicalSpace (RootIndexed.Tree Root α) :=
  TopologicalSpace.generateFrom {s | ∃ T n, s = uniformBall T n}

/-- The uniform balls are open for the uniform topology. -/
theorem isOpen_uniformBall (T : RootIndexed.Tree Root α) (n : ℕ) :
    IsOpen[uniformTopology (Root := Root) (α := α)] (uniformBall T n) := by
  letI : TopologicalSpace (RootIndexed.Tree Root α) :=
    uniformTopology (Root := Root) (α := α)
  exact isOpen_generateFrom_of_mem ⟨T, n, rfl⟩

/-- The open sets of the truncation topology of a single tree form a basis of
that topology. -/
private theorem isTopologicalBasis_isOpen_truncation :
    letI : TopologicalSpace (Tree α) := Tree.treeTruncationTopology (α := α)
    IsTopologicalBasis {s : Set (Tree α) | IsOpen s} := by
  letI : TopologicalSpace (Tree α) := Tree.treeTruncationTopology (α := α)
  exact isTopologicalBasis_of_isOpen_of_nhds (fun _ h => h)
    (fun _ u ha hu => ⟨u, hu, ha, subset_rfl⟩)

/-- The product truncation topology has the expected basis: finite intersections
of coordinate truncation-open sets. -/
theorem isTopologicalBasis_productTruncation :
    @IsTopologicalBasis (RootIndexed.Tree Root α)
      (productTruncationTopology (Root := Root) (α := α))
      {S : Set (RootIndexed.Tree Root α) |
        ∃ (V : Root → Set (Tree α)) (F : Finset Root),
          (∀ r, r ∈ F → IsOpen[Tree.treeTruncationTopology (α := α)] (V r)) ∧
          S = ⋂ r ∈ F, (fun T : RootIndexed.Tree Root α => T r) ⁻¹' V r} := by
  letI : TopologicalSpace (RootIndexed.Tree Root α) :=
    productTruncationTopology (Root := Root) (α := α)
  have h := IsTopologicalBasis.iInf_induced
    (t := fun _ : Root => Tree.treeTruncationTopology (α := α))
    (T := fun _ : Root =>
      {s : Set (Tree α) | IsOpen[Tree.treeTruncationTopology (α := α)] s})
    (cond := fun _ => isTopologicalBasis_isOpen_truncation (α := α))
    (f := fun (r : Root) (T : RootIndexed.Tree Root α) => T r)
  rw [show productTruncationTopology (Root := Root) (α := α) =
      ⨅ r : Root,
        TopologicalSpace.induced (fun T : RootIndexed.Tree Root α => T r)
          (Tree.treeTruncationTopology (α := α)) from rfl]
  simpa only [Set.mem_ofPred_eq] using h

/-- Every open set of the product truncation topology contains a uniform ball
around each of its points: a finite list of coordinates only constrains
finitely many levels, and the largest of them is a uniform level. -/
theorem exists_uniformBall_subset_of_isOpen_productTruncation
    {U : Set (RootIndexed.Tree Root α)}
    (hU : IsOpen[productTruncationTopology (Root := Root) (α := α)] U)
    {T : RootIndexed.Tree Root α} (hT : T ∈ U) :
    ∃ n : ℕ, uniformBall T n ⊆ U := by
  classical
  letI : TopologicalSpace (RootIndexed.Tree Root α) :=
    productTruncationTopology (Root := Root) (α := α)
  obtain ⟨b, hb, hTb, hbU⟩ :=
    (isTopologicalBasis_productTruncation (Root := Root) (α := α)).exists_subset_of_mem_open
      hT hU
  rcases hb with ⟨V, F, hVF, rfl⟩
  have hTV : ∀ r ∈ F, T r ∈ V r := by
    intro r hr
    have h := hTb
    simp only [Set.mem_iInter, Set.mem_preimage] at h
    exact h r hr
  choose n hn using fun r (hr : r ∈ F) =>
    (Tree.isOpen_truncation_iff_ball (V r)).1 (hVF r hr) (T r) (hTV r hr)
  refine ⟨F.attach.sup (fun r => n r.1 r.2), ?_⟩
  intro S hS
  refine hbU ?_
  simp only [Set.mem_iInter, Set.mem_preimage]
  intro r hr
  refine hn r hr ?_
  have hle : n r hr ≤ F.attach.sup (fun r : {x : Root // x ∈ F} => n r.1 r.2) :=
    Finset.le_sup (f := fun r : {x : Root // x ∈ F} => n r.1 r.2)
      (Finset.mem_attach F ⟨r, hr⟩)
  exact Tree.truncationBall_anti (T r) hle (hS r)

/-- The uniform topology is finer than the product truncation topology. -/
theorem uniformTopology_le_productTruncation :
    uniformTopology (Root := Root) (α := α) ≤
      productTruncationTopology (Root := Root) (α := α) := by
  rw [TopologicalSpace.le_def]
  intro U hU
  choose n hn using fun p : {T : RootIndexed.Tree Root α // T ∈ U} =>
    exists_uniformBall_subset_of_isOpen_productTruncation hU p.2
  have hUnion : U = ⋃ p : {T : RootIndexed.Tree Root α // T ∈ U},
      uniformBall p.1 (n p) := by
    refine Set.Subset.antisymm (fun T hT => Set.mem_iUnion.2 ⟨⟨T, hT⟩, ?_⟩) ?_
    · simp [uniformBall]
    · exact Set.iUnion_subset fun p => hn p
  rw [hUnion]
  exact @isOpen_iUnion (RootIndexed.Tree Root α)
    {T : RootIndexed.Tree Root α // T ∈ U} (uniformTopology (Root := Root) (α := α))
    (fun p => uniformBall p.1 (n p)) (fun p => isOpen_uniformBall p.1 (n p))

end RootIndexed.Tree

end UlamHarris

end Combinatorics
