import Mathlib.Data.Set.Basic
import Mathlib.Order.OrderDual
import Combinatorics.BranchingWalk.Basic.Position
import Combinatorics.BranchingWalk.Basic.SurviveAlong

/-!
# Time-indexed particle clouds

A `CloudSet Time X` is a family of spatial point sets indexed by time.  It is
only the geometric image of a branching walk; the branching-step data and the
initial positions generate it in `ofRootIndexed.StepField` and `ofStepField`.
The multi-root construction is primitive: each root supplies its own step
field and initial position, and the cloud is their union.  The single-root
construction is the special case with the singleton root type `Unit`.
-/

namespace Combinatorics

namespace Branching

open Combinatorics.UlamHarris

/-- A time-indexed cloud of points in `X`. -/
structure CloudSet (Time X : Type*) where
  points : Time → Set X

/-- An indexed particle cloud. The index retains root and node identity even
when two particles have the same spatial position. -/
structure Cloud (Time Index X : Type*) where
  particles : Time → Set Index
  position : Index → X

def Cloud.support {Time Index X : Type*} (C : Cloud Time Index X) :
    CloudSet Time X where
  points t := C.position '' C.particles t

def Cloud.ofBranchingWalk
    {Time Root α X : Type*} [AddCommMonoid X]
    (β : RootIndexed.BranchingWalk Root α X)
    (time : TreeNode α → Time)
    (position : Root → TreeNode α → X) : Cloud Time (Root × TreeNode α) X where
  particles t := {p | time p.2 = t ∧ surviveAlong (β.step p.1) [] p.2}
  position p := position p.1 p.2

def CloudSet.ofBranchingWalk
    {Time Root α X : Type*} [AddCommMonoid X]
    (β : RootIndexed.BranchingWalk Root α X)
    (time : TreeNode α → Time)
    (position : Root → TreeNode α → X) : CloudSet Time X :=
  (Cloud.ofBranchingWalk β time position).support

namespace CloudSet

variable {Time X : Type*}

instance : Membership (Time × X) (CloudSet Time X) where
  mem C p := p.2 ∈ C.points p.1

/-- The space-time set of all points of a cloud. -/
def vertexSet (C : CloudSet Time X) : Set (Time × X) :=
  {p | p ∈ C}

@[simp] theorem mem_vertexSet (C : CloudSet Time X) (p : Time × X) :
    p ∈ C.vertexSet ↔ p ∈ C :=
  Iff.rfl

@[ext] theorem ext {C D : CloudSet Time X}
    (h : ∀ t x, x ∈ C.points t ↔ x ∈ D.points t) : C = D := by
  cases C with
  | mk Cpoints =>
    cases D with
    | mk Dpoints =>
      congr
      funext t
      ext x
      exact h t x

/-- The cloud generated by a root-indexed step field and root-indexed initial
positions. -/
def ofRootIndexed.StepField
    {Root α X : Type*} [AddCommMonoid X]
    (initial : Root → X) (step : Root → Branching.StepField α X)
    (time : TreeNode α → Time) : CloudSet Time X where
  points t :=
    {x | ∃ r u,
      time u = t ∧
      surviveAlong (step r) [] u ∧
      x = RootIndexed.position initial step r u}

/-- The single-root case of `ofRootIndexed.StepField`, indexed by `Unit`. -/
def ofStepField
    {α X Time : Type*} [AddCommMonoid X]
    (initial : X) (step : Branching.StepField α X)
    (time : TreeNode α → Time) : CloudSet Time X :=
  ofRootIndexed.StepField
    (fun _ : Unit => initial)
    (fun _ : Unit => step)
    time

@[simp] theorem ofRootIndexed.StepField_points
    {Root α X Time : Type*} [AddCommMonoid X]
    (initial : Root → X)
    (step : Root → Branching.StepField α X)
    (time : TreeNode α → Time) (t : Time) :
    (CloudSet.ofRootIndexed.StepField (Root := Root) (α := α) (X := X)
      initial step time).points t =
      {x | ∃ r u,
        time u = t ∧
        surviveAlong (step r) [] u ∧
        x = Branching.RootIndexed.position (X := X) initial step r u} :=
  rfl

@[simp] theorem ofStepField_points
    {α X Time : Type*} [AddCommMonoid X]
    (initial : X) (step : Branching.StepField α X)
    (time : TreeNode α → Time) (t : Time) :
    (ofStepField initial step time).points t =
      {x | ∃ u,
        time u = t ∧
        surviveAlong step [] u ∧
        x = position initial step u} := by
  ext x
  simp [ofStepField, ofRootIndexed.StepField,
    position, RootIndexed.position]

/-- Transport a cloud to the order-dual value type. Reversing the order on
positions reverses the order on every time slice. -/
def mapOrderDual (C : CloudSet Time X) : CloudSet Time (OrderDual X) where
  points t := OrderDual.toDual '' C.points t

@[simp] theorem mem_mapOrderDual_points (C : CloudSet Time X) (t : Time)
    (x : X) :
    OrderDual.toDual x ∈ (C.mapOrderDual).points t ↔ x ∈ C.points t := by
  constructor
  · rintro ⟨y, hy, hyx⟩
    have hyx' : y = x := OrderDual.toDual_inj.mp hyx
    simpa [hyx'] using hy
  · intro hx
    exact ⟨x, hx, rfl⟩

end CloudSet

end Branching

end Combinatorics
