import Mathlib.Data.Set.Basic
import Mathlib.Order.OrderDual
import Combinatorics.BranchingWalk.Cloud.Position
import Combinatorics.BranchingWalk.Basic.SurviveAlong

/-!
# Time-indexed particle clouds

A `Cloud Time X` is a family of spatial point sets indexed by time.  It is
only the geometric image of a branching walk; the branching-step data and the
initial positions generate it in `ofRootIndexedStepField` and `ofStepField`.
The multi-root construction is primitive: each root supplies its own step
field and initial position, and the cloud is their union.  The single-root
construction is the special case with the singleton root type `Unit`.
-/

namespace Combinatorics

namespace Branching

open Combinatorics.UlamHarris

/-- A time-indexed cloud of points in `X`. -/
structure Cloud (Time X : Type*) where
  points : Time → Set X

namespace Cloud

variable {Time X : Type*}

instance : Membership (Time × X) (Cloud Time X) where
  mem C p := p.2 ∈ C.points p.1

/-- The space-time set of all points of a cloud. -/
def vertexSet (C : Cloud Time X) : Set (Time × X) :=
  {p | p ∈ C}

@[simp] theorem mem_vertexSet (C : Cloud Time X) (p : Time × X) :
    p ∈ C.vertexSet ↔ p ∈ C :=
  Iff.rfl

@[ext] theorem ext {C D : Cloud Time X}
    (h : ∀ t x, x ∈ C.points t ↔ x ∈ D.points t) : C = D := by
  cases C with
  | mk Cpoints =>
    cases D with
    | mk Dpoints =>
      congr
      funext t
      ext x
      exact h t x

/-- The cloud generated by a root-indexed step field and root-indexed initial
positions. -/
def ofRootIndexedStepField
    {Root α X : Type*} [AddCommMonoid X]
    (initial : Root → X) (step : Root → StepField α X)
    (time : TreeNode α → Time) : Cloud Time X where
  points t :=
    {x | ∃ r u,
      time u = t ∧
      surviveAlong (step r) [] u ∧
      x = RootIndexed.position initial step r u}

/-- The single-root case of `ofRootIndexedStepField`, indexed by `Unit`. -/
def ofStepField
    {α X Time : Type*} [AddCommMonoid X]
    (initial : X) (step : StepField α X)
    (time : TreeNode α → Time) : Cloud Time X :=
  ofRootIndexedStepField
    (fun _ : Unit => initial)
    (fun _ : Unit => step)
    time

@[simp] theorem ofRootIndexedStepField_points
    {Root α X Time : Type*} [AddCommMonoid X]
    (initial : Root → X) (step : Root → StepField α X)
    (time : TreeNode α → Time) (t : Time) :
    (ofRootIndexedStepField initial step time).points t =
      {x | ∃ r u,
        time u = t ∧
        surviveAlong (step r) [] u ∧
        x = RootIndexed.position initial step r u} :=
  rfl

@[simp] theorem ofStepField_points
    {α X Time : Type*} [AddCommMonoid X]
    (initial : X) (step : StepField α X)
    (time : TreeNode α → Time) (t : Time) :
    (ofStepField initial step time).points t =
      {x | ∃ u,
        time u = t ∧
        surviveAlong step [] u ∧
        x = position initial step u} := by
  ext x
  simp [ofStepField, ofRootIndexedStepField,
    position, RootIndexed.position]

/-- Transport a cloud to the order-dual value type. Reversing the order on
positions reverses the order on every time slice. -/
def mapOrderDual (C : Cloud Time X) : Cloud Time (OrderDual X) where
  points t := OrderDual.toDual '' C.points t

@[simp] theorem mem_mapOrderDual_points (C : Cloud Time X) (t : Time)
    (x : X) :
    OrderDual.toDual x ∈ (C.mapOrderDual).points t ↔ x ∈ C.points t := by
  constructor
  · rintro ⟨y, hy, hyx⟩
    have hyx' : y = x := OrderDual.toDual_inj.mp hyx
    simpa [hyx'] using hy
  · intro hx
    exact ⟨x, hx, rfl⟩

end Cloud

end Branching

end Combinatorics
