/-
Copyright (c) 2026 WANG Yiyang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: WANG Yiyang
-/

module

public import Probability.BranchingProcess.GaltonWatson.Generation
public import Probability.BranchingProcess.Offspring.Map
public import Probability.BranchingRandomWalk.Step.Map
public import Probability.BranchingRandomWalk.IID

/-!
# Forgetting marks to obtain a presampled Galton--Watson law

This is the marked-walk adapter only. The tree-valued law and generation
observations are defined in `Probability.BranchingProcess.GaltonWatson` from
an offspring configuration law. That law retains the complete independently
sampled field, including configurations at addresses never realized in the
genealogy.
-/

@[expose] public section

namespace ProbabilityTheory.BranchingRandomWalk

open MeasureTheory

/-- The canonical i.i.d. branching walk with unit marks and unit initial
position is the presampled unmarked law generated by the same offspring
configuration law. -/
theorem iid_unit_eq_galtonWatson_law {ι : Type*}
    (μ : ProbabilityTheory.BranchingProcess.OffspringConfigurationLaw
      ι PUnit.{1}) :
    ProbabilityTheory.BranchingRandomWalk.iid
        (μ : Measure (Combinatorics.Branching.Step ι PUnit.{1}))
        PUnit.unit =
      ProbabilityTheory.BranchingProcess.GaltonWatson.law μ := by
  apply ProbabilityMeasure.toMeasure_injective
  rw [ProbabilityTheory.BranchingRandomWalk.iid_toMeasure,
    ProbabilityTheory.BranchingProcess.GaltonWatson.law,
    ProbabilityMeasure.toMeasure_map]
  let rootFieldToField :
      ProbabilityTheory.BranchingRandomWalk.RootIndexed.StepField
          PUnit.{1} ι PUnit.{1} →
        Combinatorics.Branching.StepField ι PUnit.{1} :=
    fun field => field PUnit.unit
  have heval : Measurable rootFieldToField :=
    measurable_pi_apply PUnit.unit
  have hrealize :
      ProbabilityTheory.BranchingRandomWalk.iidRealization
          (α := ι) (Mark := PUnit.{1}) PUnit.unit =
        Combinatorics.Branching.branchingOfStepField ∘ rootFieldToField := by
    rfl
  rw [hrealize, ← Measure.map_map
    Combinatorics.Branching.measurable_branchingOfStepField heval]
  rw [ProbabilityTheory.BranchingRandomWalk.RootIndexed.stepFieldLaw_root_marginal
    (Root := PUnit.{1})
    (μ := (μ : Measure (Combinatorics.Branching.Step ι PUnit.{1})))
    PUnit.unit]
  rw [ProbabilityTheory.BranchingProcess.OffspringConfigurationLaw.fieldLaw_toMeasure]
  rfl

/-- Forgetting every child mark in an i.i.d. branching walk gives the
Galton--Watson law generated by the projected offspring-configuration law. -/
theorem iid_forgetMarks_eq_galtonWatson_law {ι Mark : Type*}
    [MeasurableSpace Mark]
    (μ : ProbabilityTheory.BranchingProcess.OffspringConfigurationLaw ι Mark) :
    (ProbabilityTheory.BranchingRandomWalk.iid
      (μ : Measure (Combinatorics.Branching.Step ι Mark)) PUnit.unit).map
        (Combinatorics.Branching.RootIndexed.BranchingWalk.mapMarks
          (fun _ : Mark => PUnit.unit.{1})) =
      ProbabilityTheory.BranchingProcess.GaltonWatson.law
        (μ.mapMarks (fun _ : Mark => PUnit.unit.{1}) measurable_const) := by
  calc
    (ProbabilityTheory.BranchingRandomWalk.iid
      (μ : Measure (Combinatorics.Branching.Step ι Mark)) PUnit.unit).map
        (Combinatorics.Branching.RootIndexed.BranchingWalk.mapMarks
          (fun _ : Mark => PUnit.unit.{1})) =
      ProbabilityTheory.BranchingRandomWalk.iid
        ((μ.mapMarks (fun _ : Mark => PUnit.unit.{1}) measurable_const :
          ProbabilityTheory.BranchingProcess.OffspringConfigurationLaw
            ι PUnit.{1}) :
          Measure (Combinatorics.Branching.Step ι PUnit.{1})) PUnit.unit := by
            simpa only [
              ProbabilityTheory.BranchingProcess.OffspringConfigurationLaw.mapMarks_toMeasure] using
              (ProbabilityTheory.BranchingRandomWalk.iid_mapMarks
                (μ : Measure (Combinatorics.Branching.Step ι Mark))
                PUnit.unit (fun _ : Mark => PUnit.unit.{1})
                measurable_const).symm
    _ = ProbabilityTheory.BranchingProcess.GaltonWatson.law
        (μ.mapMarks (fun _ : Mark => PUnit.unit.{1}) measurable_const) :=
          iid_unit_eq_galtonWatson_law _

/-- Forget the spatial marks of a random step and use the resulting offspring
configuration law to construct its Galton--Watson genealogy. -/
noncomputable def StepPresentation.toGaltonWatsonLaw
    {Ω ι X : Type*} [MeasurableSpace Ω] [MeasurableSpace X]
    (S : StepPresentation Ω ι X) (P : Measure Ω) [IsProbabilityMeasure P] :
    ProbabilityMeasure (Combinatorics.Branching.Process ι) :=
  ProbabilityTheory.BranchingProcess.GaltonWatson.law
    ((S.unmarkedLaw P).toProbabilityMeasure)

end ProbabilityTheory.BranchingRandomWalk

end
