/-
Copyright (c) 2026 WANG Yiyang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: WANG Yiyang
-/

module

public import Mathlib.Algebra.BigOperators.Fin

/-!
# Additive paths

An additive path records the positions obtained by accumulating an increment
sequence. It carries no probability or branching structure.
-/

open scoped BigOperators

@[expose] public section

namespace AdditivePath

variable {E : Type*} [AddCommMonoid E]

/-- The displacement accumulated from the first `n` increments. -/
def displacement (n : ℕ) (increment : ℕ → E) : E :=
  ∑ k ∈ Finset.range n, increment k

/-- The path with initial position `initial` and increment sequence
`increment`. -/
def fromIncrements (initial : E) (increment : ℕ → E) : ℕ → E :=
  fun n => initial + displacement n increment

@[simp] theorem fromIncrements_apply (initial : E) (increment : ℕ → E)
    (n : ℕ) :
    fromIncrements initial increment n = initial + displacement n increment := rfl

/-- The finite path generated by a finite vector of increments. Its prefix
sum is Mathlib's `Fin.partialSum`. -/
def finitePrefix {n : ℕ} (initial : E) (increment : Fin n → E) :
    Fin (n + 1) → E :=
  fun k => initial + Fin.partialSum increment k

@[simp] theorem displacement_zero (increment : ℕ → E) :
    displacement 0 increment = 0 := by
  simp [displacement]

theorem displacement_succ (n : ℕ) (increment : ℕ → E) :
    displacement (n + 1) increment =
      displacement n increment + increment n := by
  simp [displacement, Finset.sum_range_succ]

/-- Splitting an accumulated displacement at a deterministic time. -/
theorem displacement_add (m n : ℕ) (increment : ℕ → E) :
    displacement (m + n) increment =
      displacement m increment +
        displacement n (fun k => increment (m + k)) := by
  induction n with
  | zero => simp [displacement]
  | succ n ih =>
      rw [Nat.add_succ, displacement_succ, ih, displacement_succ]
      ac_rfl

@[simp] theorem fromIncrements_zero (initial : E) (increment : ℕ → E) :
    fromIncrements initial increment 0 = initial := by
  simp [fromIncrements]

theorem fromIncrements_succ (initial : E) (increment : ℕ → E) (n : ℕ) :
    fromIncrements initial increment (n + 1) =
      fromIncrements initial increment n + increment n := by
  simp only [fromIncrements, displacement_succ]
  ac_rfl

section AddCommGroup

variable {G : Type*} [AddCommGroup G]

/-- Negating every increment negates its accumulated displacement. -/
@[simp] theorem displacement_neg (n : ℕ) (increment : ℕ → G) :
    displacement n (fun k => -increment k) =
      -displacement n increment := by
  simp [displacement]

end AddCommGroup

@[simp] theorem finitePrefix_zero {n : ℕ} (initial : E)
    (increment : Fin n → E) :
    finitePrefix initial increment 0 = initial := by
  simp [finitePrefix]

theorem finitePrefix_succ {n : ℕ} (initial : E)
    (increment : Fin n → E) (k : Fin n) :
    finitePrefix initial increment k.succ =
      finitePrefix initial increment k.castSucc + increment k := by
  simp only [finitePrefix, Fin.partialSum_succ]
  ac_rfl

end AdditivePath

end
