import Combinatorics.UlamHarris.RootIndexedTree.Basic
import Mathlib.MeasureTheory.MeasurableSpace.Constructions
import Mathlib.MeasureTheory.MeasurableSpace.Instances

/-!
# The cylinder σ-algebra on root-indexed trees

`RootIndexed.Tree Root α` carries the product σ-algebra of the tree σ-algebras,
which is the σ-algebra generated by the coordinate memberships
`T ↦ (u ∈ (T r).carrier)`. It is the smallest σ-algebra making all of those
coordinates measurable, so a map into a root-indexed tree is measurable exactly
when the membership set of every address of every root is measurable.

This is the multi-root analogue of `Tree/Basic.lean`, where the cylinder
σ-algebra is the one induced by the carrier; `measurable_iff_forall_mem_carrier`
is the compatibility statement the random-tree constructions use.
-/

open MeasureTheory

namespace Combinatorics

namespace UlamHarris

namespace RootIndexed.Tree

variable {Root α : Type*} [LT α]

/-- The measurable space of a root-indexed tree is the product σ-algebra of
the tree σ-algebras of the initial ancestors. -/
theorem measurableSpace_eq_iSup :
    (inferInstance : MeasurableSpace (RootIndexed.Tree Root α)) =
      ⨆ r : Root,
        MeasurableSpace.comap (fun T : RootIndexed.Tree Root α => T r)
          inferInstance :=
  rfl

/-- Each initial ancestor of a root-indexed tree is separately measurable. -/
theorem measurable_apply (r : Root) :
    Measurable (fun T : RootIndexed.Tree Root α => T r) :=
  measurable_pi_apply r

/-- Membership of a fixed address of a fixed initial ancestor is measurable. -/
theorem measurableSet_carrier (r : Root) (u : List α) :
    MeasurableSet {T : RootIndexed.Tree Root α | u ∈ (T r).carrier} :=
  (UlamHarris.measurableSet_carrier u).preimage (measurable_apply r)

/-- The σ-algebra of a root-indexed tree contains the cylinder sets, in the
form used by the generator characterization. -/
theorem generateFrom_carrier_le :
    MeasurableSpace.generateFrom
        {s : Set (RootIndexed.Tree Root α) |
          ∃ r u, s = {T : RootIndexed.Tree Root α | u ∈ (T r).carrier}} ≤
      (inferInstance : MeasurableSpace (RootIndexed.Tree Root α)) :=
  MeasurableSpace.generateFrom_le (by
    rintro s ⟨r, u, rfl⟩
    exact measurableSet_carrier r u)

/-- A proposition-valued map is measurable exactly when its truth set is
measurable. The σ-algebra on `Prop` is discrete, so this is the only content of
measurability into `Prop`. -/
theorem measurable_prop_iff {β : Type*} [MeasurableSpace β] (p : β → Prop) :
    Measurable p ↔ MeasurableSet {x | p x} :=
  measurableSet_setOfPred.symm

/-- A map into a root-indexed tree is measurable exactly when the membership
set of every address of every initial ancestor is measurable. In other words
the product σ-algebra is the smallest σ-algebra making all coordinate
memberships measurable. -/
theorem measurable_iff_forall_mem_carrier {β : Type*} [MeasurableSpace β]
    (f : β → RootIndexed.Tree Root α) :
    Measurable f ↔
      ∀ (r : Root) (u : List α), MeasurableSet {x | u ∈ (f x r).carrier} := by
  constructor
  · intro hf r u
    exact (UlamHarris.measurableSet_carrier u).preimage
      ((measurable_apply r).comp hf)
  · intro h
    rw [measurable_pi_iff]
    intro r
    rw [measurable_comap_iff]
    rw [measurable_set_iff]
    intro u
    exact (measurableSet_setOfPred).1 (h r u)

end RootIndexed.Tree

end UlamHarris

end Combinatorics
