/-
Copyright (c) 2026 WANG Yiyang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: WANG Yiyang
-/

module

public import Algebra.BigOperators.AdditivePath
public import Mathlib.MeasureTheory.Group.Arithmetic

/-!
# Increment paths of random walks

This module gives the process realization and finite histories used by the
random-walk probability theory. The underlying additive path arithmetic is in
`Algebra.BigOperators.AdditivePath`.
-/

open MeasureTheory
open scoped BigOperators

@[expose] public section

namespace ProbabilityTheory.RandomWalk

variable {E : Type*} [AddCommMonoid E]

/-- Position at time `n` for an increment sequence, as a process realization
map on the increment-path sample space. -/
def positionProcess (initial : E) : ℕ → (ℕ → E) → E :=
  fun n increment => AdditivePath.fromIncrements initial increment n

@[simp] theorem positionProcess_zero (initial : E) (increment : ℕ → E) :
    positionProcess initial 0 increment = initial := by
  simp [positionProcess]

theorem positionProcess_succ (initial : E) (increment : ℕ → E) (n : ℕ) :
    positionProcess initial (n + 1) increment =
      positionProcess initial n increment + increment n := by
  exact AdditivePath.fromIncrements_succ initial increment n

theorem displacement_measurable [MeasurableSpace E] [MeasurableAdd₂ E]
    (n : ℕ) : Measurable (AdditivePath.displacement (E := E) n) := by
  unfold AdditivePath.displacement
  exact Finset.measurable_sum (Finset.range n)
    (fun k _ => measurable_pi_apply k)

omit [AddCommMonoid E] in
/-- Dropping a deterministic prefix is a measurable map on increment paths. -/
theorem measurable_natAdd [MeasurableSpace E] (offset : ℕ) :
    Measurable (fun increment : ℕ → E => fun n => increment (offset + n)) := by
  rw [measurable_pi_iff]
  exact fun n => measurable_pi_apply (offset + n)

/-- Every coordinate of the position process is measurable. -/
theorem positionProcess_measurable [MeasurableSpace E] [MeasurableAdd₂ E]
    (initial : E) (n : ℕ) : Measurable (positionProcess initial n) := by
  exact measurable_const.add (displacement_measurable n)

/-- The full position-path map is measurable in the product sigma algebra. -/
theorem positionProcess_path_measurable
    [MeasurableSpace E] [MeasurableAdd₂ E] (initial : E) :
    Measurable (fun increment : ℕ → E => fun n =>
      positionProcess initial n increment) := by
  rw [measurable_pi_iff]
  exact positionProcess_measurable initial

/-- The finite path at times `0, ..., n` generated by an increment sequence. -/
def history (n : ℕ) (initial : E) (increment : ℕ → E) :
    Fin (n + 1) → E :=
  AdditivePath.finitePrefix initial (fun k : Fin n => increment k)

@[simp] theorem history_eq_fromIncrements (n : ℕ) (initial : E)
    (increment : ℕ → E) :
    history n initial increment =
      fun k : Fin (n + 1) => AdditivePath.fromIncrements initial increment k :=
  AdditivePath.finitePrefix_restrict_eq_fromIncrements initial increment

@[simp] theorem history_zero (n : ℕ) (initial : E) (increment : ℕ → E) :
    history n initial increment 0 = initial := by
  simp [history]

theorem history_last (n : ℕ) (initial : E) (increment : ℕ → E) :
    history n initial increment ⟨n, Nat.lt_succ_self n⟩ =
      AdditivePath.fromIncrements initial increment n := by
  rw [history_eq_fromIncrements]

/-- Restarting an additive path at time `m` gives the corresponding segment
of the original path. -/
theorem history_restart (m n : ℕ) (initial : E) (increment : ℕ → E)
    (k : Fin (n + 1)) :
    history n (initial + AdditivePath.displacement m increment)
        (fun j => increment (m + j)) k =
      history (m + n) initial increment
        ⟨m + k, Nat.add_lt_add_left k.isLt m⟩ := by
  simp only [history_eq_fromIncrements, AdditivePath.fromIncrements]
  rw [AdditivePath.displacement_add]
  ac_rfl

theorem history_measurable [MeasurableSpace E] [MeasurableAdd₂ E]
    (n : ℕ) (initial : E) : Measurable (history n initial) := by
  rw [measurable_pi_iff]
  intro k
  change Measurable (fun increment : ℕ → E =>
    AdditivePath.finitePrefix initial (fun j : Fin n => increment j) k)
  have hEq : (fun increment : ℕ → E =>
      AdditivePath.finitePrefix initial (fun j : Fin n => increment j) k) =
      positionProcess initial k := by
    funext increment
    change AdditivePath.finitePrefix initial
      (fun j : Fin n => increment j) k =
        AdditivePath.fromIncrements initial increment k
    exact congrFun
      (AdditivePath.finitePrefix_restrict_eq_fromIncrements initial increment) k
  rw [hEq]
  exact positionProcess_measurable initial k

theorem history_joint_measurable [MeasurableSpace E] [MeasurableAdd₂ E]
    (n : ℕ) :
    Measurable (fun p : E × (ℕ → E) => history n p.1 p.2) := by
  rw [measurable_pi_iff]
  intro k
  have h : Measurable (fun p : E × (ℕ → E) =>
      p.1 + AdditivePath.displacement (E := E) k p.2) :=
    measurable_fst.add ((displacement_measurable k).comp measurable_snd)
  simpa only [history_eq_fromIncrements, AdditivePath.fromIncrements,
    Function.comp_apply] using h

/-- Add the initial position in front of a nonempty finite path. -/
def prependHistory {n : ℕ} (initial : E) (tail : Fin (n + 1) → E) :
    Fin (n + 2) → E :=
  Fin.cases initial tail

/-- The increment sequence after its first step. -/
def incrementTail (increment : ℕ → E) : ℕ → E :=
  fun k => increment (k + 1)

omit [AddCommMonoid E] in
@[simp] theorem prependHistory_zero {n : ℕ} (initial : E)
    (tail : Fin (n + 1) → E) : prependHistory initial tail 0 = initial := rfl

omit [AddCommMonoid E] in
@[simp] theorem prependHistory_succ {n : ℕ} (initial : E)
    (tail : Fin (n + 1) → E) (k : Fin (n + 1)) :
    prependHistory initial tail k.succ = tail k := rfl

omit [AddCommMonoid E] in
theorem prependHistory_joint_measurable [MeasurableSpace E] (n : ℕ) :
    Measurable (fun p : E × (Fin (n + 1) → E) =>
      prependHistory p.1 p.2) := by
  rw [measurable_pi_iff]
  intro k
  refine Fin.cases ?_ (fun j => ?_) k
  · exact measurable_fst
  · exact (measurable_pi_apply j).comp measurable_snd

omit [AddCommMonoid E] in
theorem incrementTail_measurable [MeasurableSpace E] :
    Measurable (incrementTail (E := E)) := by
  rw [measurable_pi_iff]
  intro k
  exact measurable_pi_apply (k + 1)

/-- Splitting off the first increment from a displacement. -/
theorem displacement_succ_eq_head_add_tail (n : ℕ)
    (increment : ℕ → E) :
    AdditivePath.displacement (n + 1) increment =
      increment 0 + AdditivePath.displacement n (incrementTail increment) := by
  induction n with
  | zero => simp [AdditivePath.displacement]
  | succ n ih =>
      rw [AdditivePath.displacement_succ, ih,
        AdditivePath.displacement_succ]
      simp only [incrementTail]
      ac_rfl

/-- The finite path has the expected first-step decomposition. -/
theorem history_succ (n : ℕ) (initial : E) (increment : ℕ → E) :
    history (n + 1) initial increment =
      prependHistory initial
        (history n (initial + increment 0) (incrementTail increment)) := by
  funext k
  refine Fin.cases ?_ (fun j => ?_) k
  · simp [history_eq_fromIncrements, prependHistory_zero]
  · simp only [history_eq_fromIncrements, prependHistory_succ]
    change initial + AdditivePath.displacement (j.val + 1) increment =
      initial + increment 0 +
        AdditivePath.displacement j.val (incrementTail increment)
    rw [displacement_succ_eq_head_add_tail]
    ac_rfl

end ProbabilityTheory.RandomWalk

end
