import Probability.BranchingRandomWalk.Walk.Law
import Probability.Measure.ConvolutionPower
import Mathlib.MeasureTheory.Group.Arithmetic
import Mathlib.Probability.Kernel.Composition.CompProd
import Mathlib.Probability.Kernel.Composition.MapComap
import Mathlib.Probability.Kernel.Composition.MeasureComp

/-!
# Transition kernels of random walks

An increment law induces the translation invariant Markov kernel sending a
position `x` to the law of `x + Z`.  This is the kernel interface of an
independent increment random walk; the walk itself remains the singleton-slot
specialization of a branching random walk.
-/

open MeasureTheory
open scoped ProbabilityTheory

namespace ProbabilityTheory.BranchingRandomWalk.RandomWalk

variable {E : Type*} [MeasurableSpace E] [AddCommMonoid E] [MeasurableAdd₂ E]

/-- The transition kernel generated by an additive increment law. -/
noncomputable def incrementKernel (ν : Measure E) [SFinite ν] : Kernel E E :=
  Kernel.map
    ((Kernel.id : Kernel E E) ⊗ₖ Kernel.const (E × E) ν)
    (fun p : E × E => p.1 + p.2)

noncomputable instance incrementKernel.instIsMarkovKernel
    (ν : Measure E) [IsProbabilityMeasure ν] :
    IsMarkovKernel (incrementKernel ν) := by
  unfold incrementKernel
  exact Kernel.IsMarkovKernel.map _ measurable_add

/-- At `x`, the increment kernel is the pushforward of the increment law by
translation by `x`. -/
theorem incrementKernel_apply [MeasurableSingletonClass E]
    (ν : Measure E) [SFinite ν] (x : E) :
    incrementKernel ν x = ν.map (fun z => x + z) := by
  ext s hs
  rw [incrementKernel, Kernel.map_apply' _ measurable_add _ hs,
    Kernel.compProd_apply (measurable_add hs) _ _ _]
  simp only [Kernel.id_apply, Kernel.const_apply]
  rw [lintegral_dirac]
  rw [Measure.map_apply (measurable_const_add x) hs]
  rfl

/-- Applying the transition kernel to a position law convolves that law with
the increment law. -/
theorem incrementKernel_comp [MeasurableSingletonClass E]
    (ν μ : Measure E) [SFinite ν] [SFinite μ] :
    incrementKernel ν ∘ₘ μ = μ ∗ ν := by
  ext s hs
  rw [Measure.bind_apply hs (Kernel.aemeasurable _)]
  simp_rw [incrementKernel_apply ν, Measure.map_apply (measurable_const_add _) hs]
  rw [← lintegral_indicator_one hs]
  calc
    (∫⁻ a, ν ((fun z => a + z) ⁻¹' s) ∂μ) =
        ∫⁻ a, ∫⁻ z, s.indicator 1 (a + z) ∂ν ∂μ := by
      congr with a
      rw [← lintegral_indicator_one (hs.preimage (measurable_const_add a))]
      rfl
    _ = ∫⁻ a, s.indicator 1 a ∂(μ ∗ ν) :=
      (Measure.lintegral_conv (measurable_const.indicator hs)).symm

omit [AddCommMonoid E] [MeasurableAdd₂ E] in
private theorem kernel_pow_succ_apply (κ : Kernel E E)
    [IsSFiniteKernel κ] (n : ℕ) (x : E) :
    (κ ^ (n + 1)) x = κ ∘ₘ ((κ ^ n) x) := by
  ext s hs
  rw [Kernel.pow_succ_apply_eq_lintegral κ n x hs,
    Measure.bind_apply hs (Kernel.aemeasurable _)]

/-- The `n`-step transition law is translation of the `n`-fold convolution
of the increment law.  This is the Chapman--Kolmogorov form of the random
walk law. -/
theorem incrementKernel_pow_apply [MeasurableSingletonClass E]
    (ν : Measure E) [IsProbabilityMeasure ν] (n : ℕ) (x : E) :
    (incrementKernel ν ^ n) x =
      Measure.dirac x ∗ ν.convPow n := by
  induction n with
  | zero =>
      change Measure.dirac x = Measure.dirac x ∗ Measure.dirac 0
      simp
  | succ n ih =>
      rw [kernel_pow_succ_apply, ih, incrementKernel_comp,
        Measure.convPow_succ, Measure.conv_assoc]

/-- Sum of the first `n` coordinates of an additive increment path. -/
def prefixSum (n : ℕ) (increment : ℕ → E) : E :=
  ∑ k ∈ Finset.range n, increment k

omit [MeasurableSpace E] [MeasurableAdd₂ E] in
@[simp] theorem prefixSum_zero (increment : ℕ → E) :
    prefixSum 0 increment = 0 := by simp [prefixSum]

omit [MeasurableSpace E] [MeasurableAdd₂ E] in
theorem prefixSum_succ (n : ℕ) (increment : ℕ → E) :
    prefixSum (n + 1) increment = prefixSum n increment + increment n := by
  simp [prefixSum, Finset.sum_range_succ]

theorem prefixSum_measurable (n : ℕ) : Measurable (prefixSum (E := E) n) := by
  unfold prefixSum
  exact Finset.measurable_sum (Finset.range n)
    (fun k _ => measurable_pi_apply k)

/-- Under the canonical IID sequence law, the first `n` increments have
distribution equal to the `n`-fold convolution of their common law. -/
theorem iidSequenceLaw_map_prefixSum [MeasurableSingletonClass E]
    (ν : Measure E) [IsProbabilityMeasure ν] (n : ℕ) :
    (iidSequenceLaw ν).map (prefixSum (E := E) n) = ν.convPow n := by
  induction n with
  | zero =>
      rw [Measure.convPow_zero]
      exact (hasLaw_dirac_of_ae_eq
        (P := iidSequenceLaw ν) (X := prefixSum (E := E) 0)
        (Filter.Eventually.of_forall prefixSum_zero)).map_eq
  | succ n ih =>
      have hiid := iidSequenceLaw_independent ν
      have hgroup := hiid.indepFun_finset (Finset.range n) {n}
        (by simp) (fun _ => measurable_pi_apply _)
      have hind : IndepFun (prefixSum (E := E) n)
          (fun increment : ℕ → E => increment n) (iidSequenceLaw ν) := by
        have hcomp := hgroup.comp
          (Finset.measurable_sum Finset.univ
            (fun k _ => measurable_pi_apply k))
          (measurable_pi_apply ⟨n, Finset.mem_singleton_self n⟩)
        change IndepFun (fun x : ℕ → E => ∑ k ∈ Finset.range n, x k)
          (fun x : ℕ → E => x n) (iidSequenceLaw ν)
        simpa [Function.comp_def, Finset.sum_attach] using hcomp
      have hsum := hind.hasLaw_add
        ⟨(prefixSum_measurable n).aemeasurable, ih⟩
        ⟨(measurable_pi_apply n).aemeasurable,
          iidSequenceLaw_map_apply ν n⟩
      change (iidSequenceLaw ν).map (prefixSum (E := E) (n + 1)) =
        ν.convPow n ∗ ν
      rw [show prefixSum (E := E) (n + 1) =
          prefixSum n + fun increment => increment n by
        funext increment
        exact prefixSum_succ n increment]
      exact hsum.map_eq

/-- Therefore the position at time `n` of the canonical IID random walk has
the same law as the `n`-step transition kernel. -/
theorem iidSequenceLaw_map_initial_add_prefixSum
    [MeasurableSingletonClass E] (ν : Measure E) [IsProbabilityMeasure ν]
    (n : ℕ) (initial : E) :
    (iidSequenceLaw ν).map (fun increment => initial + prefixSum n increment) =
      (incrementKernel ν ^ n) initial := by
  calc
    _ = ((iidSequenceLaw ν).map (prefixSum (E := E) n)).map
        (fun y => initial + y) := by
      rw [Measure.map_map (measurable_const_add initial) (prefixSum_measurable n)]
      rfl
    _ = (ν.convPow n).map (fun y => initial + y) := by
      rw [iidSequenceLaw_map_prefixSum]
    _ = Measure.dirac initial ∗ ν.convPow n :=
      (Measure.dirac_conv initial (ν.convPow n)).symm
    _ = _ := (incrementKernel_pow_apply ν n initial).symm

end ProbabilityTheory.BranchingRandomWalk.RandomWalk
