import Probability.BranchingRandomWalk.Walk.Law
import Mathlib.MeasureTheory.Group.Arithmetic
import Mathlib.Probability.Kernel.Composition.CompProd
import Mathlib.Probability.Kernel.Composition.MapComap

/-!
# Transition kernels of random walks

An increment law induces the translation invariant Markov kernel sending a
position `x` to the law of `x + Z`.  This is the kernel interface of an
independent increment random walk; the walk itself remains the singleton-slot
specialization of a branching random walk.
-/

open MeasureTheory
open scoped ProbabilityTheory

namespace ProbabilityTheory.BranchingRandomWalk.RandomWalk

variable {E : Type*} [MeasurableSpace E] [Add E] [MeasurableAdd₂ E]

/-- The transition kernel generated by an additive increment law. -/
noncomputable def incrementKernel (ν : Measure E) [SFinite ν] : Kernel E E :=
  Kernel.map
    ((Kernel.id : Kernel E E) ⊗ₖ Kernel.const (E × E) ν)
    (fun p : E × E => p.1 + p.2)

noncomputable instance incrementKernel.instIsMarkovKernel
    (ν : Measure E) [IsProbabilityMeasure ν] :
    IsMarkovKernel (incrementKernel ν) := by
  unfold incrementKernel
  exact Kernel.IsMarkovKernel.map _ measurable_add

/-- At `x`, the increment kernel is the pushforward of the increment law by
translation by `x`. -/
theorem incrementKernel_apply [MeasurableSingletonClass E]
    (ν : Measure E) [SFinite ν] (x : E) :
    incrementKernel ν x = ν.map (fun z => x + z) := by
  ext s hs
  rw [incrementKernel, Kernel.map_apply' _ measurable_add _ hs,
    Kernel.compProd_apply (measurable_add hs) _ _ _]
  simp only [Kernel.id_apply, Kernel.const_apply]
  rw [lintegral_dirac]
  rw [Measure.map_apply (measurable_const_add x) hs]
  rfl

end ProbabilityTheory.BranchingRandomWalk.RandomWalk
